package LMS;

import DBConnection.DBConnect;
import LMS.code.Author;
import LMS.code.Book;
import LMS.code.Category;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

import SPMS.dbConnection;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sanjalee
 */
public class LMS_ManageBook_1 extends javax.swing.JInternalFrame {

    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public LMS_ManageBook_1() {
        initComponents();
        
         conn = DBConnect.connect();
        
        
        tableload();
        
        
        Category c2 = new Category();
        
        String[] categories = null;
        int count = 0;
        
        try {
            
            categories = c2.get();
        } catch (SQLException ex) {
            Logger.getLogger(LMS_LibraryManagementSystem_1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        while(count < categories.length){
        
            categorycombo.addItem(categories[count]);
            count++;
        }
        
        Author a2 = new Author();
        
        String[] names = null;
        int namecount = 0;
        
        try {
            names = a2.get();
            //JOptionPane.showMessageDialog(null,names);
        } catch (SQLException ex) {
            Logger.getLogger(LMS_LibraryManagementSystem_1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        while(namecount < names.length){
        
            authorcombo.addItem(names[namecount]);
            namecount++;
        }
    }
    
    public void tableload(){
    
        String sql_viewBooks = "SELECT lb.ISBN, lb.name, lb.price, lb.stock, la.name as author, lc.category "
                                 + "FROM lms_book lb, lms_author la, lms_category lc "
                                 + "WHERE lb.author_id = la.id AND lb.category_id = lc.id";
        try {
            pst = conn.prepareStatement(sql_viewBooks);
            rs = pst.executeQuery();
            jTablebooks.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (SQLException ex) {
            Logger.getLogger(LMS_ManageBook_1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchbook = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        isbnText = new javax.swing.JTextField();
        authorcombo = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        categorycombo = new javax.swing.JComboBox();
        btnaddbook = new javax.swing.JButton();
        priceText = new javax.swing.JTextField();
        btnUpdateBook = new javax.swing.JButton();
        btndeletebook = new javax.swing.JButton();
        labelsearchISBN = new javax.swing.JLabel();
        isbnsearchtext = new javax.swing.JTextField();
        labelsearchname = new javax.swing.JLabel();
        searchnameText = new javax.swing.JTextField();
        searchauthorText = new javax.swing.JTextField();
        labelsearchauthor = new javax.swing.JLabel();
        btnsearchbook = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablebooks = new javax.swing.JTable();
        btnreset = new javax.swing.JButton();

        searchbook.setBackground(new java.awt.Color(255, 255, 230));

        jPanel3.setBackground(new java.awt.Color(255, 255, 230));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 26, 77));
        jLabel10.setText("Price");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 26, 77));
        jLabel7.setText("ISBN");

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 26, 77));
        jLabel9.setText("Name");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 26, 77));
        jLabel11.setText("Author");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 26, 77));
        jLabel13.setText("Category");

        btnaddbook.setBackground(new java.awt.Color(0, 179, 60));
        btnaddbook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnaddbook.setForeground(new java.awt.Color(255, 255, 255));
        btnaddbook.setText("Insert");
        btnaddbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddbookActionPerformed(evt);
            }
        });

        btnUpdateBook.setBackground(new java.awt.Color(0, 77, 153));
        btnUpdateBook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdateBook.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateBook.setText("Update");
        btnUpdateBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBookActionPerformed(evt);
            }
        });

        btndeletebook.setBackground(new java.awt.Color(255, 26, 26));
        btndeletebook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndeletebook.setForeground(new java.awt.Color(255, 255, 255));
        btndeletebook.setText("Delete");
        btndeletebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletebookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnaddbook)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(isbnText)
                            .addComponent(nameText)
                            .addComponent(priceText)
                            .addComponent(authorcombo, 0, 146, Short.MAX_VALUE)
                            .addComponent(categorycombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnUpdateBook)
                        .addGap(14, 14, 14)
                        .addComponent(btndeletebook, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(isbnText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(authorcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(categorycombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaddbook)
                    .addComponent(btnUpdateBook)
                    .addComponent(btndeletebook))
                .addGap(48, 48, 48))
        );

        labelsearchISBN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelsearchISBN.setForeground(new java.awt.Color(0, 26, 77));
        labelsearchISBN.setText("ISBN");

        isbnsearchtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnsearchtextActionPerformed(evt);
            }
        });

        labelsearchname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelsearchname.setForeground(new java.awt.Color(0, 26, 77));
        labelsearchname.setText("Name");

        searchnameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchnameTextActionPerformed(evt);
            }
        });

        searchauthorText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchauthorTextActionPerformed(evt);
            }
        });

        labelsearchauthor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelsearchauthor.setForeground(new java.awt.Color(0, 26, 77));
        labelsearchauthor.setText("Author");

        btnsearchbook.setBackground(new java.awt.Color(255, 173, 51));
        btnsearchbook.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsearchbook.setForeground(new java.awt.Color(255, 255, 255));
        btnsearchbook.setText("Search");
        btnsearchbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchbookActionPerformed(evt);
            }
        });

        jTablebooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablebooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablebooksMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablebooks);

        btnreset.setBackground(new java.awt.Color(255, 173, 51));
        btnreset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnreset.setForeground(new java.awt.Color(255, 255, 255));
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchbookLayout = new javax.swing.GroupLayout(searchbook);
        searchbook.setLayout(searchbookLayout);
        searchbookLayout.setHorizontalGroup(
            searchbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchbookLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(searchbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchbookLayout.createSequentialGroup()
                        .addComponent(labelsearchISBN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(isbnsearchtext, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(labelsearchname)
                        .addGap(27, 27, 27)
                        .addComponent(searchnameText, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(labelsearchauthor)
                        .addGap(26, 26, 26)
                        .addComponent(searchauthorText, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnsearchbook)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnreset))
                    .addGroup(searchbookLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(376, Short.MAX_VALUE))
        );
        searchbookLayout.setVerticalGroup(
            searchbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchbookLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(searchbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelsearchISBN)
                    .addComponent(isbnsearchtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelsearchname)
                    .addComponent(searchnameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelsearchauthor)
                    .addComponent(searchauthorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearchbook)
                    .addComponent(btnreset))
                .addGap(45, 45, 45)
                .addGroup(searchbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(406, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1359, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(searchbook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 917, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(searchbook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void btnaddbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddbookActionPerformed
        String isbn = isbnText.getText();
        String name = nameText.getText();
        double price = Double.parseDouble(priceText.getText());
        String author = authorcombo.getSelectedItem().toString();
        String category = categorycombo.getSelectedItem().toString();
        
        Book book = new Book();
        
        try {
            book.add(isbn, name, price, author, category);
        } catch (SQLException ex) {
            Logger.getLogger(LMS_ManageBook_1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        isbnText.setText(null);
        nameText.setText(null);
        priceText.setText(null);
        
        tableload();
    }//GEN-LAST:event_btnaddbookActionPerformed

    private void btnUpdateBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBookActionPerformed
        
        int isConfirmed = JOptionPane.showConfirmDialog(null, "Do you really want to update this information?");
        
        if(isConfirmed == 0){
        
            String isbn = isbnText.getText();
            String name = nameText.getText();
            double price = Double.parseDouble(priceText.getText());
            String author = authorcombo.getSelectedItem().toString();
            String category = categorycombo.getSelectedItem().toString();
            
            Book book = new Book();
            
            try {
                book.update(isbn, name, price, author, category);
            } catch (SQLException ex) {
                Logger.getLogger(LMS_ManageBook_1.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            tableload();
            
            JOptionPane.showMessageDialog(null,"Updated Successfully!!");
            
            isbnText.setText(null);
            nameText.setText(null);
            priceText.setText(null);
        
        }
    }//GEN-LAST:event_btnUpdateBookActionPerformed

    private void isbnsearchtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnsearchtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnsearchtextActionPerformed

    private void searchnameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchnameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchnameTextActionPerformed

    private void searchauthorTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchauthorTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchauthorTextActionPerformed

    private void jTablebooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablebooksMouseClicked
        
        int raw = jTablebooks.getSelectedRow();
        
        String isbn = jTablebooks.getValueAt(raw, 0).toString();
        String name = jTablebooks.getValueAt(raw, 1).toString();
        String price = jTablebooks.getValueAt(raw, 2).toString();
        String author = jTablebooks.getValueAt(raw, 4).toString();
        String category = jTablebooks.getValueAt(raw, 5).toString();
        
        isbnText.setText(isbn);
        nameText.setText(name);
        priceText.setText(price);
        authorcombo.setSelectedItem(author);
        categorycombo.setSelectedItem(category);
        
        
        
    }//GEN-LAST:event_jTablebooksMouseClicked

    private void btndeletebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletebookActionPerformed
        
        int isConfirmed = JOptionPane.showConfirmDialog(null, "Do you really want to delete this information?");
        
        if(isConfirmed == 0){
        
           String isbn = isbnText.getText();
           
           String sql_DeleteBook = "DELETE FROM lms_book WHERE isbn = '"+ isbn +"'";
           
           try {
                pst = conn.prepareStatement(sql_DeleteBook);
                pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(LMS_ManageMember.class.getName()).log(Level.SEVERE, null, ex);
            }
           
           tableload();
           
           isbnText.setText(null);
           nameText.setText(null);
            priceText.setText(null);
        
        }
        
    }//GEN-LAST:event_btndeletebookActionPerformed

    private void btnsearchbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchbookActionPerformed
        
        String isbnlabel = labelsearchISBN.getText();
        String namelabel = labelsearchname.getText();
        String authorlabel = labelsearchauthor.getText();

        String isbnText = isbnsearchtext.getText();
        String nameText = searchnameText.getText();
        String authorText = searchauthorText.getText();
        
        System.out.println(authorText);
        System.out.println(authorlabel);
        System.out.println(isbnText);
        
        Book book = new Book();
        
        if(nameText.equals("") && authorText.equals("")){
       
            try {
                rs = book.search(isbnlabel, isbnText);
            } catch (SQLException ex) {
                Logger.getLogger(LMS_ManageBook_1.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        else if(isbnText.equals("") && authorText.equals("")){
    
            try {
                rs = book.search(namelabel, nameText);
            } catch (SQLException ex) {
                Logger.getLogger(LMS_ManageBook_1.class.getName()).log(Level.SEVERE, null, ex);
            }
    
        }
        else if(isbnText.equals("") && nameText.equals("")){
    
            try {
                
                rs = book.search(authorlabel, authorText);

            } catch (SQLException ex) {
                Logger.getLogger(LMS_ManageBook_1.class.getName()).log(Level.SEVERE, null, ex);
            }
    
        }
        
        jTablebooks.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_btnsearchbookActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        tableload();
    }//GEN-LAST:event_btnresetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox authorcombo;
    private javax.swing.JButton btnUpdateBook;
    private javax.swing.JButton btnaddbook;
    private javax.swing.JButton btndeletebook;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsearchbook;
    private javax.swing.JComboBox categorycombo;
    private javax.swing.JTextField isbnText;
    private javax.swing.JTextField isbnsearchtext;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablebooks;
    private javax.swing.JLabel labelsearchISBN;
    private javax.swing.JLabel labelsearchauthor;
    private javax.swing.JLabel labelsearchname;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField priceText;
    private javax.swing.JTextField searchauthorText;
    private javax.swing.JPanel searchbook;
    private javax.swing.JTextField searchnameText;
    // End of variables declaration//GEN-END:variables
}
