/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HMS;

import static HMS_CODE.AssignedRoom.Room_Type;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Hashini
 */
public class HMS_RoomDetails extends javax.swing.JInternalFrame {
    
     Connection conn = null;
     PreparedStatement pst = null;
     ResultSet rs = null;
     
//         
//    public String driver = "com.microsoft.jdbc.SQLServerDriver";
//    public String url = "jdbcsqlserver://localhost::24809:databaseName=smsDB";
//    public String user = "adminK";
//    public String pw = "adminK";
    
    

    /**
     * Creates new form RoomDetails
     */
    public HMS_RoomDetails() {
        initComponents();
        
         conn = DBConnection.DBConnect.connect();
        
//        Class.forName(driver);
//        conn=DriverManger.getConnection(url,user,pw);
//        
//        conn = DBConnect.connect();
//        
        tableload();
        groupButton();
        
        
    }
    
     public void tableload(){
        try {
            String sql = "SELECT Room_No,Room_Type,No_of_Seats,Status FROM hms_room";
        
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            R_tbl.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (SQLException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Room_Panel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        R_No_Combo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        R_lux_rad = new javax.swing.JRadioButton();
        R_UPDATE_but = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        R_VIEW_but = new javax.swing.JButton();
        R_Search_but = new javax.swing.JButton();
        R_normal_rad = new javax.swing.JRadioButton();
        R_noOfseats_combo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        R_status_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        R_REMOVE_but = new javax.swing.JButton();
        R_CLEAR_but = new javax.swing.JButton();
        R_AssRoom_but = new javax.swing.JButton();
        radioClear = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        R_tbl = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(1200, 620));
        setMinimumSize(new java.awt.Dimension(1200, 620));
        setPreferredSize(new java.awt.Dimension(1200, 620));

        Room_Panel1.setBackground(new java.awt.Color(204, 204, 255));
        Room_Panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Room Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(0, 0, 204))); // NOI18N
        Room_Panel1.setMaximumSize(new java.awt.Dimension(1617, 592));
        Room_Panel1.setMinimumSize(new java.awt.Dimension(1617, 592));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        R_No_Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Room No", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Room Type");

        R_lux_rad.setText("Luxury");

        R_UPDATE_but.setBackground(new java.awt.Color(204, 204, 255));
        R_UPDATE_but.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        R_UPDATE_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_HMS/update.png"))); // NOI18N
        R_UPDATE_but.setText("Update");
        R_UPDATE_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_UPDATE_butActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Room No");

        R_VIEW_but.setBackground(new java.awt.Color(204, 204, 255));
        R_VIEW_but.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        R_VIEW_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_HMS/view.png"))); // NOI18N
        R_VIEW_but.setText("View");
        R_VIEW_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_VIEW_butActionPerformed(evt);
            }
        });

        R_Search_but.setBackground(new java.awt.Color(204, 204, 255));
        R_Search_but.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        R_Search_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_HMS/find.png"))); // NOI18N
        R_Search_but.setText("Search");
        R_Search_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_Search_butActionPerformed(evt);
            }
        });

        R_normal_rad.setText("Normal");

        R_noOfseats_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Of Seats", "1", "2" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Status");

        R_status_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_status_txtActionPerformed(evt);
            }
        });
        R_status_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                R_status_txtKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("No Of Seats");

        R_REMOVE_but.setBackground(new java.awt.Color(204, 204, 255));
        R_REMOVE_but.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        R_REMOVE_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_HMS/delete.png"))); // NOI18N
        R_REMOVE_but.setText("Remove");
        R_REMOVE_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_REMOVE_butActionPerformed(evt);
            }
        });

        R_CLEAR_but.setBackground(new java.awt.Color(204, 204, 255));
        R_CLEAR_but.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        R_CLEAR_but.setText("Clear");
        R_CLEAR_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_CLEAR_butActionPerformed(evt);
            }
        });

        R_AssRoom_but.setBackground(new java.awt.Color(204, 204, 255));
        R_AssRoom_but.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        R_AssRoom_but.setText("Assign Rooms");
        R_AssRoom_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_AssRoom_butActionPerformed(evt);
            }
        });

        radioClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(R_noOfseats_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(R_status_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(R_No_Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(R_normal_rad)
                                        .addGap(18, 18, 18)
                                        .addComponent(R_lux_rad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radioClear)))))
                        .addContainerGap(62, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(R_UPDATE_but, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(R_Search_but, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R_CLEAR_but, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(R_AssRoom_but, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(R_VIEW_but, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(R_REMOVE_but, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(R_No_Combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(radioClear, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(R_normal_rad)
                            .addComponent(R_lux_rad)))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(R_noOfseats_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(R_status_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R_UPDATE_but)
                    .addComponent(R_REMOVE_but))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(R_Search_but)
                    .addComponent(R_VIEW_but))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R_CLEAR_but)
                    .addComponent(R_AssRoom_but, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        R_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        R_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                R_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(R_tbl);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Room_Panel1Layout = new javax.swing.GroupLayout(Room_Panel1);
        Room_Panel1.setLayout(Room_Panel1Layout);
        Room_Panel1Layout.setHorizontalGroup(
            Room_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Room_Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(742, 742, 742))
        );
        Room_Panel1Layout.setVerticalGroup(
            Room_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Room_Panel1Layout.createSequentialGroup()
                .addGroup(Room_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Room_Panel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(Room_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Room_Panel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Room_Panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Room_Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void R_REMOVE_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_REMOVE_butActionPerformed

         int confirmdelete = JOptionPane.showConfirmDialog(null, "Do you really want to delete this record ?","Delete",JOptionPane.YES_NO_OPTION);
        
        if(confirmdelete==0){
            
        
        
        try{
            String sql = "DELETE FROM hms_room WHERE Room_No=?";
        
      
        
        pst = conn.prepareStatement(sql);
        
        pst.setString(1,R_No_Combo.getSelectedItem().toString());
        
        pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record Deleted Successfully !");
            
            tableload();
        }
        
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        
      
    }
    }//GEN-LAST:event_R_REMOVE_butActionPerformed

    private void R_Search_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_Search_butActionPerformed

        Room_Panel1.removeAll();
        HMS_Search_Room   Sr1 = new  HMS_Search_Room();
        Room_Panel1.add(Sr1).setVisible(true);
    }//GEN-LAST:event_R_Search_butActionPerformed

    private void R_VIEW_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_VIEW_butActionPerformed

        Room_Panel1.removeAll();
        HMS_View_Room_Details  Vrm1= new  HMS_View_Room_Details ();
        Room_Panel1.add(Vrm1).setVisible(true);
    }//GEN-LAST:event_R_VIEW_butActionPerformed

    private void R_AssRoom_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_AssRoom_butActionPerformed

        Room_Panel1.removeAll();
        HMS_Assign_Room   Ar1= new  HMS_Assign_Room();
        Room_Panel1.add(Ar1).setVisible(true);
    }//GEN-LAST:event_R_AssRoom_butActionPerformed

    private void R_UPDATE_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_UPDATE_butActionPerformed
  try{
          String sql = "UPDATE hms_room SET Room_Type=?,No_of_Seats=?,Status=? WHERE Room_No=?";
        
        pst = conn.prepareStatement(sql); 
        
        pst.setString(4, R_No_Combo.getSelectedItem().toString());
         
         if(R_normal_rad.isSelected()){
            Room_Type="Normal";
        }
        if(R_lux_rad.isSelected()){
            Room_Type="Luxury";
        }
        pst.setString(1, Room_Type);
        pst.setString(2,R_noOfseats_combo.getSelectedItem().toString());
        
        pst.setString(3, R_status_txt.getText());
                            
               
        pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record Updated Successfully !");
            
            tableload();
        }
        
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
    }                                        
    
        
          
       // try{
         // String sql = "UPDATE hms_hostelaccount SET SHID=?,Amount=?,Transaction_Date=?,Description=? WHERE AccountID=?";
        
        //pst = con.prepareStatement(sql); 
        
       // pst.setString(5, accNobx.getText());
                            
        //pst.setString(1,H_shidbx.getText());
                            
       // pst.setString(2, expensebx.getText());
        
        //pst.setString(3, descriptionbx.getText());
        
       // pst.setString(4,((JTextField)trnsctDatebx.getDateEditor().getUiComponent()).getText());
                       
        
       // pst.executeUpdate();
      //      JOptionPane.showMessageDialog(null, "Record Updated Successfully !");
       // }
        
        //catch(Exception ex){
          //  JOptionPane.showMessageDialog(null, ex);
       // }
    }//GEN-LAST:event_R_UPDATE_butActionPerformed

    private void R_status_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_status_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R_status_txtActionPerformed

    private void R_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_R_tblMouseClicked

        //mouse clicking event on the table
                
          int r = R_tbl.getSelectedRow();
        
        String Room_No = R_tbl.getValueAt(r, 0).toString();  

        TableModel model = R_tbl.getModel();
        String Room_Type = model.getValueAt(r,1).toString();   
           if(Room_Type.equals("Normal")){
               R_normal_rad.setSelected(true);
               
           }
           else{
               R_lux_rad.setSelected(true);
           }
        String No_of_Seats = R_tbl.getValueAt(r, 2).toString();
        String Status = R_tbl.getValueAt(r, 3).toString();
     
        
        R_No_Combo.setSelectedItem(Room_No);
        R_noOfseats_combo.setSelectedItem(No_of_Seats);
        R_status_txt.setText(Status);
    
    }//GEN-LAST:event_R_tblMouseClicked

    private void R_CLEAR_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_CLEAR_butActionPerformed
       
     
        R_No_Combo.setSelectedIndex(0);
        radioClear.setSelected(true);
        R_noOfseats_combo.setSelectedIndex(0);
        R_status_txt.setText(" ");
        
    }//GEN-LAST:event_R_CLEAR_butActionPerformed

    private void radioClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioClearActionPerformed

    private void R_status_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_R_status_txtKeyTyped
        
            char c = evt.getKeyChar();
        if(!((Character.isAlphabetic(c))||(c==com.sun.glass.events.KeyEvent.VK_BACKSPACE)||(c==com.sun.glass.events.KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_R_status_txtKeyTyped
private void groupButton( ) {

        ButtonGroup bg1 = new ButtonGroup( );

        bg1.add(R_normal_rad);
        bg1.add(R_lux_rad);
        bg1.add(radioClear);
        radioClear.setVisible(false);
        

        }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton R_AssRoom_but;
    private javax.swing.JButton R_CLEAR_but;
    private javax.swing.JComboBox<String> R_No_Combo;
    private javax.swing.JButton R_REMOVE_but;
    private javax.swing.JButton R_Search_but;
    private javax.swing.JButton R_UPDATE_but;
    private javax.swing.JButton R_VIEW_but;
    private javax.swing.JRadioButton R_lux_rad;
    private javax.swing.JComboBox<String> R_noOfseats_combo;
    private javax.swing.JRadioButton R_normal_rad;
    private javax.swing.JTextField R_status_txt;
    private javax.swing.JTable R_tbl;
    private javax.swing.JPanel Room_Panel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioClear;
    // End of variables declaration//GEN-END:variables
}
