/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HMS;


import DBConnection.DBConnect;
import static HMS_CODE.Boarder.Gender;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Hashini
 */
public class HMS_Student_Details extends javax.swing.JInternalFrame {
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
//    public String driver = "com.microsoft.jdbc.SQLServerDriver";
//    public String url = "jdbcsqlserver://localhost::24809:databaseName=smsDB";
//    public String user = "adminK";
//    public String pw = "adminK";
 
    

    /**
     * Creates new form Student_Details
     */
    public HMS_Student_Details() {
        
        initComponents();
        
         conn = DBConnection.DBConnect.connect();
        
//        Class.forName(driver);
//        conn=DriverManger.getConnection(url,user,pw);
        
        //connect to DB
        conn = DBConnect.connect();
        
        tableload();
        
        
           
    }
    
    public void tableload(){
        
        try { 
            
            String sql = "SELECT SHID,First_Name,Last_Name,Date_Of_Birth,Parent_Name,Parent_Phone,Grade,Class FROM hms_maleboarders";
        
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            B_tbl.setModel(DbUtils.resultSetToTableModel(rs));
            
        } 
        catch (SQLException e) {
            
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        j_PANEL = new javax.swing.JPanel();
        B_classBox_txt = new javax.swing.JTextField();
        B_gradeBox_txt = new javax.swing.JTextField();
        B_grade = new javax.swing.JLabel();
        B_pphone = new javax.swing.JLabel();
        B_fnameBox_txt = new javax.swing.JTextField();
        B_lnameBox_txt = new javax.swing.JTextField();
        B_dob = new javax.swing.JLabel();
        B_pname = new javax.swing.JLabel();
        B_pphoneBox_txt = new javax.swing.JTextField();
        B_pnameBox_txt = new javax.swing.JTextField();
        B_class = new javax.swing.JLabel();
        B_hidBox_txt = new javax.swing.JTextField();
        B_lname = new javax.swing.JLabel();
        B_hid = new javax.swing.JLabel();
        B_fname = new javax.swing.JLabel();
        B_ADD_but = new javax.swing.JButton();
        B_update_but = new javax.swing.JButton();
        B_Remove_but = new javax.swing.JButton();
        B_serch_but = new javax.swing.JButton();
        B_view_but = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        B_back_but = new javax.swing.JButton();
        B_DOB_dateCH = new com.toedter.calendar.JDateChooser();
        B_clear_but = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        B_tbl = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 255));
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(1200, 650));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setPreferredSize(new java.awt.Dimension(1200, 535));

        j_PANEL.setBackground(new java.awt.Color(204, 204, 255));
        j_PANEL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        j_PANEL.setMaximumSize(new java.awt.Dimension(1200, 650));
        j_PANEL.setMinimumSize(new java.awt.Dimension(1200, 650));
        j_PANEL.setPreferredSize(new java.awt.Dimension(1200, 650));

        B_classBox_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_classBox_txtActionPerformed(evt);
            }
        });
        B_classBox_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                B_classBox_txtKeyTyped(evt);
            }
        });

        B_gradeBox_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_gradeBox_txtActionPerformed(evt);
            }
        });
        B_gradeBox_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                B_gradeBox_txtKeyTyped(evt);
            }
        });

        B_grade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_grade.setText("Grade");

        B_pphone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_pphone.setText("Parent's Phone");

        B_fnameBox_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_fnameBox_txtActionPerformed(evt);
            }
        });
        B_fnameBox_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                B_fnameBox_txtKeyTyped(evt);
            }
        });

        B_lnameBox_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                B_lnameBox_txtKeyTyped(evt);
            }
        });

        B_dob.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_dob.setText("Date Of Birth");

        B_pname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_pname.setText("Parent Name");

        B_pphoneBox_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_pphoneBox_txtActionPerformed(evt);
            }
        });
        B_pphoneBox_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                B_pphoneBox_txtKeyTyped(evt);
            }
        });

        B_pnameBox_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_pnameBox_txtActionPerformed(evt);
            }
        });
        B_pnameBox_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                B_pnameBox_txtKeyTyped(evt);
            }
        });

        B_class.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_class.setText("Class");

        B_lname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_lname.setText("Last Name");

        B_hid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_hid.setText("Student HID");

        B_fname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_fname.setText("First Name");

        B_ADD_but.setBackground(new java.awt.Color(204, 204, 255));
        B_ADD_but.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B_ADD_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_HMS/insert.png"))); // NOI18N
        B_ADD_but.setText("Add");
        B_ADD_but.setMaximumSize(new java.awt.Dimension(133, 41));
        B_ADD_but.setMinimumSize(new java.awt.Dimension(133, 41));
        B_ADD_but.setPreferredSize(new java.awt.Dimension(133, 41));
        B_ADD_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ADD_butActionPerformed(evt);
            }
        });

        B_update_but.setBackground(new java.awt.Color(204, 204, 255));
        B_update_but.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B_update_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_HMS/update.png"))); // NOI18N
        B_update_but.setText("Update");
        B_update_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_update_butActionPerformed(evt);
            }
        });

        B_Remove_but.setBackground(new java.awt.Color(204, 204, 255));
        B_Remove_but.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B_Remove_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_HMS/delete.png"))); // NOI18N
        B_Remove_but.setText("Remove");
        B_Remove_but.setMaximumSize(new java.awt.Dimension(133, 41));
        B_Remove_but.setMinimumSize(new java.awt.Dimension(133, 41));
        B_Remove_but.setPreferredSize(new java.awt.Dimension(133, 41));
        B_Remove_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_Remove_butActionPerformed(evt);
            }
        });

        B_serch_but.setBackground(new java.awt.Color(204, 204, 255));
        B_serch_but.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B_serch_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_HMS/find.png"))); // NOI18N
        B_serch_but.setText("Search");
        B_serch_but.setMaximumSize(new java.awt.Dimension(133, 41));
        B_serch_but.setMinimumSize(new java.awt.Dimension(133, 41));
        B_serch_but.setPreferredSize(new java.awt.Dimension(133, 41));
        B_serch_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_serch_butActionPerformed(evt);
            }
        });

        B_view_but.setBackground(new java.awt.Color(204, 204, 255));
        B_view_but.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B_view_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_HMS/view.png"))); // NOI18N
        B_view_but.setText("View");
        B_view_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_view_butActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 204));
        jLabel14.setText("Boarder Details");

        B_back_but.setBackground(new java.awt.Color(204, 204, 255));
        B_back_but.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B_back_but.setText("Back");
        B_back_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_back_butActionPerformed(evt);
            }
        });

        B_DOB_dateCH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                B_DOB_dateCHKeyTyped(evt);
            }
        });

        B_clear_but.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B_clear_but.setText("Clear");
        B_clear_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_clear_butActionPerformed(evt);
            }
        });

        B_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        B_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_tblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(B_tbl);

        javax.swing.GroupLayout j_PANELLayout = new javax.swing.GroupLayout(j_PANEL);
        j_PANEL.setLayout(j_PANELLayout);
        j_PANELLayout.setHorizontalGroup(
            j_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(j_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(j_PANELLayout.createSequentialGroup()
                        .addGroup(j_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B_lname)
                            .addComponent(B_fname)
                            .addComponent(B_hid)
                            .addComponent(B_pname)
                            .addComponent(B_dob))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(j_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B_fnameBox_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_hidBox_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_lnameBox_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_DOB_dateCH, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_pnameBox_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addGroup(j_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(j_PANELLayout.createSequentialGroup()
                        .addComponent(B_grade)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j_PANELLayout.createSequentialGroup()
                        .addGroup(j_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(B_pphone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B_class, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(32, 32, 32)))
                .addGroup(j_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(j_PANELLayout.createSequentialGroup()
                        .addComponent(B_pphoneBox_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(B_ADD_but, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(j_PANELLayout.createSequentialGroup()
                        .addGroup(j_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(B_gradeBox_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_classBox_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(j_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B_serch_but, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(B_view_but, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(j_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(j_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(B_update_but, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                        .addComponent(B_back_but, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(B_Remove_but, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j_PANELLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(B_clear_but)
                .addGap(368, 368, 368))
        );
        j_PANELLayout.setVerticalGroup(
            j_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(j_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_hid)
                    .addComponent(B_hidBox_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_pphone)
                    .addComponent(B_pphoneBox_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(j_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_fname)
                    .addComponent(B_fnameBox_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_grade)
                    .addComponent(B_gradeBox_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(j_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B_lname)
                    .addGroup(j_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(B_lnameBox_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B_class)
                        .addComponent(B_classBox_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(j_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(j_PANELLayout.createSequentialGroup()
                        .addComponent(B_dob)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(B_pname))
                    .addGroup(j_PANELLayout.createSequentialGroup()
                        .addComponent(B_DOB_dateCH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B_pnameBox_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
            .addGroup(j_PANELLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(j_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_ADD_but, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Remove_but, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(j_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_serch_but, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_update_but))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(j_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(B_view_but, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_back_but, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_clear_but)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(j_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 981, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_serch_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_serch_butActionPerformed
              
              j_PANEL.removeAll();
              HMS_Search_Stu_Details   Ssd1 = new  HMS_Search_Stu_Details();
              j_PANEL.add(Ssd1).setVisible(true);
    }//GEN-LAST:event_B_serch_butActionPerformed

    private void B_view_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_view_butActionPerformed
              
              j_PANEL.removeAll();
              HMS_View_Stu_Details   Vsd1 = new  HMS_View_Stu_Details();
              j_PANEL.add(Vsd1).setVisible(true);
    }//GEN-LAST:event_B_view_butActionPerformed

    private void B_ADD_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ADD_butActionPerformed
       
        
        
        String FirstNmame = B_fnameBox_txt.getText();
        String Lastname = B_lnameBox_txt.getText();
        String DOB =  ((JTextField)B_DOB_dateCH.getDateEditor().getUiComponent()).getText();
        String pName = B_pnameBox_txt.getText();
        String pPhone = B_pphoneBox_txt.getText();
        String grade = B_gradeBox_txt.getText();
        String Class = B_classBox_txt.getText();
        
        /*if ( FirstNmame.isEmpty() || Lastname.isEmpty() || DOB.isEmpty() || pName.isEmpty() || pPhone.isEmpty() || grade.isEmpty() || Class.isEmpty()){
                    
                JOptionPane.showMessageDialog(null, "Complete all the input fields!!");
             }
        else {
        
            String pattern = B_pphoneBox_txt.getText();
            B_pphoneBox_txt.setText(pattern);
            
            if ((!pattern.isEmpty()) && (!pattern.matches("[0-9][0-9][0-9][0-9][0-9[0-9][0-9][0-9][0-9][0-9]")))
                    {
                        getToolkit().beep();
                        JOptionPane.showMessageDialog(null, "Invalid Input. Enter only 10 digits for Parent Phone!!");
                        B_pphoneBox_txt.setText("");
                    }
            else
            */
        try {
            String sql = "INSERT INTO hms_maleboarders"
                    + "(First_Name,Last_Name,Date_Of_Birth,Parent_Name,Parent_Phone,Grade,Class)"
                    + "VALUES (?,?,?,?,?,?,?)";

            pst = conn.prepareStatement(sql);
            
            pst.setString(1, B_fnameBox_txt.getText());
            
            pst.setString(2, B_lnameBox_txt.getText());
            
            pst.setString(3, ((JTextField) B_DOB_dateCH.getDateEditor().getUiComponent()).getText());
                                     
            pst.setString(4, B_pnameBox_txt.getText());
           
            pst.setString(5, B_pphoneBox_txt.getText());
            
            pst.setString(6, B_gradeBox_txt.getText());
            
            pst.setString(7, B_classBox_txt.getText());
            
          
         
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Record Inserted Successfully !");
            
             tableload();
             
        } 
           catch (Exception ex) {
               
            JOptionPane.showMessageDialog(null, ex);
        }

      
                   
        
        
    }//GEN-LAST:event_B_ADD_butActionPerformed

    private void B_Remove_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_Remove_butActionPerformed
       
         int confirmdelete = JOptionPane.showConfirmDialog(null, "Do you really want to delete this record ?","Delete",JOptionPane.YES_NO_OPTION);
        
        if(confirmdelete==0){
                            
        try{
            
            String sql = "DELETE FROM hms_maleboarders WHERE SHID=?";
        
        pst = conn.prepareStatement(sql);
        
        pst.setString(1,B_hidBox_txt.getText());
        
        pst.executeUpdate();
        
            JOptionPane.showMessageDialog(null, "Record Deleted Successfully !");
            
             tableload();
        }
        
        catch(Exception ex){
            
            JOptionPane.showMessageDialog(null, ex);
        }
        
      
    }
    }//GEN-LAST:event_B_Remove_butActionPerformed

    private void B_update_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_update_butActionPerformed
         
        try{
            
          String sql = "UPDATE hms_maleboarders SET First_Name=?,Last_Name=?,Date_Of_Birth=?,Parent_Name=?,Parent_Phone=?,Grade=?,Class=? WHERE SHID=?";
        
        pst = conn.prepareStatement(sql); 
        
        pst.setString(8, B_hidBox_txt.getText());
                            
        pst.setString(1,B_fnameBox_txt.getText());
                            
        pst.setString(2, B_lnameBox_txt.getText());
                 
        pst.setString(3, ((JTextField) B_DOB_dateCH.getDateEditor().getUiComponent()).getText());
       
        pst.setString(4, B_pnameBox_txt.getText());
        
        pst.setString(5, B_pphoneBox_txt.getText());
                     
        pst.setString(6,B_gradeBox_txt.getText());
         
        pst.setString(7,B_classBox_txt.getText());
        
        
                            
        
        pst.executeUpdate();
        
            JOptionPane.showMessageDialog(null, "Record Updated Successfully !");
            
            tableload();
        }
        
        catch(Exception ex){
            
            JOptionPane.showMessageDialog(null, ex);
        }
    
        
        
    }//GEN-LAST:event_B_update_butActionPerformed

    private void B_pphoneBox_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_pphoneBox_txtActionPerformed
       
        
        
    }//GEN-LAST:event_B_pphoneBox_txtActionPerformed

    private void B_fnameBox_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_fnameBox_txtActionPerformed
      
       
        
    }//GEN-LAST:event_B_fnameBox_txtActionPerformed

    private void B_classBox_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_classBox_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_classBox_txtActionPerformed

    private void B_pnameBox_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_pnameBox_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_pnameBox_txtActionPerformed

    private void B_pnameBox_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_B_pnameBox_txtKeyTyped

        
         char c = evt.getKeyChar();
        if(!((Character.isAlphabetic(c))||(c==com.sun.glass.events.KeyEvent.VK_BACKSPACE)||(c==com.sun.glass.events.KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
      
      
    }//GEN-LAST:event_B_pnameBox_txtKeyTyped
    }
    private void B_fnameBox_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_B_fnameBox_txtKeyTyped
    
    
         char c = evt.getKeyChar();
        if(!((Character.isAlphabetic(c))||(c==com.sun.glass.events.KeyEvent.VK_BACKSPACE)||(c==com.sun.glass.events.KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
      
     
    }//GEN-LAST:event_B_fnameBox_txtKeyTyped
    }
    private void B_pphoneBox_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_B_pphoneBox_txtKeyTyped
       
              char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==com.sun.glass.events.KeyEvent.VK_BACKSPACE)||(c==com.sun.glass.events.KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
            
        }     
        
    }//GEN-LAST:event_B_pphoneBox_txtKeyTyped

    private void B_gradeBox_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_B_gradeBox_txtKeyTyped
   
             char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==com.sun.glass.events.KeyEvent.VK_BACKSPACE)||(c==com.sun.glass.events.KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
            
        }     
    }//GEN-LAST:event_B_gradeBox_txtKeyTyped

    private void B_lnameBox_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_B_lnameBox_txtKeyTyped
       
        
         char c = evt.getKeyChar();
        if(!((Character.isAlphabetic(c))||(c==com.sun.glass.events.KeyEvent.VK_BACKSPACE)||(c==com.sun.glass.events.KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
      
    }//GEN-LAST:event_B_lnameBox_txtKeyTyped
    }   
    private void B_gradeBox_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_gradeBox_txtActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_B_gradeBox_txtActionPerformed
    
    private void B_back_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_back_butActionPerformed
       
        j_PANEL.removeAll();
        HMS_BoardersINFO viewall =new HMS_BoardersINFO ();
        j_PANEL.add(viewall).setVisible(true);
    }//GEN-LAST:event_B_back_butActionPerformed

    private void B_clear_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_clear_butActionPerformed

        B_hidBox_txt.setText(" ");
        B_fnameBox_txt.setText(" ");
        B_lnameBox_txt.setText(" ");
        B_pnameBox_txt.setText(" ");
        B_pphoneBox_txt.setText(" ");
        B_gradeBox_txt.setText(" ");
        B_classBox_txt.setText(" ");
       
    }//GEN-LAST:event_B_clear_butActionPerformed

    private void B_classBox_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_B_classBox_txtKeyTyped
       
        
         char c = evt.getKeyChar();
        if(!((Character.isAlphabetic(c))||(c==com.sun.glass.events.KeyEvent.VK_BACKSPACE)||(c==com.sun.glass.events.KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
      
        }
    }//GEN-LAST:event_B_classBox_txtKeyTyped

    private void B_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_tblMouseClicked
      
               
           int r = B_tbl.getSelectedRow();
        
        String SHID = B_tbl.getValueAt(r, 0).toString();
        String First_Name = B_tbl.getValueAt(r, 1).toString();
        String Last_Name = B_tbl.getValueAt(r, 2).toString();
        String Date_Of_Birth = B_tbl.getValueAt(r, 3).toString();
        String Parent_Name = B_tbl.getValueAt(r, 4).toString();
        String Parent_Phone = B_tbl.getValueAt(r, 5).toString();
        String Grade = B_tbl.getValueAt(r, 6).toString();
        String Class = B_tbl.getValueAt(r, 7).toString();
        
     
        try{
       
        Date date=new SimpleDateFormat("MMM d,yyyy").parse(Date_Of_Birth);
       
        B_hidBox_txt.setText(SHID);
        B_fnameBox_txt.setText(First_Name);
        B_lnameBox_txt.setText(Last_Name);
        B_DOB_dateCH.setDate(date);
        B_pnameBox_txt.setText(Parent_Name);
        B_pphoneBox_txt.setText(Parent_Phone);
        B_gradeBox_txt.setText(Grade);
        B_classBox_txt.setText(Class);
       
        }
            catch(Exception e){
                
                    JOptionPane.showMessageDialog(null,e);
                    
                    }
    }//GEN-LAST:event_B_tblMouseClicked

    private void B_DOB_dateCHKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_B_DOB_dateCHKeyTyped

        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==com.sun.glass.events.KeyEvent.VK_BACKSPACE)||(c==com.sun.glass.events.KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_B_DOB_dateCHKeyTyped
    

    
       
     /*private void required( ) {
        
        reqc1.setVisible(false);
        reqc2.setVisible(false);
        reqc4.setVisible(false);
        reqc5.setVisible(false);
        reqc6.setVisible(false);
        reqc7.setVisible(false);
        
       
        
     }*/
    
    /*public boolean validphone(){
        String phonecount = "^[0-9]{10}$";
        
        Pattern patternphone = Pattern.compile(phonecount, Pattern.CASE_INSENSITIVE);
        
        Matcher regeMatcherphone = patternphone.matcher(B_pphoneBox_txt.getText());
        if(!regeMatcherphone.matches()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Enter a valid phone number !");
            return false;
        }
        else
            return true;
        }*/
    
    
    /* public boolean isEmpty(){
            
        
        if(B_fnameBox_txt.getText().isEmpty())
            reqc1.setVisible(true);
        else
            reqc1.setVisible(false);
        if(B_lnameBox_txt.getText().isEmpty())
            reqc2.setVisible(true);
        else
            reqc2.setVisible(false);
        if(B_pnameBox_txt.getText().isEmpty())
            reqc4.setVisible(true);
        else
            reqc4.setVisible(false);
        if(B_pphoneBox_txt.getText().isEmpty())
            reqc5.setVisible(true);
        else
            reqc5.setVisible(false);
        if(B_gradeBox_txt.getText().isEmpty())
            reqc6.setVisible(true);
        else
            reqc6.setVisible(false);
        if(B_classBox_txt.getText().isEmpty())
            reqc7.setVisible(true);
        else
            reqc7.setVisible(false);
       
        
        if(!B_fnameBox_txt.getText().isEmpty()&&!B_lnameBox_txt.getText().isEmpty()&&!B_pnameBox_txt.getText().isEmpty()&&!B_pphoneBox_txt.getText().isEmpty()&&!B_gradeBox_txt.getText().isEmpty()&&!B_classBox_txt.getText().isEmpty())
            return true;
        else
        {
            JOptionPane.showMessageDialog(null, "Please Enter all the Values!");
            return false;
        }
       
        }*/
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_ADD_but;
    private com.toedter.calendar.JDateChooser B_DOB_dateCH;
    private javax.swing.JButton B_Remove_but;
    private javax.swing.JButton B_back_but;
    private javax.swing.JLabel B_class;
    private javax.swing.JTextField B_classBox_txt;
    private javax.swing.JButton B_clear_but;
    private javax.swing.JLabel B_dob;
    private javax.swing.JLabel B_fname;
    private javax.swing.JTextField B_fnameBox_txt;
    private javax.swing.JLabel B_grade;
    private javax.swing.JTextField B_gradeBox_txt;
    private javax.swing.JLabel B_hid;
    private javax.swing.JTextField B_hidBox_txt;
    private javax.swing.JLabel B_lname;
    private javax.swing.JTextField B_lnameBox_txt;
    private javax.swing.JLabel B_pname;
    private javax.swing.JTextField B_pnameBox_txt;
    private javax.swing.JLabel B_pphone;
    private javax.swing.JTextField B_pphoneBox_txt;
    private javax.swing.JButton B_serch_but;
    private javax.swing.JTable B_tbl;
    private javax.swing.JButton B_update_but;
    private javax.swing.JButton B_view_but;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel j_PANEL;
    // End of variables declaration//GEN-END:variables
}
