/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HMS;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Hashini
 */
public class HMS_Funds_Fines extends javax.swing.JInternalFrame {
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
//    public String driver = "com.microsoft.jdbc.SQLServerDriver";
//    public String url = "jdbcsqlserver://localhost::24809:databaseName=smsDB";
//    public String user = "adminK";
//    public String pw = "adminK";

    /**
     * Creates new form Funds_Fines
     */
    public HMS_Funds_Fines() {
        initComponents();
        
        
//        Class.forName(driver);
//        conn=DriverManger.getConnection(url,user,pw);
        
//        conn = DBConnect.connect();
conn = DBConnection.DBConnect.connect();
//        
         tableload();
        
    }
    
    public void tableload(){
        try {
            String sql = "SELECT FundID,SHID,Amount,Submission_Date,Description FROM hms_funds";
        
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            Fu_tbl.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (SQLException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Fundpanel1 = new javax.swing.JPanel();
        jpanelFund1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Fu_ID_txt = new javax.swing.JTextField();
        Fu_SumbitDate_DateCH = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Fu_Desc_txt = new javax.swing.JTextArea();
        Fu_VIEW_but = new javax.swing.JButton();
        Fu_Search_but = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Fu_REMOVE_but = new javax.swing.JButton();
        Fu_Amnt_txt = new javax.swing.JTextField();
        Fu_SHID_txt = new javax.swing.JTextField();
        Fu_UPDATE_but = new javax.swing.JButton();
        Fu_ADD_but = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Fu_CLEAR_but = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Fu_tbl = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(1200, 620));
        setMinimumSize(new java.awt.Dimension(1200, 620));
        setPreferredSize(new java.awt.Dimension(1200, 620));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );

        Fundpanel1.setBackground(new java.awt.Color(204, 204, 255));
        Fundpanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout Fundpanel1Layout = new javax.swing.GroupLayout(Fundpanel1);
        Fundpanel1.setLayout(Fundpanel1Layout);
        Fundpanel1Layout.setHorizontalGroup(
            Fundpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1240, Short.MAX_VALUE)
        );
        Fundpanel1Layout.setVerticalGroup(
            Fundpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );

        jpanelFund1.setBackground(new java.awt.Color(204, 204, 255));
        jpanelFund1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpanelFund1.setMaximumSize(new java.awt.Dimension(1200, 620));
        jpanelFund1.setMinimumSize(new java.awt.Dimension(1200, 620));
        jpanelFund1.setPreferredSize(new java.awt.Dimension(1200, 620));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Student Fund Details");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Submission Date");

        Fu_SumbitDate_DateCH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Fu_SumbitDate_DateCHKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Student HID");

        Fu_Desc_txt.setColumns(20);
        Fu_Desc_txt.setRows(5);
        jScrollPane2.setViewportView(Fu_Desc_txt);

        Fu_VIEW_but.setBackground(new java.awt.Color(204, 204, 255));
        Fu_VIEW_but.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Fu_VIEW_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_HMS/view.png"))); // NOI18N
        Fu_VIEW_but.setText("View");
        Fu_VIEW_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fu_VIEW_butActionPerformed(evt);
            }
        });

        Fu_Search_but.setBackground(new java.awt.Color(204, 204, 255));
        Fu_Search_but.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Fu_Search_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_HMS/find.png"))); // NOI18N
        Fu_Search_but.setText("Search");
        Fu_Search_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fu_Search_butActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Fund ID");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Description");

        Fu_REMOVE_but.setBackground(new java.awt.Color(204, 204, 255));
        Fu_REMOVE_but.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Fu_REMOVE_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_HMS/delete.png"))); // NOI18N
        Fu_REMOVE_but.setText("Remove");
        Fu_REMOVE_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fu_REMOVE_butActionPerformed(evt);
            }
        });

        Fu_Amnt_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Fu_Amnt_txtKeyTyped(evt);
            }
        });

        Fu_SHID_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Fu_SHID_txtKeyTyped(evt);
            }
        });

        Fu_UPDATE_but.setBackground(new java.awt.Color(204, 204, 255));
        Fu_UPDATE_but.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Fu_UPDATE_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_HMS/update.png"))); // NOI18N
        Fu_UPDATE_but.setText("Update");
        Fu_UPDATE_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fu_UPDATE_butActionPerformed(evt);
            }
        });

        Fu_ADD_but.setBackground(new java.awt.Color(204, 204, 255));
        Fu_ADD_but.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Fu_ADD_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_HMS/insert.png"))); // NOI18N
        Fu_ADD_but.setText("Add");
        Fu_ADD_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fu_ADD_butActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Amount");

        Fu_CLEAR_but.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Fu_CLEAR_but.setText("Clear");
        Fu_CLEAR_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fu_CLEAR_butActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fu_SumbitDate_DateCH, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fu_Amnt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fu_SHID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fu_ID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(Fu_VIEW_but, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Fu_CLEAR_but, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Fu_UPDATE_but, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Fu_ADD_but, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Fu_REMOVE_but, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Fu_Search_but, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Fu_ID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Fu_SHID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Fu_Amnt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(Fu_SumbitDate_DateCH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fu_ADD_but)
                    .addComponent(Fu_REMOVE_but))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fu_UPDATE_but)
                    .addComponent(Fu_Search_but))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fu_VIEW_but)
                    .addComponent(Fu_CLEAR_but, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Fu_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Fu_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Fu_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Fu_tbl);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpanelFund1Layout = new javax.swing.GroupLayout(jpanelFund1);
        jpanelFund1.setLayout(jpanelFund1Layout);
        jpanelFund1Layout.setHorizontalGroup(
            jpanelFund1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelFund1Layout.createSequentialGroup()
                .addGroup(jpanelFund1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelFund1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1))
                    .addGroup(jpanelFund1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(321, Short.MAX_VALUE))
        );
        jpanelFund1Layout.setVerticalGroup(
            jpanelFund1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelFund1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jpanelFund1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpanelFund1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Fundpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fundpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpanelFund1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Fu_VIEW_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fu_VIEW_butActionPerformed
         
        jpanelFund1.removeAll();
        HMS_View_Fund   Vfu1 = new  HMS_View_Fund();
        jpanelFund1.add(Vfu1).setVisible(true);
    }//GEN-LAST:event_Fu_VIEW_butActionPerformed

    private void Fu_Search_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fu_Search_butActionPerformed
       
        jpanelFund1.removeAll();
        HMS_Search_Fund  Sfun1 = new  HMS_Search_Fund();
        jpanelFund1.add(Sfun1).setVisible(true);
    }//GEN-LAST:event_Fu_Search_butActionPerformed

    private void Fu_ADD_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fu_ADD_butActionPerformed
        try {
            String sql = "INSERT INTO hms_funds"
                    + "(SHID,Amount,Submission_Date,Description)"
                    + "VALUES (?,?,?,?)";

            pst = conn.prepareStatement(sql);
            
            
           

            pst.setString(1, Fu_SHID_txt.getText());

            pst.setString(2, Fu_Amnt_txt.getText());
            
            pst.setString(3, ((JTextField) Fu_SumbitDate_DateCH.getDateEditor().getUiComponent()).getText());

            pst.setString(4, Fu_Desc_txt.getText());

             
            
            
            

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record Inserted Successfully !");
            
            tableload();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        
    }//GEN-LAST:event_Fu_ADD_butActionPerformed

    private void Fu_REMOVE_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fu_REMOVE_butActionPerformed
       
        int confirmdelete = JOptionPane.showConfirmDialog(null, "Do you really want to delete this record ?","Delete",JOptionPane.YES_NO_OPTION);
        
        if(confirmdelete==0){
            
        
        
        try{
            String sql = "DELETE FROM hms_funds WHERE FundID=?";
        
      
        
        pst = conn.prepareStatement(sql);
        
        pst.setString(1,Fu_ID_txt.getText());
        
        pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record Deleted Successfully !");
            
            tableload();
        }
        
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        
      
    }
    }//GEN-LAST:event_Fu_REMOVE_butActionPerformed

    private void Fu_UPDATE_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fu_UPDATE_butActionPerformed
       
          
        try{
          String sql = "UPDATE hms_funds SET SHID=?,Amount=?,Submission_Date=?,Description=? WHERE FundID=?";
        
        pst = conn.prepareStatement(sql); 
        
        pst.setString(5, Fu_ID_txt.getText());
                            
        pst.setString(1,Fu_SHID_txt.getText());
                            
        pst.setString(2, Fu_Amnt_txt.getText());
        
        pst.setString(3,((JTextField)Fu_SumbitDate_DateCH.getDateEditor().getUiComponent()).getText());
        
        pst.setString(4, Fu_Desc_txt.getText());
        
        
                       
        
        pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record Updated Successfully !");
            
            tableload();
        }
        
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_Fu_UPDATE_butActionPerformed

    private void Fu_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fu_tblMouseClicked

//mouse clicking event on the table        
        
         int r = Fu_tbl.getSelectedRow();
        
        String FundID = Fu_tbl.getValueAt(r, 0).toString();
        String SHID = Fu_tbl.getValueAt(r, 1).toString();
        String Amount = Fu_tbl.getValueAt(r, 2).toString();
        String Submission_Date = Fu_tbl.getValueAt(r, 3).toString();//date chooser
        String Description = Fu_tbl.getValueAt(r, 4).toString();
     try{
        Date date=new SimpleDateFormat("MMM d,yyyy").parse(Submission_Date); //date chooser
        Fu_ID_txt.setText(FundID);
        Fu_SHID_txt.setText(SHID);
        Fu_Amnt_txt.setText(Amount);
        Fu_SumbitDate_DateCH.setDate(date);
        Fu_Desc_txt.setText(Description);
     }
     catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
   }
    
    }//GEN-LAST:event_Fu_tblMouseClicked

    private void Fu_CLEAR_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fu_CLEAR_butActionPerformed

        Fu_ID_txt.setText(" ");
        Fu_SHID_txt.setText(" ");
        Fu_Amnt_txt.setText(" ");
        Fu_SumbitDate_DateCH.setCalendar(null);
        Fu_Desc_txt.setText(" ");
    }//GEN-LAST:event_Fu_CLEAR_butActionPerformed

    private void Fu_SHID_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Fu_SHID_txtKeyTyped
        
            char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==com.sun.glass.events.KeyEvent.VK_BACKSPACE)||(c==com.sun.glass.events.KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
            
        }     
    }//GEN-LAST:event_Fu_SHID_txtKeyTyped

    private void Fu_Amnt_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Fu_Amnt_txtKeyTyped
        
            char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==com.sun.glass.events.KeyEvent.VK_BACKSPACE)||(c==com.sun.glass.events.KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
            
        }     
    }//GEN-LAST:event_Fu_Amnt_txtKeyTyped

    private void Fu_SumbitDate_DateCHKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Fu_SumbitDate_DateCHKeyTyped
      
            char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==com.sun.glass.events.KeyEvent.VK_BACKSPACE)||(c==com.sun.glass.events.KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
            
        }     
    }//GEN-LAST:event_Fu_SumbitDate_DateCHKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fu_ADD_but;
    private javax.swing.JTextField Fu_Amnt_txt;
    private javax.swing.JButton Fu_CLEAR_but;
    private javax.swing.JTextArea Fu_Desc_txt;
    private javax.swing.JTextField Fu_ID_txt;
    private javax.swing.JButton Fu_REMOVE_but;
    private javax.swing.JTextField Fu_SHID_txt;
    private javax.swing.JButton Fu_Search_but;
    private com.toedter.calendar.JDateChooser Fu_SumbitDate_DateCH;
    private javax.swing.JButton Fu_UPDATE_but;
    private javax.swing.JButton Fu_VIEW_but;
    private javax.swing.JTable Fu_tbl;
    private javax.swing.JPanel Fundpanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpanelFund1;
    // End of variables declaration//GEN-END:variables
}
