/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HMS;

import DBConnection.DBConnect;
import SPMS_IREPORTS.IREPORT_PARAMETERIZED;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import java.sql.Connection;
import java.sql.DriverManager;
/**
 *
 * @author Hashini
 */
public class HMS_Student_Fines extends javax.swing.JInternalFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
//    
//    public String driver = "com.microsoft.jdbc.SQLServerDriver";
//    public String url = "jdbcsqlserver://localhost::24809:databaseName=smsDB";
//    public String user = "adminK";
//    public String pw = "adminK";

    /**
     * Creates new form Student_Fines
     */
    public HMS_Student_Fines() {
        
        initComponents();
        
         conn = DBConnection.DBConnect.connect();
        
//         Class.forName(driver);
//        conn=DriverManger.getConnection(url,user,pw);

        conn = DBConnect.connect();
        
        tableload();


    }
    
     public void tableload(){
         
        try {
            
            String sql = "SELECT FineID,SHID,Amount,Fine_Date,Description FROM hms_fines";
        
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
                        
            sfTble.setModel(DbUtils.resultSetToTableModel(rs));
            
        } 
        catch (SQLException e) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sf_CLEAR_but = new javax.swing.JPanel();
        sf_Amt_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sfSHID_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sd_Desc_txt = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        sfID_txt = new javax.swing.JTextField();
        sfADD_but = new javax.swing.JButton();
        sf_UPDATE_but = new javax.swing.JButton();
        sf_REMOVE_but = new javax.swing.JButton();
        sf_SEARCH_but = new javax.swing.JButton();
        sf_VIEW_but = new javax.swing.JButton();
        sf_finedate_dateCH = new com.toedter.calendar.JDateChooser();
        txtfineReport = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sfTble = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1200, 620));
        setMinimumSize(new java.awt.Dimension(1200, 620));
        setPreferredSize(new java.awt.Dimension(1200, 620));

        sf_CLEAR_but.setBackground(new java.awt.Color(204, 204, 255));
        sf_CLEAR_but.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Fines", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(0, 0, 204))); // NOI18N

        sf_Amt_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sf_Amt_txtKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Student HID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Amount");

        sfSHID_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sfSHID_txtKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Description");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Fine Date");

        sd_Desc_txt.setColumns(20);
        sd_Desc_txt.setRows(5);
        jScrollPane1.setViewportView(sd_Desc_txt);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Fine ID");

        sfADD_but.setBackground(new java.awt.Color(204, 204, 255));
        sfADD_but.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sfADD_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_HMS/insert.png"))); // NOI18N
        sfADD_but.setText("Add");
        sfADD_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sfADD_butActionPerformed(evt);
            }
        });

        sf_UPDATE_but.setBackground(new java.awt.Color(204, 204, 255));
        sf_UPDATE_but.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sf_UPDATE_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_HMS/update.png"))); // NOI18N
        sf_UPDATE_but.setText("Update");
        sf_UPDATE_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sf_UPDATE_butActionPerformed(evt);
            }
        });

        sf_REMOVE_but.setBackground(new java.awt.Color(204, 204, 255));
        sf_REMOVE_but.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sf_REMOVE_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_HMS/delete.png"))); // NOI18N
        sf_REMOVE_but.setText("Remove");
        sf_REMOVE_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sf_REMOVE_butActionPerformed(evt);
            }
        });

        sf_SEARCH_but.setBackground(new java.awt.Color(204, 204, 255));
        sf_SEARCH_but.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sf_SEARCH_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_HMS/find.png"))); // NOI18N
        sf_SEARCH_but.setText("Search");
        sf_SEARCH_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sf_SEARCH_butActionPerformed(evt);
            }
        });

        sf_VIEW_but.setBackground(new java.awt.Color(204, 204, 255));
        sf_VIEW_but.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sf_VIEW_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_HMS/view.png"))); // NOI18N
        sf_VIEW_but.setText("View");
        sf_VIEW_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sf_VIEW_butActionPerformed(evt);
            }
        });

        sf_finedate_dateCH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sf_finedate_dateCHKeyTyped(evt);
            }
        });

        txtfineReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfineReportActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Fine Report");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        sfTble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        sfTble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sfTbleMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(sfTble);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setText("Clear");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sf_CLEAR_butLayout = new javax.swing.GroupLayout(sf_CLEAR_but);
        sf_CLEAR_but.setLayout(sf_CLEAR_butLayout);
        sf_CLEAR_butLayout.setHorizontalGroup(
            sf_CLEAR_butLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sf_CLEAR_butLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sf_CLEAR_butLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sf_CLEAR_butLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(sf_CLEAR_butLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sfSHID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(sf_CLEAR_butLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sf_Amt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(sf_CLEAR_butLayout.createSequentialGroup()
                            .addGroup(sf_CLEAR_butLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel11))
                            .addGroup(sf_CLEAR_butLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(sf_CLEAR_butLayout.createSequentialGroup()
                                    .addGap(91, 91, 91)
                                    .addComponent(sfID_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sf_CLEAR_butLayout.createSequentialGroup()
                                    .addGap(50, 50, 50)
                                    .addComponent(sf_finedate_dateCH, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(sf_CLEAR_butLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(sf_CLEAR_butLayout.createSequentialGroup()
                        .addComponent(sfADD_but, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sf_REMOVE_but))
                    .addGroup(sf_CLEAR_butLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(sf_CLEAR_butLayout.createSequentialGroup()
                            .addComponent(sf_VIEW_but, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(sf_CLEAR_butLayout.createSequentialGroup()
                            .addComponent(sf_UPDATE_but, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(sf_SEARCH_but, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(356, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sf_CLEAR_butLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtfineReport, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton6)
                .addGap(371, 371, 371))
        );
        sf_CLEAR_butLayout.setVerticalGroup(
            sf_CLEAR_butLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sf_CLEAR_butLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(sf_CLEAR_butLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfineReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sf_CLEAR_butLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sf_CLEAR_butLayout.createSequentialGroup()
                        .addGroup(sf_CLEAR_butLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(sfID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sf_CLEAR_butLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(sfSHID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sf_CLEAR_butLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(sf_Amt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sf_CLEAR_butLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(sf_finedate_dateCH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(sf_CLEAR_butLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(sf_CLEAR_butLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sfADD_but)
                            .addComponent(sf_REMOVE_but))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sf_CLEAR_butLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sf_UPDATE_but)
                            .addComponent(sf_SEARCH_but))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sf_CLEAR_butLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sf_VIEW_but)
                            .addGroup(sf_CLEAR_butLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sf_CLEAR_but, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sf_CLEAR_but, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sf_SEARCH_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sf_SEARCH_butActionPerformed

        sf_CLEAR_but.removeAll();
        HMS_Search_Fines Sfin1 = new HMS_Search_Fines();
        sf_CLEAR_but.add(Sfin1).setVisible(true);

    }//GEN-LAST:event_sf_SEARCH_butActionPerformed

    private void sf_VIEW_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sf_VIEW_butActionPerformed

        sf_CLEAR_but.removeAll();
        HMS_Search_Fine Sfi1 = new HMS_Search_Fine();
        sf_CLEAR_but.add(Sfi1).setVisible(true);
    }//GEN-LAST:event_sf_VIEW_butActionPerformed

    private void sfADD_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sfADD_butActionPerformed

        try {
            
            String sql = "INSERT INTO hms_fines"
                    + "(SHID,Amount,Fine_Date,Description)"
                    + "VALUES (?,?,?,?)";

            pst = conn.prepareStatement(sql);
                      
            pst.setString(1, sfSHID_txt.getText());

            pst.setString(2, sf_Amt_txt.getText());
           
            pst.setString(3, ((JTextField) sf_finedate_dateCH.getDateEditor().getUiComponent()).getText());
                                    
            pst.setString(4, sd_Desc_txt.getText());

            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Record Inserted Successfully !");
            
            tableload();
            
        } 
          catch (Exception ex) {
              
            JOptionPane.showMessageDialog(null, ex);
        }


    }//GEN-LAST:event_sfADD_butActionPerformed

    private void sf_REMOVE_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sf_REMOVE_butActionPerformed
       
        int confirmdelete = JOptionPane.showConfirmDialog(null, "Do you really want to delete this record ?","Delete",JOptionPane.YES_NO_OPTION);
        
        if(confirmdelete==0){
                   
        
        try{
            
            String sql = "DELETE FROM hms_fines WHERE FineID=?";
        
      
        pst = conn.prepareStatement(sql);
        
        pst.setString(1,sfID_txt.getText());
        
        pst.executeUpdate();
        
            JOptionPane.showMessageDialog(null, "Record Deleted Successfully !");
            
            tableload();
        }
        
        catch(Exception ex){
            
            JOptionPane.showMessageDialog(null, ex);
        }
        
      
    }
    }//GEN-LAST:event_sf_REMOVE_butActionPerformed

    private void sf_UPDATE_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sf_UPDATE_butActionPerformed

        
           
        try{
            
        String sql = "UPDATE hms_fines SET SHID=?,Amount=?,Fine_Date=?,Description=? WHERE FineID=?";
        
        pst = conn.prepareStatement(sql); 
        
        pst.setString(5, sfID_txt.getText());
                            
        pst.setString(1,sfSHID_txt.getText());
                            
        pst.setString(2, sf_Amt_txt.getText());
                        
        pst.setString(3,((JTextField)sf_finedate_dateCH.getDateEditor().getUiComponent()).getText());
        
        pst.setString(4, sd_Desc_txt.getText());
                                      
        
        pst.executeUpdate();
        
            JOptionPane.showMessageDialog(null, "Record Updated Successfully !");
            
            tableload();
        }
        
        catch(Exception ex){
            
            JOptionPane.showMessageDialog(null, ex);
        }
      
    }//GEN-LAST:event_sf_UPDATE_butActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       
       //select * from hms_fines where Amount > $P{pamnt}
//       
        HashMap fp_p1 = new HashMap();
        fp_p1.put("pamt", txtfineReport.getText());

        IREPORT_PARAMETERIZED showReport_fp = new IREPORT_PARAMETERIZED("C:\\xampp\\htdocs\\ITP\\IREPORTS\\HMS_FinesP.jasper", fp_p1);
        showReport_fp.setVisible(true);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void sfTbleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sfTbleMouseClicked
        
           int r = sfTble.getSelectedRow();
        
        String FineID = sfTble.getValueAt(r, 0).toString();
        String SHID = sfTble.getValueAt(r, 1).toString();
        String Amount = sfTble.getValueAt(r, 2).toString();
        String Fine_Date = sfTble.getValueAt(r, 3).toString();
        String Description = sfTble.getValueAt(r, 4).toString();
     
        try{
            
        Date date=new SimpleDateFormat("MMM d,yyyy").parse(Fine_Date);
      
        sfID_txt.setText(FineID);
        sfSHID_txt.setText(SHID);
        sf_Amt_txt.setText(Amount);
        sf_finedate_dateCH.setDate(date);
        sd_Desc_txt.setText(Description);
        
        }
        
          catch(Exception e){
            
               JOptionPane.showMessageDialog(null,e);
       }
        
    }//GEN-LAST:event_sfTbleMouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        sfID_txt.setText(" ");
        sfSHID_txt.setText(" ");
        sf_Amt_txt.setText(" ");
        sf_finedate_dateCH.setCalendar(null);
        sd_Desc_txt.setText(" ");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void sf_Amt_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sf_Amt_txtKeyTyped
        
            char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==com.sun.glass.events.KeyEvent.VK_BACKSPACE)||(c==com.sun.glass.events.KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
            
        }     
    }//GEN-LAST:event_sf_Amt_txtKeyTyped

    private void sfSHID_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sfSHID_txtKeyTyped
       
             char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==com.sun.glass.events.KeyEvent.VK_BACKSPACE)||(c==com.sun.glass.events.KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
            
        }     
    }//GEN-LAST:event_sfSHID_txtKeyTyped

    private void sf_finedate_dateCHKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sf_finedate_dateCHKeyTyped
       
             char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==com.sun.glass.events.KeyEvent.VK_BACKSPACE)||(c==com.sun.glass.events.KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
            
        }     
    }//GEN-LAST:event_sf_finedate_dateCHKeyTyped

    private void txtfineReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfineReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfineReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea sd_Desc_txt;
    private javax.swing.JButton sfADD_but;
    private javax.swing.JTextField sfID_txt;
    private javax.swing.JTextField sfSHID_txt;
    private javax.swing.JTable sfTble;
    private javax.swing.JTextField sf_Amt_txt;
    private javax.swing.JPanel sf_CLEAR_but;
    private javax.swing.JButton sf_REMOVE_but;
    private javax.swing.JButton sf_SEARCH_but;
    private javax.swing.JButton sf_UPDATE_but;
    private javax.swing.JButton sf_VIEW_but;
    private com.toedter.calendar.JDateChooser sf_finedate_dateCH;
    private javax.swing.JTextField txtfineReport;
    // End of variables declaration//GEN-END:variables
}
