/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HMS;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Hashini
 */
public class HMS_Search_Stu_Details extends javax.swing.JInternalFrame {
    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
//        
//    public String driver = "com.microsoft.jdbc.SQLServerDriver";
//    public String url = "jdbcsqlserver://localhost::24809:databaseName=smsDB";
//    public String user = "adminK";
//    public String pw = "adminK";

    /**
     * Creates new form Search_Stu_Details
     */
    public HMS_Search_Stu_Details() {
        
        initComponents();
        
         conn = DBConnection.DBConnect.connect();
        
//        Class.forName(driver);
//        conn=DriverManger.getConnection(url,user,pw);
        
        viewStudentTable();
        
    }
    
     public void viewStudentTable(){
        
        try{
            
        String sql1 = "SELECT * FROM hms_maleboarders";
        pst = conn.prepareStatement(sql1);
        rs = pst.executeQuery();
        B_search_tbl.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        
        catch(Exception e ){
            
            JOptionPane.showMessageDialog(null, e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentInfo_panel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        B_serch_txt = new javax.swing.JTextField();
        B_serch_back_but = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        B_search_tbl = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(1200, 535));
        setMinimumSize(new java.awt.Dimension(1200, 535));
        setPreferredSize(new java.awt.Dimension(1200, 535));

        studentInfo_panel1.setBackground(new java.awt.Color(204, 204, 255));
        studentInfo_panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Boarder Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 0, 255))); // NOI18N
        studentInfo_panel1.setPreferredSize(new java.awt.Dimension(1200, 535));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Type Student HID To Search Student Details");

        B_serch_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_serch_txtActionPerformed(evt);
            }
        });
        B_serch_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                B_serch_txtKeyReleased(evt);
            }
        });

        B_serch_back_but.setBackground(new java.awt.Color(204, 204, 255));
        B_serch_back_but.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_serch_back_but.setText("Back");
        B_serch_back_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_serch_back_butActionPerformed(evt);
            }
        });

        B_search_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(B_search_tbl);

        javax.swing.GroupLayout studentInfo_panel1Layout = new javax.swing.GroupLayout(studentInfo_panel1);
        studentInfo_panel1.setLayout(studentInfo_panel1Layout);
        studentInfo_panel1Layout.setHorizontalGroup(
            studentInfo_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentInfo_panel1Layout.createSequentialGroup()
                .addGroup(studentInfo_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentInfo_panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addGap(36, 36, 36)
                        .addComponent(B_serch_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(studentInfo_panel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(studentInfo_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentInfo_panel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(studentInfo_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(studentInfo_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(studentInfo_panel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(B_serch_back_but)))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        studentInfo_panel1Layout.setVerticalGroup(
            studentInfo_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentInfo_panel1Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B_serch_back_but)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentInfo_panel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(studentInfo_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(B_serch_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentInfo_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1184, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentInfo_panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_serch_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_serch_txtActionPerformed
       
        /*DefaultTableModel table =(DefaultTableModel)jTable1.getModel();
        String search=jTextField9.getText();
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(table);
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
        
        
        try{
            String sql="SELECT * FROM hms_maleboarders WHERE SHID=?";
            
            pst=con.prepareStatement(sql);
            pst.setString(1,jTextField9.getText());
            rs=pst.executeQuery();
            
            
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }*/

    }//GEN-LAST:event_B_serch_txtActionPerformed

    private void B_serch_back_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_serch_back_butActionPerformed
      
        studentInfo_panel1.removeAll();
        HMS_Student_Details viewall =new HMS_Student_Details ();
        studentInfo_panel1.add(viewall).setVisible(true);
    }//GEN-LAST:event_B_serch_back_butActionPerformed

    private void B_serch_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_B_serch_txtKeyReleased
       
        DefaultTableModel table =(DefaultTableModel)B_search_tbl.getModel();
        String search=B_serch_txt.getText();
        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(table);
        B_search_tbl.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
        
        
        try{
            
            String sql="SELECT * FROM hms_maleboarders WHERE SHID=?";
            
            pst=conn.prepareStatement(sql);
            pst.setString(1,B_serch_txt.getText());
            rs=pst.executeQuery();
                        
            
        }
        
        catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
            
        }
    }//GEN-LAST:event_B_serch_txtKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable B_search_tbl;
    private javax.swing.JButton B_serch_back_but;
    private javax.swing.JTextField B_serch_txt;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel studentInfo_panel1;
    // End of variables declaration//GEN-END:variables
}
