/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HMS;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Hashini
 */
public class HMS_Fee_Payments extends javax.swing.JInternalFrame {
    
     Connection conn = null;
     PreparedStatement pst = null;
     ResultSet rs = null;
//     
//    public String driver = "com.microsoft.jdbc.SQLServerDriver";
//    public String url = "jdbcsqlserver://localhost::24809:databaseName=smsDB";
//    public String user = "adminK";
//    public String pw = "adminK";
    

    /**
     * Creates new form Fee_Payments
     */
    public HMS_Fee_Payments() {
        initComponents();
        
//        Class.forName(driver);
//        conn=DriverManger.getConnection(url,user,pw);
       
              
//        conn = DBConnect.connect();
 conn = DBConnection.DBConnect.connect();
        
         tableload();
    
    }
    
     public void tableload(){
        try {
            String sql = "SELECT PID,SHID,Payment,Payment_Date,Description FROM hms_payment";
        
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            fpTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (SQLException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        feePanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fpSHID_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fpID_txt = new javax.swing.JTextField();
        fpDate_dateCH = new com.toedter.calendar.JDateChooser();
        FpPaymnt_txt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        fpDesc_txt = new javax.swing.JTextArea();
        fpADD_but = new javax.swing.JButton();
        fpREMOVE_but = new javax.swing.JButton();
        fpUPDATE_txt = new javax.swing.JButton();
        fpSEARCH_but = new javax.swing.JButton();
        fpVIEW_but = new javax.swing.JButton();
        fpCLEAR_but = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        fpTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        setMaximumSize(new java.awt.Dimension(1200, 600));
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1200, 600));

        feePanel1.setBackground(new java.awt.Color(204, 204, 255));
        feePanel1.setBorder(new javax.swing.border.MatteBorder(null));
        feePanel1.setMaximumSize(new java.awt.Dimension(1184, 570));
        feePanel1.setMinimumSize(new java.awt.Dimension(1184, 570));
        feePanel1.setRequestFocusEnabled(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fee Payment", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Student HID");

        fpSHID_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fpSHID_txtKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Description");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Payment Date");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Payment");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Payment ID");

        fpDate_dateCH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fpDate_dateCHKeyTyped(evt);
            }
        });

        FpPaymnt_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FpPaymnt_txtKeyTyped(evt);
            }
        });

        fpDesc_txt.setColumns(20);
        fpDesc_txt.setRows(5);
        jScrollPane1.setViewportView(fpDesc_txt);

        fpADD_but.setBackground(new java.awt.Color(204, 204, 255));
        fpADD_but.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fpADD_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_HMS/insert.png"))); // NOI18N
        fpADD_but.setText("ADD");
        fpADD_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fpADD_butActionPerformed(evt);
            }
        });

        fpREMOVE_but.setBackground(new java.awt.Color(204, 204, 255));
        fpREMOVE_but.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fpREMOVE_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_HMS/delete.png"))); // NOI18N
        fpREMOVE_but.setText("Remove");
        fpREMOVE_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fpREMOVE_butActionPerformed(evt);
            }
        });

        fpUPDATE_txt.setBackground(new java.awt.Color(204, 204, 255));
        fpUPDATE_txt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fpUPDATE_txt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_HMS/update.png"))); // NOI18N
        fpUPDATE_txt.setText("Update");
        fpUPDATE_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fpUPDATE_txtActionPerformed(evt);
            }
        });

        fpSEARCH_but.setBackground(new java.awt.Color(204, 204, 255));
        fpSEARCH_but.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fpSEARCH_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_HMS/find.png"))); // NOI18N
        fpSEARCH_but.setText("Search");
        fpSEARCH_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fpSEARCH_butActionPerformed(evt);
            }
        });

        fpVIEW_but.setBackground(new java.awt.Color(204, 204, 255));
        fpVIEW_but.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fpVIEW_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_HMS/view.png"))); // NOI18N
        fpVIEW_but.setText("View");
        fpVIEW_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fpVIEW_butActionPerformed(evt);
            }
        });

        fpCLEAR_but.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fpCLEAR_but.setText("Clear");
        fpCLEAR_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fpCLEAR_butActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fpSHID_txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(fpID_txt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FpPaymnt_txt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fpDate_dateCH, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fpVIEW_but, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fpADD_but, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fpUPDATE_txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fpREMOVE_but, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fpSEARCH_but, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(fpCLEAR_but, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(fpID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fpSHID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(FpPaymnt_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(fpDate_dateCH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fpADD_but, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fpREMOVE_but, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fpUPDATE_txt)
                    .addComponent(fpSEARCH_but))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fpVIEW_but, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fpCLEAR_but, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fpTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        fpTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fpTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(fpTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Fee Payments Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout feePanel1Layout = new javax.swing.GroupLayout(feePanel1);
        feePanel1.setLayout(feePanel1Layout);
        feePanel1Layout.setHorizontalGroup(
            feePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(feePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        feePanel1Layout.setVerticalGroup(
            feePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feePanel1Layout.createSequentialGroup()
                .addGroup(feePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(feePanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(feePanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(feePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(feePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fpSEARCH_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fpSEARCH_butActionPerformed
      
        feePanel1.removeAll();
        HMS_Search_Fee  Sf1= new       HMS_Search_Fee ();
        feePanel1.add(Sf1).setVisible(true);
    }//GEN-LAST:event_fpSEARCH_butActionPerformed

    private void fpVIEW_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fpVIEW_butActionPerformed
        
        feePanel1.removeAll();
        HMS_View_Fee  Vf1= new  HMS_View_Fee ();
        feePanel1.add(Vf1).setVisible(true);
    }//GEN-LAST:event_fpVIEW_butActionPerformed

    private void fpADD_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fpADD_butActionPerformed
      
         try{
            String sql = "INSERT INTO hms_payment"
            + "(SHID,Payment,Payment_Date,Description)"
            + "VALUES (?,?,?,?)";
            
        
        
        pst = conn.prepareStatement(sql); 
        
     
        
         
         pst.setString(1, fpSHID_txt.getText());
                          
               
         pst.setString(2,FpPaymnt_txt.getText());
         
         pst.setString(3,((JTextField)fpDate_dateCH.getDateEditor().getUiComponent()).getText());
                   
         pst.setString(4, fpDesc_txt.getText());
        
        
    
        
        
        
        
        pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record Inserted Successfully !");
            
            tableload();
        }
        
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }//GEN-LAST:event_fpADD_butActionPerformed

    private void fpREMOVE_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fpREMOVE_butActionPerformed
        
        int confirmdelete = JOptionPane.showConfirmDialog(null, "Do you really want to delete this record ?","Delete",JOptionPane.YES_NO_OPTION);
        
        if(confirmdelete==0){
            
        
        
        try{
            String sql = "DELETE FROM hms_payment WHERE PID=?";
        
      
        
        pst = conn.prepareStatement(sql);
        
        pst.setString(1,fpID_txt.getText());
        
        pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record Deleted Successfully !");
        }
        
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        
      
    }
    }//GEN-LAST:event_fpREMOVE_butActionPerformed

    private void fpUPDATE_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fpUPDATE_txtActionPerformed
        
         try{
          String sql = "UPDATE hms_payment SET SHID=?,Payment=?,Payment_Date=?,Description=? WHERE PID=?";
        
        pst = conn.prepareStatement(sql); 
        
        pst.setString(5, fpID_txt.getText());
                            
        pst.setString(1,fpSHID_txt.getText());
                            
        pst.setString(2, FpPaymnt_txt.getText());
        
        pst.setString(3, fpDesc_txt.getText());
        
        pst.setString(4,((JTextField)fpDate_dateCH.getDateEditor().getUiComponent()).getText());
                       
        
        pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record Updated Successfully !");
            
            tableload();
        }
        
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_fpUPDATE_txtActionPerformed

    private void fpTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fpTableMouseClicked
      
        //mouse clicking event on the table
        
           int r = fpTable.getSelectedRow();
        
        String PID = fpTable.getValueAt(r, 0).toString();
        String SHID = fpTable.getValueAt(r, 1).toString();
        String Payment = fpTable.getValueAt(r, 2).toString();
        String Payment_Date = fpTable.getValueAt(r, 3).toString();
        String Description = fpTable.getValueAt(r, 4).toString();
     
       try{ 
        Date date=new SimpleDateFormat("MMM d,yyyy").parse(Payment_Date);
        fpID_txt.setText(PID);
        fpSHID_txt.setText(SHID);
        FpPaymnt_txt.setText(Payment);
        fpDate_dateCH.setDate(date);
        fpDesc_txt.setText(Description);
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null,e);
       }
        
    }//GEN-LAST:event_fpTableMouseClicked

    private void fpCLEAR_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fpCLEAR_butActionPerformed

        fpID_txt.setText(" ");
        fpSHID_txt.setText(" ");
        FpPaymnt_txt.setText(" ");
        fpDate_dateCH.setCalendar(null);
        fpDesc_txt.setText(" ");

    }//GEN-LAST:event_fpCLEAR_butActionPerformed

    private void fpSHID_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fpSHID_txtKeyTyped
       
            char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==com.sun.glass.events.KeyEvent.VK_BACKSPACE)||(c==com.sun.glass.events.KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
            
        }     
    }//GEN-LAST:event_fpSHID_txtKeyTyped

    private void FpPaymnt_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FpPaymnt_txtKeyTyped
       
            char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==com.sun.glass.events.KeyEvent.VK_BACKSPACE)||(c==com.sun.glass.events.KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
            
        }     
    }//GEN-LAST:event_FpPaymnt_txtKeyTyped

    private void fpDate_dateCHKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fpDate_dateCHKeyTyped
      
            char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==com.sun.glass.events.KeyEvent.VK_BACKSPACE)||(c==com.sun.glass.events.KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
            
        }     
    }//GEN-LAST:event_fpDate_dateCHKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        //Select PID,SHID,Payment,Payment_Date from hms_payment
        
        try {
            String fee_report = "C:\\xampp\\htdocs\\ITP\\IREPORTS\\HMS_PaymentN.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(fee_report);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
            JasperViewer.viewReport(jp, false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FpPaymnt_txt;
    private javax.swing.JPanel feePanel1;
    private javax.swing.JButton fpADD_but;
    private javax.swing.JButton fpCLEAR_but;
    private com.toedter.calendar.JDateChooser fpDate_dateCH;
    private javax.swing.JTextArea fpDesc_txt;
    private javax.swing.JTextField fpID_txt;
    private javax.swing.JButton fpREMOVE_but;
    private javax.swing.JButton fpSEARCH_but;
    private javax.swing.JTextField fpSHID_txt;
    private javax.swing.JTable fpTable;
    private javax.swing.JButton fpUPDATE_txt;
    private javax.swing.JButton fpVIEW_but;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
