export const GET_ITEMS = "GET_ITEMS";
export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";

export const GET_TRAINS = "GET_TRAINS";
export const ADD_TRAIN = "ADD_TRAIN";
export const DELETE_TRAIN = "DELETE_TRAIN";

export const ADD_CREDITCARDPAYMENT = "ADD_CREDITCARDPAYMENT";
export const ADD_MOBILEBILLPAYMENT = "ADD_MOBILEBILLPAYMENT";
export const GET_MOBILEBILLPAYMENT = "GET_MOBILEBILLPAYMENT";
export const GET_CREDITCARDPAYMENT = "GET_CREDITCARDPAYMENT";

export const ADD_GOVEMP = "ADD_GOVEMP";
export const DELETE_GOVEMP = "DELETE_GOVEMP";
export const GET_GOVEMPS = "GET_GOVEMPS";

export const ITEMS_LOADING = "ITEMS_LOADING";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
