/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iuds;
//DISPLAY TO LOGGED IN ADMIN TO EDIT RECORDS
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.Document;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;









/**
 *
 * @author Himashi
 */

public class AssignGradesandCalcGPA extends javax.swing.JFrame {
    
    
    Connection conn =null;
    PreparedStatement pst = null;
    ResultSet rs=null;
    

    /**
     * Creates new form NewJFrame
     */
    public AssignGradesandCalcGPA() {
        initComponents();
        conn = dbConnect.connectToDb();
        
        currentDate();
    }

    
    public void currentDate(){
        
        
        Thread clock = new Thread(){
            public void run(){
                for(;;){
                    Calendar cal = new GregorianCalendar();
                    int month = cal.get(Calendar.MONTH);
                    int year = cal.get(Calendar.YEAR);
                    int day = cal.get(Calendar.DAY_OF_MONTH);
                    mnu_date.setText("Date "+year+"/"+(month+1)+"/"+day);
        
        
                    int second = cal.get(Calendar.SECOND);
                    int mins = cal.get(Calendar.MINUTE);
                    int hrs = cal.get(Calendar.HOUR);
                    mnu_time.setText("Time "+hrs+":"+(mins)+":"+second);
                    
                    
                    try {
                        sleep(1000);
                    } 
                    catch (InterruptedException ex) {
                        Logger.getLogger(AssignGradesandCalcGPA.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
            }
            
            
            
        };
        clock.start();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        txt_gm7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_gm9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_gm8 = new javax.swing.JTextField();
        txt_gm10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_gm6 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_gcid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_gm1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_gm2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_gm3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_gm4 = new javax.swing.JTextField();
        txt_gm5 = new javax.swing.JTextField();
        txt_gca = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_gsid = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txt_gprg = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txt_geid = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txt_gasem = new javax.swing.JTextField();
        btn_calcgpa = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_s_gsid = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txt_grm11 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_grm12 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_grm13 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_grm14 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_grm15 = new javax.swing.JTextField();
        txt_grgpa = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_grstatus = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnu_date = new javax.swing.JMenu();
        mnu_time = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jRadioButton1.setText("jRadioButton1");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Module 2 Marks ");

        txt_gm7.setEditable(false);
        txt_gm7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_gm7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gm7ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Module 1 Marks ");

        txt_gm9.setEditable(false);
        txt_gm9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_gm9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gm9ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Module 3 Marks ");

        txt_gm8.setEditable(false);
        txt_gm8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_gm8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gm8ActionPerformed(evt);
            }
        });

        txt_gm10.setEditable(false);
        txt_gm10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_gm10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gm10ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Module 4 Marks ");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Module 5 Marks ");

        txt_gm6.setEditable(false);
        txt_gm6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_gm6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gm6ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Assign Grades and Calculate GPA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(255, 0, 0))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(102, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Marks Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 0, 0))); // NOI18N

        txt_gcid.setEditable(false);
        txt_gcid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_gcid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gcidActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Course_ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Module 1 Marks ");

        txt_gm1.setEditable(false);
        txt_gm1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_gm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gm1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Module 2 Marks ");

        txt_gm2.setEditable(false);
        txt_gm2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_gm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gm2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Module 3 Marks ");

        txt_gm3.setEditable(false);
        txt_gm3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_gm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gm3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Module 4 Marks ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Module 5 Marks ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("CA Marks ");

        txt_gm4.setEditable(false);
        txt_gm4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_gm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gm4ActionPerformed(evt);
            }
        });

        txt_gm5.setEditable(false);
        txt_gm5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_gm5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gm5ActionPerformed(evt);
            }
        });

        txt_gca.setEditable(false);
        txt_gca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_gca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gcaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Student_ID");

        txt_gsid.setEditable(false);
        txt_gsid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_gsid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gsidActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Program");

        txt_gprg.setEditable(false);
        txt_gprg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_gprg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gprgActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Exam_ID");

        txt_geid.setEditable(false);
        txt_geid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_geid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_geidActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Academic Semester");

        txt_gasem.setEditable(false);
        txt_gasem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_gasem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gasemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(341, 341, 341))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(94, 94, 94))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(102, 102, 102)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_gm2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_gm5)
                                        .addComponent(txt_gm4)
                                        .addComponent(txt_gca, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(20, 20, 20))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txt_gm1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_gm3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(txt_gcid, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(txt_gsid, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(txt_gprg, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(txt_geid, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(txt_gasem, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_gsid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_gprg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_gcid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_geid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_gasem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_gm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_gm2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_gm3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_gm4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_gm5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_gca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btn_calcgpa.setBackground(new java.awt.Color(204, 204, 204));
        btn_calcgpa.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_calcgpa.setForeground(new java.awt.Color(255, 0, 0));
        btn_calcgpa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/insert.png"))); // NOI18N
        btn_calcgpa.setText("Assign Grades and Calculate GPA");
        btn_calcgpa.setIconTextGap(14);
        btn_calcgpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcgpaActionPerformed(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(204, 204, 204));
        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(255, 0, 0));
        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clear.png"))); // NOI18N
        btn_clear.setText("CLEAR");
        btn_clear.setIconTextGap(14);
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Student_ID");

        txt_s_gsid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_s_gsid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_s_gsidKeyReleased(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(102, 255, 153));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Module 1 Grade ");

        txt_grm11.setEditable(false);
        txt_grm11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_grm11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_grm11ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Module 2 Grade ");

        txt_grm12.setEditable(false);
        txt_grm12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_grm12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_grm12ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Module 3 Grade ");

        txt_grm13.setEditable(false);
        txt_grm13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_grm13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_grm13ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Module 4 Grade ");

        txt_grm14.setEditable(false);
        txt_grm14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_grm14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_grm14ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Module 5 Grade ");

        txt_grm15.setEditable(false);
        txt_grm15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_grm15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_grm15ActionPerformed(evt);
            }
        });

        txt_grgpa.setEditable(false);
        txt_grgpa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_grgpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_grgpaActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("GPA");

        txt_grstatus.setEditable(false);
        txt_grstatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_grstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_grstatusActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Status");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(txt_grstatus, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(txt_grgpa, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                        .addGap(20, 20, 20))))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(321, 321, 321))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(94, 94, 94))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(102, 102, 102)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_grm12, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_grm15)
                                        .addComponent(txt_grm14))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txt_grm11, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_grm13, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGap(20, 20, 20)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(290, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txt_grgpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txt_grstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(112, 112, 112)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_grm11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_grm12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(txt_grm13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(txt_grm14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(txt_grm15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(113, Short.MAX_VALUE)))
        );

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/generatetrans.png"))); // NOI18N
        jButton1.setText("Genarate Transcript");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
                .addComponent(txt_s_gsid, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                .addGap(125, 125, 125))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btn_calcgpa)
                .addGap(182, 182, 182)
                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(175, 175, 175))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_s_gsid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_calcgpa)
                        .addComponent(btn_clear))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jMenu3.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Home");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);
        jMenu3.add(jSeparator1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Close Window");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("About");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("About this System");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar2.add(jMenu4);

        mnu_date.setText("Date");
        jMenuBar2.add(mnu_date);

        mnu_time.setText("Time");
        jMenuBar2.add(mnu_time);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calcgpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcgpaActionPerformed
        
        
        
        
        double m1=Float.parseFloat(txt_gm1.getText());
        double m2=Float.parseFloat(txt_gm2.getText());
        double m3=Float.parseFloat(txt_gm3.getText());
        double m4=Float.parseFloat(txt_gm4.getText());
        double m5=Float.parseFloat(txt_gm5.getText());
        double ca=Float.parseFloat(txt_gca.getText());
        
        
        double gradepoints = 0;
        double tpoints=0;
        String grade = null;
       
        try{
        
        //if(rs.next()){
        
        if(m1<=100 && m1>=80){
            gradepoints=4.0;
            tpoints=tpoints+gradepoints;
            grade="A";
            txt_grm11.setText(grade);
        }
        else if(m1<=79 && m1>=75){
            gradepoints=3.7;
            tpoints=tpoints+gradepoints;
            grade="A-";
            txt_grm11.setText(grade);
        }
        else if(m1<=74 && m1>=70){
            gradepoints=3.3;
            tpoints=tpoints+gradepoints;
            grade="B+";
            txt_grm11.setText(grade);
        }
        else if(m1<=69 && m1>=65){
            gradepoints=3.0;
            tpoints=tpoints+gradepoints;
            grade="B";
            txt_grm11.setText(grade);
        }
        else if(m1<=64 && m1>=60){
            gradepoints=2.4;
            tpoints=tpoints+gradepoints;
            grade="B-";
            txt_grm11.setText(grade);
        }
        else if(m1<=59 && m1>=55){
            gradepoints=2.3;
            tpoints=tpoints+gradepoints;
            grade="C+";
            txt_grm11.setText(grade);
        }
        else if(m1<=54 && m1>=50){
            gradepoints=2.0;
            tpoints=tpoints+gradepoints;
            grade="C";
            txt_grm11.setText(grade);
        }
        else if(m1<=49 && m1>=45){
            gradepoints=1.7;
            tpoints=tpoints+gradepoints;
            grade="C-";
            txt_grm11.setText(grade);
        }
        else if(m1<=44 && m1>=40){
            gradepoints=1.3;
            tpoints=tpoints+gradepoints;
            grade="D+";
            txt_grm11.setText(grade);
        }
        else if(m1<=39 && m1>=35){
            gradepoints=1.0;
            tpoints=tpoints+gradepoints;
            grade="D";
            txt_grm11.setText(grade);
        }
        else if(m1<=34 && m1>=0){
            gradepoints=0.0;
            tpoints=tpoints+gradepoints;
            grade="E";
            txt_grm11.setText(grade);
        }
        
        
        if(m2<=100 && m2>=80){
            gradepoints=4.0;
            tpoints=tpoints+gradepoints;
            grade="A";
            txt_grm12.setText(grade);
        }
        else if(m2<=79 && m2>=75){
            gradepoints=3.7;
            tpoints=tpoints+gradepoints;
            grade="A-";
            txt_grm12.setText(grade);
        }
        else if(m2<=74 && m2>=70){
            gradepoints=3.3;
            tpoints=tpoints+gradepoints;
            grade="B+";
            txt_grm12.setText(grade);
        }
        else if(m2<=69 && m2>=65){
            gradepoints=3.0;
            tpoints=tpoints+gradepoints;
            grade="B";
            txt_grm12.setText(grade);
        }
        else if(m2<=64 && m2>=60){
            gradepoints=2.4;
            tpoints=tpoints+gradepoints;
            grade="B-";
            txt_grm12.setText(grade);
        }
        else if(m2<=59 && m2>=55){
            gradepoints=2.3;
            tpoints=tpoints+gradepoints;
            grade="C+";
            txt_grm12.setText(grade);
        }
        else if(m2<=54 && m2>=50){
            gradepoints=2.0;
            tpoints=tpoints+gradepoints;
            grade="C";
            txt_grm12.setText(grade);
        }
        else if(m2<=49 && m2>=45){
            gradepoints=1.7;
            tpoints=tpoints+gradepoints;
            grade="C-";
            txt_grm12.setText(grade);
        }
        else if(m2<=44 && m2>=40){
            gradepoints=1.3;
            tpoints=tpoints+gradepoints;
            grade="D+";
            txt_grm12.setText(grade);
        }
        else if(m2<=39 && m2>=35){
            gradepoints=1.0;
            tpoints=tpoints+gradepoints;
            grade="D";
            txt_grm12.setText(grade);
        }
        else if(m2<=34 && m2>=0){
            gradepoints=0.0;
            tpoints=tpoints+gradepoints;
            grade="E";
            txt_grm12.setText(grade);
        }
        
        
        if(m3<=100 && m3>=80){
            gradepoints=4.0;
            tpoints=tpoints+gradepoints;
            grade="A";
            txt_grm13.setText(grade);
        }
        else if(m3<=79 && m3>=75){
            gradepoints=3.7;
            tpoints=tpoints+gradepoints;
            grade="A-";
            txt_grm13.setText(grade);
        }
        else if(m3<=74 && m3>=70){
            gradepoints=3.3;
            tpoints=tpoints+gradepoints;
            grade="B+";
            txt_grm13.setText(grade);
        }
        else if(m3<=69 && m3>=65){
            gradepoints=3.0;
            tpoints=tpoints+gradepoints;
            grade="B";
            txt_grm13.setText(grade);
        }
        else if(m3<=64 && m3>=60){
            gradepoints=2.4;
            tpoints=tpoints+gradepoints;
            grade="B-";
            txt_grm13.setText(grade);
        }
        else if(m3<=59 && m3>=55){
            gradepoints=2.3;
            tpoints=tpoints+gradepoints;
            grade="C+";
            txt_grm13.setText(grade);
        }
        else if(m3<=54 && m3>=50){
            gradepoints=2.0;
            tpoints=tpoints+gradepoints;
            grade="C";
            txt_grm13.setText(grade);
        }
        else if(m3<=49 && m3>=45){
            gradepoints=1.7;
            tpoints=tpoints+gradepoints;
            grade="C-";
            txt_grm13.setText(grade);
        }
        else if(m3<=44 && m3>=40){
            gradepoints=1.3;
            tpoints=tpoints+gradepoints;
            grade="D+";
            txt_grm13.setText(grade);
        }
        else if(m3<=39 && m3>=35){
            gradepoints=1.0;
            tpoints=tpoints+gradepoints;
            grade="D";
            txt_grm13.setText(grade);
        }
        else if(m3<=34 && m3>=0){
            gradepoints=0.0;
            tpoints=tpoints+gradepoints;
            grade="E";
            txt_grm13.setText(grade);
        }
        
        
        
        if(m4<=100 && m4>=80){
            gradepoints=4.0;
            tpoints=tpoints+gradepoints;
            grade="A";
            txt_grm14.setText(grade);
        }
        else if(m4<=79 && m4>=75){
            gradepoints=3.7;
            tpoints=tpoints+gradepoints;
            grade="A-";
            txt_grm14.setText(grade);
        }
        else if(m4<=74 && m4>=70){
            gradepoints=3.3;
            tpoints=tpoints+gradepoints;
            grade="B+";
            txt_grm14.setText(grade);
        }
        else if(m4<=69 && m4>=65){
            gradepoints=3.0;
            tpoints=tpoints+gradepoints;
            grade="B";
            txt_grm14.setText(grade);
        }
        else if(m4<=64 && m4>=60){
            gradepoints=2.4;
            tpoints=tpoints+gradepoints;
            grade="B-";
            txt_grm14.setText(grade);
        }
        else if(m4<=59 && m4>=55){
            gradepoints=2.3;
            tpoints=tpoints+gradepoints;
            grade="C+";
            txt_grm14.setText(grade);
        }
        else if(m4<=54 && m4>=50){
            gradepoints=2.0;
            tpoints=tpoints+gradepoints;
            grade="C";
            txt_grm14.setText(grade);
        }
        else if(m4<=49 && m4>=45){
            gradepoints=1.7;
            tpoints=tpoints+gradepoints;
            grade="C-";
            txt_grm14.setText(grade);
        }
        else if(m4<=44 && m4>=40){
            gradepoints=1.3;
            tpoints=tpoints+gradepoints;
            grade="D+";
            txt_grm14.setText(grade);
        }
        else if(m4<=39 && m4>=35){
            gradepoints=1.0;
            tpoints=tpoints+gradepoints;
            grade="D";
            txt_grm14.setText(grade);
        }
        else if(m4<=34 && m4>=0){
            gradepoints=0.0;
            tpoints=tpoints+gradepoints;
            grade="E";
            txt_grm14.setText(grade);
        }
        
        
        
        if(m5<=100 && m5>=80){
            gradepoints=4.0;
            tpoints=tpoints+gradepoints;
            grade="A";
            txt_grm15.setText(grade);
        }
        else if(m5<=79 && m5>=75){
            gradepoints=3.7;
            tpoints=tpoints+gradepoints;
            grade="A-";
            txt_grm15.setText(grade);
        }
        else if(m5<=74 && m5>=70){
            gradepoints=3.3;
            tpoints=tpoints+gradepoints;
            grade="B+";
            txt_grm15.setText(grade);
        }
        else if(m5<=69 && m5>=65){
            gradepoints=3.0;
            tpoints=tpoints+gradepoints;
            grade="B";
            txt_grm15.setText(grade);
        }
        else if(m5<=64 && m5>=60){
            gradepoints=2.4;
            tpoints=tpoints+gradepoints;
            grade="B-";
            txt_grm15.setText(grade);
        }
        else if(m5<=59 && m5>=55){
            gradepoints=2.3;
            tpoints=tpoints+gradepoints;
            grade="C+";
            txt_grm15.setText(grade);
        }
        else if(m5<=54 && m5>=50){
            gradepoints=2.0;
            tpoints=tpoints+gradepoints;
            grade="C";
            txt_grm15.setText(grade);
        }
        else if(m5<=49 && m5>=45){
            gradepoints=1.7;
            tpoints=tpoints+gradepoints;
            grade="C-";
            txt_grm15.setText(grade);
        }
        else if(m5<=44 && m5>=40){
            gradepoints=1.3;
            tpoints=tpoints+gradepoints;
            grade="D+";
            txt_grm15.setText(grade);
        }
        else if(m5<=39 && m5>=35){
            gradepoints=1.0;
            tpoints=tpoints+gradepoints;
            grade="D";
            txt_grm15.setText(grade);
        }
        else if(m5<=34 && m5>=0){
            gradepoints=0.0;
            tpoints=tpoints+gradepoints;
            grade="E";
            txt_grm15.setText(grade);
        }
        
        
        double gpa=tpoints/5.0;
       
        txt_grgpa.setText(String.valueOf(gpa).toString());
        
        double finalMark=((((m1+m2+m3+m4+m5)/100.0)*60)+ca);
        if(finalMark>=45)
            txt_grstatus.setText("Pass");
        else
            txt_grstatus.setText("Fail");
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        
        
        
        }
        
        
        
        
        
        
        try{
            String sql = "INSERT INTO exam_results"
            + "(program,cid,exam_id,academic_sem,sid,module_1,module_2,module_3,module_4,module_5,gpa,status)"
            + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";
        
        
        pst = conn.prepareStatement(sql);
        
        pst.setString(1,txt_gprg.getText());
        pst.setString(2,txt_gcid.getText());
        pst.setString(3,txt_geid.getText());
        pst.setString(4,txt_gasem.getText());
        pst.setString(5,txt_gsid.getText());
        pst.setString(6,txt_grm11.getText());
        pst.setString(7,txt_grm12.getText());
        pst.setString(8,txt_grm13.getText());
        pst.setString(9,txt_grm14.getText());
        pst.setString(10,txt_grm15.getText());
        pst.setString(11,txt_grgpa.getText());
        pst.setString(12,txt_grstatus.getText());
        
        
        pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record Inserted Successfully !");
        }
        
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        
        
    
    
    }//GEN-LAST:event_btn_calcgpaActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        
        txt_s_gsid.setText(" ");
        txt_gsid.setText(" ");
        txt_gcid.setText(" ");
        txt_gprg.setText(" ");
        txt_geid.setText(" ");
        txt_gasem.setText(" ");
        txt_gm1.setText(" ");
        txt_gm2.setText(" ");
        txt_gm3.setText(" ");
        txt_gm4.setText(" ");
        txt_gm5.setText(" ");
        txt_gca.setText(" ");
        txt_grm11.setText(" ");
        txt_grm12.setText(" ");
        txt_grm13.setText(" ");
        txt_grm14.setText(" ");
        txt_grm15.setText(" ");
        txt_grgpa.setText(" ");
        txt_grstatus.setText(" ");
        

        
        
            }//GEN-LAST:event_btn_clearActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
            
        System.exit(0);


    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

           dispose();
           new Home().setVisible(true);


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void txt_gm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gm1ActionPerformed

    private void txt_gm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gm2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gm2ActionPerformed

    private void txt_gcidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gcidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gcidActionPerformed

    private void txt_gm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gm3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gm3ActionPerformed

    private void txt_gm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gm4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gm4ActionPerformed

    private void txt_gm5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gm5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gm5ActionPerformed

    private void txt_gcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gcaActionPerformed

    private void txt_gsidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gsidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gsidActionPerformed

    private void txt_s_gsidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_s_gsidKeyReleased
            
        try {
            String sql ="SELECT * FROM exam_marks WHERE sid=?";
            
            pst=conn.prepareStatement(sql);
            
            pst.setString(1, txt_s_gsid.getText());
            
            rs=pst.executeQuery();
            
            if(rs.next()){
            
            String t1=rs.getString("sid");
            txt_gsid.setText(t1);
            
            String t2=rs.getString("program");
            txt_gprg.setText(t2);
            
            String t3=rs.getString("cid");
            txt_gcid.setText(t3);
            
            String t4=rs.getString("exam_id");
            txt_geid.setText(t4);
            
            String t5=rs.getString("academic_sem");
            txt_gasem.setText(t5);
            
            String t6=rs.getString("module_1_mark");
            txt_gm1.setText(t6);
            
            String t7=rs.getString("module_2_mark");
            txt_gm2.setText(t7);
            
            String t8=rs.getString("module_3_mark");
            txt_gm3.setText(t8);
            
            String t9=rs.getString("module_4_mark");
            txt_gm4.setText(t9);
            
            String t10=rs.getString("module_5_mark");
            txt_gm5.setText(t10);
            
            String t11=rs.getString("ca_marks");
            txt_gca.setText(t11);
            
            }
            
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
        
          
        
    
        
    }//GEN-LAST:event_txt_s_gsidKeyReleased

    private void txt_gm6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gm6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gm6ActionPerformed

    private void txt_gm7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gm7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gm7ActionPerformed

    private void txt_gm8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gm8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gm8ActionPerformed

    private void txt_gm9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gm9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gm9ActionPerformed

    private void txt_gm10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gm10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gm10ActionPerformed

    private void txt_grm11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_grm11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_grm11ActionPerformed

    private void txt_grm12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_grm12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_grm12ActionPerformed

    private void txt_grm13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_grm13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_grm13ActionPerformed

    private void txt_grm14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_grm14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_grm14ActionPerformed

    private void txt_grm15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_grm15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_grm15ActionPerformed

    private void txt_grgpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_grgpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_grgpaActionPerformed

    private void txt_grstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_grstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_grstatusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        
        HashMap fp_p1 = new HashMap();
        fp_p1.put("sid",txt_gsid.getText());
        
        
        IReport_parameterized showReport_fp = new IReport_parameterized("src/iReports/ParameterizedResultsSheet.jasper",fp_p1);
        showReport_fp.setVisible(true);
        
        
        
        
        
        /************
        try {
            
            
            //String report = "C:\\xampp\\htdocs\\SIMS\\JavaFiles\\NEW_IUDS_COPY\\Transcript.jrxml";
            JasperDesign jd = JRXmlLoader.load("C:\\xampp\\htdocs\\SIMS\\JavaFiles\\NEW_IUDS_COPY\\Transcript.jrxml");
            
            
            //String studentid=txt_gsid.getText();
            String sql = "SELECT * FROM exam_results order by sid";//WHERE sid=?";
            
            /*
            pst=conn.prepareStatement(sql);
            pst.setString(1,studentid);
            rs=pst.executeQuery();
            */
          
        
        /*
            JRDesignQuery  newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            
            
            JasperReport jr = JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, null,conn);
            JasperViewer.viewReport(jp,false);
      
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            
        }
        *******************************
        
        */
        
        /*
            String value=txt_gsid.getText();
            String value0=txt_gcid.getText();
            String value1=txt_grm11.getText();
            String value2=txt_grm12.getText();
            String value3=txt_grm13.getText();
            String value4=txt_grm14.getText();
            String value5=txt_grm15.getText();
            String value6=txt_grgpa.getText();
            String value7=txt_grstatus.getText();
            
            
           JFileChooser dialog = new JFileChooser();
           dialog.setSelectedFile(new File(value+" -Transcript"+".pdf"));
           int dialogResult=dialog.showSaveDialog(null);
           if(dialogResult==JFileChooser.APPROVE_OPTION){
               String filePath=dialog.getSelectedFile().getPath();
               
               try {
                   
                   
                   Document myDocument = new Document();
                   pdfWriter myWriter = pdfWriter.getInstance(myDocument,new fileOutputStream(filePath));
                   
                   myDocument.open();
                   
                   
                   myDocument.close();
                    JOptionPane.showMessageDialog(null, "Report was successfully generated");
                    
                   
                   
                   
                   
               } catch (Exception e) {
                   JOptionPane.showMessageDialog(null, e);
               }
               
               
           }
           
          
           
           
        */
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_gprgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gprgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gprgActionPerformed

    private void txt_geidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_geidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_geidActionPerformed

    private void txt_gasemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gasemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gasemActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
      
        new ABOUT().setVisible(true); 
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /*
     public void showTableData(){
         try{
            //conn = DriverManager.getConnection("jdbc:mysql://localhost/iuds","root","");
            
            String sql = "SELECT * FROM iudstbl";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            
            jTable_stu.setModel(DbUtils.resultSetToTableModel(rs));
         }
         catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);

         }
            
        }
    */
    
    
    
    
     
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignGradesandCalcGPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignGradesandCalcGPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignGradesandCalcGPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignGradesandCalcGPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignGradesandCalcGPA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcgpa;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mnu_date;
    private javax.swing.JMenu mnu_time;
    private javax.swing.JTextField txt_gasem;
    private javax.swing.JTextField txt_gca;
    private javax.swing.JTextField txt_gcid;
    private javax.swing.JTextField txt_geid;
    private javax.swing.JTextField txt_gm1;
    private javax.swing.JTextField txt_gm10;
    private javax.swing.JTextField txt_gm2;
    private javax.swing.JTextField txt_gm3;
    private javax.swing.JTextField txt_gm4;
    private javax.swing.JTextField txt_gm5;
    private javax.swing.JTextField txt_gm6;
    private javax.swing.JTextField txt_gm7;
    private javax.swing.JTextField txt_gm8;
    private javax.swing.JTextField txt_gm9;
    private javax.swing.JTextField txt_gprg;
    private javax.swing.JTextField txt_grgpa;
    private javax.swing.JTextField txt_grm11;
    private javax.swing.JTextField txt_grm12;
    private javax.swing.JTextField txt_grm13;
    private javax.swing.JTextField txt_grm14;
    private javax.swing.JTextField txt_grm15;
    private javax.swing.JTextField txt_grstatus;
    private javax.swing.JTextField txt_gsid;
    private javax.swing.JTextField txt_s_gsid;
    // End of variables declaration//GEN-END:variables

    private ImageIcon format = null;
    String filename =null;
    int s = 0;
    byte[] profile_pic=null;
    private String feedback;
   
}
