/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iuds;
//DISPLAY TO LOGGED IN ADMIN TO EDIT RECORDS
import com.sun.glass.events.KeyEvent;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import java.util.regex.MatchResult.*;
import java.util.regex.Matcher;









/**
 *
 * @author Himashi
 */

public class Student_IUDSV_AdminTask extends javax.swing.JFrame {
    
    
    Connection conn =null;
    PreparedStatement pst = null;
    ResultSet rs=null;
    

    /**
     * Creates new form NewJFrame
     */
    public Student_IUDSV_AdminTask() {
        
        initComponents();
        conn = dbConnect.connectToDb();
        //showTableData();
        groupButton();
        currentDate();
        required( );
    }

    
    public void currentDate(){
        
        
        Thread clock = new Thread(){
            public void run(){
                for(;;){
                    Calendar cal = new GregorianCalendar();
                    int month = cal.get(Calendar.MONTH);
                    int year = cal.get(Calendar.YEAR);
                    int day = cal.get(Calendar.DAY_OF_MONTH);
                    mnu_date.setText("Date "+year+"/"+(month+1)+"/"+day);
        
        
                    int second = cal.get(Calendar.SECOND);
                    int mins = cal.get(Calendar.MINUTE);
                    int hrs = cal.get(Calendar.HOUR);
                    mnu_time.setText("Time "+hrs+":"+(mins)+":"+second);
                    
                    
                    try {
                        sleep(1000);
                    } 
                    catch (InterruptedException ex) {
                        Logger.getLogger(Student_IUDSV_AdminTask.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
            }
            
            
            
        };
        clock.start();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_stu_fname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_stu_address = new javax.swing.JTextField();
        female = new javax.swing.JRadioButton();
        txt_stu_email = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txt_sid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_stu_nic = new javax.swing.JTextField();
        txt_stu_phone = new javax.swing.JTextField();
        jDateChooser_dob = new com.toedter.calendar.JDateChooser();
        txt_parent_phone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_parent_nic = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_stu_lname = new javax.swing.JTextField();
        lbl_gender = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        radioclear = new javax.swing.JRadioButton();
        req = new javax.swing.JLabel();
        req1 = new javax.swing.JLabel();
        req2 = new javax.swing.JLabel();
        req3 = new javax.swing.JLabel();
        req4 = new javax.swing.JLabel();
        req5 = new javax.swing.JLabel();
        req6 = new javax.swing.JLabel();
        req7 = new javax.swing.JLabel();
        req8 = new javax.swing.JLabel();
        req9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt_stu_pw = new javax.swing.JPasswordField();
        lbl_uname = new javax.swing.JLabel();
        comboprog = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        lbl_pw = new javax.swing.JLabel();
        lbl_prog = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        combo_sem = new javax.swing.JComboBox<>();
        txt_stu_username = new javax.swing.JTextField();
        jDateChooser_enrolldate = new com.toedter.calendar.JDateChooser();
        req10 = new javax.swing.JLabel();
        req11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lbl_photo = new javax.swing.JLabel();
        stu_pathimg = new javax.swing.JTextField();
        btn_stu_attachphoto = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btn_insert = new javax.swing.JButton();
        btn_view = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_search = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnu_date = new javax.swing.JMenu();
        mnu_time = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Information System", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(204, 0, 204))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(204, 0, 204))); // NOI18N

        txt_stu_fname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_stu_fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_stu_fnameKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Parent NIC");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Email");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("First Name");

        txt_stu_address.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_stu_address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_stu_addressKeyTyped(evt);
            }
        });

        female.setBackground(new java.awt.Color(102, 255, 255));
        female.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });

        txt_stu_email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        male.setBackground(new java.awt.Color(102, 255, 255));
        male.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Last Name");

        txt_sid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_sid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_sidKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("NIC");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Student_ID");

        txt_stu_nic.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_stu_nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stu_nicActionPerformed(evt);
            }
        });
        txt_stu_nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_stu_nicKeyTyped(evt);
            }
        });

        txt_stu_phone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_stu_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_stu_phoneKeyTyped(evt);
            }
        });

        jDateChooser_dob.setBackground(new java.awt.Color(255, 255, 204));
        jDateChooser_dob.setDateFormatString("yyyy-MM-dd");

        txt_parent_phone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_parent_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_parent_phoneKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Date of Birth");

        txt_parent_nic.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Phone Number");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Postal Address");

        txt_stu_lname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_stu_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stu_lnameActionPerformed(evt);
            }
        });
        txt_stu_lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_stu_lnameKeyTyped(evt);
            }
        });

        lbl_gender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_gender.setText("Gender");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Parent's Phone No");

        radioclear.setBackground(new java.awt.Color(102, 255, 255));
        radioclear.setForeground(new java.awt.Color(255, 204, 102));

        req.setForeground(new java.awt.Color(255, 0, 0));
        req.setText("*");

        req1.setForeground(new java.awt.Color(255, 0, 0));
        req1.setText("*");

        req2.setForeground(new java.awt.Color(255, 0, 0));
        req2.setText("*");

        req3.setForeground(new java.awt.Color(255, 0, 0));
        req3.setText("*");

        req4.setForeground(new java.awt.Color(255, 0, 0));
        req4.setText("*");

        req5.setForeground(new java.awt.Color(255, 0, 0));
        req5.setText("*");

        req6.setForeground(new java.awt.Color(255, 0, 0));
        req6.setText("*");

        req7.setForeground(new java.awt.Color(255, 0, 0));
        req7.setText("*");

        req8.setForeground(new java.awt.Color(255, 0, 0));
        req8.setText("*");

        req9.setForeground(new java.awt.Color(255, 0, 0));
        req9.setText("*");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_gender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(req, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(req1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(req2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(req3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(req4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(req6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(req8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(req9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(req7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(req5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_stu_lname)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(female)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(male)
                        .addGap(27, 27, 27)
                        .addComponent(radioclear))
                    .addComponent(txt_stu_email)
                    .addComponent(txt_stu_fname)
                    .addComponent(txt_stu_nic)
                    .addComponent(txt_sid)
                    .addComponent(jDateChooser_dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_stu_phone)
                    .addComponent(txt_parent_nic)
                    .addComponent(txt_parent_phone)
                    .addComponent(txt_stu_address, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(req, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_sid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_stu_nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(req1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_stu_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(req2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_stu_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(req3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lbl_gender)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioclear, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 5, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(male)
                                            .addComponent(female)))
                                    .addComponent(req5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txt_stu_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(req4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_stu_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txt_stu_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(req7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(req6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txt_parent_nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel11))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(req9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_parent_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(req8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        jPanel3.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(204, 0, 204))); // NOI18N

        txt_stu_pw.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lbl_uname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_uname.setText("Username");

        comboprog.setBackground(new java.awt.Color(255, 255, 204));
        comboprog.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comboprog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<--Select Degree Program-->", "Information Technology ", "Computer Systems and Network Engineering ", "Information Systems Engineering ", "Software Engineering ", "Interactive Media", "Cyber Security", "Human Capital Management", "Accounting and Finance", "Marketing Management", "Logistics and Supply Chain Management", "Business Analytics", "Civil Engineering", "Electrical & Electronic Engineering", "Materials Engineering", "Mechanical Engineering", " " }));
        comboprog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboprogActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Current Semester");

        lbl_pw.setBackground(new java.awt.Color(102, 255, 255));
        lbl_pw.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_pw.setText("Password");

        lbl_prog.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_prog.setText("Program");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Enroll Date");

        combo_sem.setBackground(new java.awt.Color(255, 255, 204));
        combo_sem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        combo_sem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<--Select Current Semester-->", "Year 1 Semester 1", "Year 1 Semester 2", "Year 2 Semester 1", "Year 2 Semester 2", "Year 3 Semester 1", "Year 3 Semester 2", "Year 4 Semester 1", "Year 4 Semester 2" }));

        txt_stu_username.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jDateChooser_enrolldate.setDateFormatString("yyyy-MM-dd");

        req10.setForeground(new java.awt.Color(255, 0, 0));
        req10.setText("*");

        req11.setForeground(new java.awt.Color(255, 0, 0));
        req11.setText("*");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_pw, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(req11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_uname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_prog, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(req10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_stu_pw)
                    .addComponent(jDateChooser_enrolldate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboprog, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo_sem, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_stu_username))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(req11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_prog)
                            .addComponent(comboprog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jDateChooser_enrolldate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(combo_sem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_uname)
                                .addComponent(txt_stu_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(req10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_pw)
                            .addComponent(txt_stu_pw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(102, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Profile Picture", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(204, 0, 204))); // NOI18N

        jDesktopPane1.setLayer(lbl_photo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_photo, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_photo, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addContainerGap())
        );

        stu_pathimg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btn_stu_attachphoto.setBackground(new java.awt.Color(204, 204, 204));
        btn_stu_attachphoto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_stu_attachphoto.setForeground(new java.awt.Color(204, 0, 204));
        btn_stu_attachphoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/attach.png"))); // NOI18N
        btn_stu_attachphoto.setText("Attach Photo");
        btn_stu_attachphoto.setIconTextGap(2);
        btn_stu_attachphoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stu_attachphotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_stu_attachphoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(stu_pathimg, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_stu_attachphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stu_pathimg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(102, 255, 255));

        btn_insert.setBackground(new java.awt.Color(204, 204, 204));
        btn_insert.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_insert.setForeground(new java.awt.Color(204, 0, 204));
        btn_insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/insert.png"))); // NOI18N
        btn_insert.setText("INSERT");
        btn_insert.setIconTextGap(14);
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });

        btn_view.setBackground(new java.awt.Color(204, 204, 204));
        btn_view.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_view.setForeground(new java.awt.Color(204, 0, 204));
        btn_view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/viewall.png"))); // NOI18N
        btn_view.setText("VIEW");
        btn_view.setIconTextGap(14);
        btn_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewActionPerformed(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(204, 204, 204));
        btn_update.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_update.setForeground(new java.awt.Color(204, 0, 204));
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update.png"))); // NOI18N
        btn_update.setText("UPDATE");
        btn_update.setIconTextGap(14);
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(204, 204, 204));
        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(204, 0, 204));
        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clear.png"))); // NOI18N
        btn_clear.setText("CLEAR");
        btn_clear.setIconTextGap(14);
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(204, 204, 204));
        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(204, 0, 204));
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        btn_delete.setText("DELETE");
        btn_delete.setIconTextGap(14);
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_search.setBackground(new java.awt.Color(204, 204, 204));
        btn_search.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_search.setForeground(new java.awt.Color(204, 0, 204));
        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/find.png"))); // NOI18N
        btn_search.setText("SEARCH");
        btn_search.setIconTextGap(14);
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_insert)
                .addGap(26, 26, 26)
                .addComponent(btn_update)
                .addGap(41, 41, 41)
                .addComponent(btn_delete)
                .addGap(36, 36, 36)
                .addComponent(btn_search)
                .addGap(44, 44, 44)
                .addComponent(btn_view)
                .addGap(40, 40, 40)
                .addComponent(btn_clear)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_insert)
                    .addComponent(btn_update)
                    .addComponent(btn_delete)
                    .addComponent(btn_view)
                    .addComponent(btn_clear)
                    .addComponent(btn_search))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu3.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Home");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);
        jMenu3.add(jSeparator1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Close Window");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("About");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("About this System");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar2.add(jMenu4);

        mnu_date.setText("Date");
        jMenuBar2.add(mnu_date);

        mnu_time.setText("Time");
        jMenuBar2.add(mnu_time);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_stu_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stu_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stu_lnameActionPerformed

    private void txt_stu_nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stu_nicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stu_nicActionPerformed

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
        
        
        int confirminsert = JOptionPane.showConfirmDialog(null, "Do you really want to insert this record ?","Insert",JOptionPane.YES_NO_OPTION);
        
        if(confirminsert==0){
            if(isEmpty()&&validnic()&&validphone()&&validemail()&&validpnic()&&validpphone()){
               
                
               
        
        try{
            
        
            String sql = "INSERT INTO student"
            + "(nic,stu_fname,stu_lname,gender,dob,stu_email,stu_phone,stu_address,parent_nic,parent_contact_no,program,enroll_date,cur_sem,stu_username,stu_password,profile_pic) "
            + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        
        //conn = DriverManager.getConnection("jdbc:mysql://localhost/iuds","root","");
        
        pst = conn.prepareStatement(sql);
        
        pst.setString(1,txt_stu_nic.getText());
        pst.setString(2,txt_stu_fname.getText());
        pst.setString(3,txt_stu_lname.getText());
        if(female.isSelected()){
            gender="Female";
        }
        if(male.isSelected()){
            gender="Male";
        }
        pst.setString(4, gender);
        pst.setString(5,((JTextField)jDateChooser_dob.getDateEditor().getUiComponent()).getText());
        pst.setString(6,txt_stu_email.getText());
        pst.setString(7,txt_stu_phone.getText());
        pst.setString(8,txt_stu_address.getText());
        pst.setString(9,txt_parent_nic.getText());
        pst.setString(10,txt_parent_phone.getText());
        String value=comboprog.getSelectedItem().toString();
        pst.setString(11, value);
        pst.setString(12,((JTextField)jDateChooser_enrolldate.getDateEditor().getUiComponent()).getText());
        String value2=combo_sem.getSelectedItem().toString();
        pst.setString(13, value2);
        pst.setString(14,txt_stu_username.getText());
        pst.setString(15,txt_stu_pw.getText());
        pst.setBytes(16,profile_pic);
        
        
        
        
        
        
        
       
        pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record Inserted Successfully !");
        }
            
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }

        
        //showTableData();
    }
            
        }
    }//GEN-LAST:event_btn_insertActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        
        int confirmdelete = JOptionPane.showConfirmDialog(null, "Do you really want to delete this record ?","Delete",JOptionPane.YES_NO_OPTION);
        
        if(confirmdelete==0){
            
        
        
        try{
            String sql = "DELETE FROM student WHERE sid=?";
        
        //conn = DriverManager.getConnection("jdbc:mysql://localhost/iuds","root","");
        
        pst = conn.prepareStatement(sql);
        
        pst.setString(1,txt_sid.getText());
        
        pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record Deleted Successfully !");
        }
        
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        
        //showTableData();
    }
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        
        int confirmupdate = JOptionPane.showConfirmDialog(null, "Do you really want to update this record ?","Update",JOptionPane.YES_NO_OPTION);
        
        if(confirmupdate==0){
        if(isEmpty()&&validnic()&&validphone()&&validemail()&&validpnic()&&validpphone()){
            if(!txt_sid.getText().isEmpty()){
            
        
        try{
            String sql = "UPDATE student SET nic=?,stu_fname=?, stu_lname=?,gender=?,dob=?,stu_email=?,stu_phone=?,stu_address=?,parent_nic=?,parent_contact_no=?,program=?,enroll_date=?,cur_sem=?,stu_username=?,stu_password=?,profile_pic=? WHERE sid=?";
        
        //conn = DriverManager.getConnection("jdbc:mysql://localhost/iuds","root","");
        
        pst = conn.prepareStatement(sql);
        
        pst.setString(17,txt_sid.getText());
        
        pst.setString(1,txt_stu_nic.getText());
        pst.setString(2,txt_stu_fname.getText());
        pst.setString(3,txt_stu_lname.getText());
        if(female.isSelected()){
            gender="Female";
        }
        if(male.isSelected()){
            gender="Male";
        }
        pst.setString(4, gender);
        pst.setString(5,((JTextField)jDateChooser_dob.getDateEditor().getUiComponent()).getText());
        pst.setString(6,txt_stu_email.getText());
        pst.setString(7,txt_stu_phone.getText());
        pst.setString(8,txt_stu_address.getText());
        pst.setString(9,txt_parent_nic.getText());
        pst.setString(10,txt_parent_phone.getText());
        String value=comboprog.getSelectedItem().toString();
        pst.setString(11, value);
        pst.setString(12,((JTextField)jDateChooser_enrolldate.getDateEditor().getUiComponent()).getText());
        String value2=combo_sem.getSelectedItem().toString();
        pst.setString(13, value2);
        pst.setString(14,txt_stu_username.getText());
        pst.setString(15,txt_stu_pw.getText());
        pst.setBytes(16,profile_pic);
        
        
       
        
        
        
        
        
        
        pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record Updated Successfully !");
        }
        
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
       
        //showTableData();
    }
        }
        }
            }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        
        txt_sid.setText(" ");
        txt_stu_nic.setText(" ");
        txt_stu_fname.setText(" ");
        txt_stu_lname.setText(" ");
        radioclear.setSelected(true);
        jDateChooser_dob.setCalendar(null);
        txt_stu_email.setText(" ");
        txt_stu_phone.setText(" ");
        txt_stu_address.setText(" ");
        txt_parent_nic.setText(" ");
        txt_parent_phone.setText(" ");
        comboprog.setSelectedIndex(0);
        jDateChooser_enrolldate.setCalendar(null);
        combo_sem.setSelectedIndex(0);
        txt_stu_username.setText(" ");
        txt_stu_pw.setText(null);
        lbl_photo.setIcon(null);
        stu_pathimg.setText(" ");
        
        
            }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_stu_attachphotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stu_attachphotoActionPerformed
      
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        stu_pathimg.setText(filename);
        
        
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_photo.getWidth(), lbl_photo.getHeight(), Image.SCALE_DEFAULT));
        lbl_photo.setIcon(imageIcon);
        
        
        try{
           
           File image = new File(filename); 
           FileInputStream fis = new FileInputStream(image);
           ByteArrayOutputStream bos = new ByteArrayOutputStream();
           byte[] buff = new byte[1024];
           
           
           for(int readNum;(readNum=fis.read(buff))!=-1;){
               bos.write(buff,0,readNum);
               
           }
           profile_pic=bos.toByteArray();

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
        


    }//GEN-LAST:event_btn_stu_attachphotoActionPerformed

    private void comboprogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboprogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboprogActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed

    }//GEN-LAST:event_femaleActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
            }//GEN-LAST:event_maleActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
            
        System.exit(0);


    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btn_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewActionPerformed
            
        StudentRecords_ViewAll_AdminTask viewall =new StudentRecords_ViewAll_AdminTask();
        viewall.setVisible(true);
        
        

    }//GEN-LAST:event_btn_viewActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed

        StudentRecords_SearchRecords_AdminTask searchrecords =new StudentRecords_SearchRecords_AdminTask();
        searchrecords.setVisible(true);


    }//GEN-LAST:event_btn_searchActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

           dispose();
           new Home().setVisible(true);


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed

        dispose();

    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void txt_stu_phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_stu_phoneKeyTyped
        
        
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
            
        }     
        
        
        
        
        
    }//GEN-LAST:event_txt_stu_phoneKeyTyped

    private void txt_parent_phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_parent_phoneKeyTyped
       
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
            
        }    
        
        
        
    }//GEN-LAST:event_txt_parent_phoneKeyTyped

    private void txt_sidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sidKeyTyped

        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
            
        }    


    }//GEN-LAST:event_txt_sidKeyTyped

    private void txt_stu_addressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_stu_addressKeyTyped

        

    }//GEN-LAST:event_txt_stu_addressKeyTyped

    private void txt_stu_nicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_stu_nicKeyTyped

        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(Character.isAlphabetic(c))||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
            
        }    

    }//GEN-LAST:event_txt_stu_nicKeyTyped

    private void txt_stu_fnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_stu_fnameKeyTyped

        char c = evt.getKeyChar();
        if(!((Character.isAlphabetic(c))||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
            
        }    

    }//GEN-LAST:event_txt_stu_fnameKeyTyped

    private void txt_stu_lnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_stu_lnameKeyTyped

        char c = evt.getKeyChar();
        if(!((Character.isAlphabetic(c))||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
            
        }    

    }//GEN-LAST:event_txt_stu_lnameKeyTyped

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       
        new ABOUT().setVisible(true); 
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /*
     public void showTableData(){
         try{
            //conn = DriverManager.getConnection("jdbc:mysql://localhost/iuds","root","");
            
            String sql = "SELECT * FROM iudstbl";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            
            jTable_stu.setModel(DbUtils.resultSetToTableModel(rs));
         }
         catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);

         }
            
        }
    */
    
    
     private void groupButton( ) {

        ButtonGroup bg1 = new ButtonGroup( );

        bg1.add(female);
        bg1.add(male);
        bg1.add(radioclear);
        radioclear.setVisible(false);
        

        }
     
     
     private void required( ) {
        req.setVisible(false);
        req1.setVisible(false);
        req2.setVisible(false);
        req3.setVisible(false);
        req4.setVisible(false);
        req5.setVisible(false);
        req6.setVisible(false);
        req7.setVisible(false);
        req8.setVisible(false);
        req9.setVisible(false);
        req10.setVisible(false);
        req11.setVisible(false);
        
     }
     
     
     
      public boolean validnic(){
        
        String nic = "^[0-9]{9}V$";
        
        Pattern patternnic = Pattern.compile(nic,Pattern.CASE_INSENSITIVE);
        
        Matcher regeMatchernic = patternnic.matcher(txt_stu_nic.getText());
        if(!regeMatchernic.matches()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Enter a valid NIC !");
            return false;
        }
        else 
            return true;
      }
        
      public boolean validpnic(){
        String pnic = "^[0-9]{9}V$";
        
        Pattern patternpnic = Pattern.compile(pnic,Pattern.CASE_INSENSITIVE);
        
        Matcher regeMatcherpnic = patternpnic.matcher(txt_parent_nic.getText());
        if(!regeMatcherpnic.matches()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Enter a valid NIC !");
            return false;
        }
        else
            return true;
      }
            
        
        public boolean validemail(){
        //String emailPattern = "^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,3}$";
        
        String emailPattern = "^[A-Z0-9]+@[A-Z0-9]+\\.[A-Z]{2,3}$";
        
        Pattern patternemail = Pattern.compile(emailPattern, Pattern.CASE_INSENSITIVE);
        
        Matcher regeMatcheremail = patternemail.matcher(txt_stu_email.getText());
        if(!regeMatcheremail.matches()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Enter a valid email address !");
            return false;
        }
        else
            return true;
        }
        
        public boolean validphone(){
        String phonecount = "^[0-9]{10}$";
        
        Pattern patternphone = Pattern.compile(phonecount, Pattern.CASE_INSENSITIVE);
        
        Matcher regeMatcherphone = patternphone.matcher(txt_stu_phone.getText());
        if(!regeMatcherphone.matches()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Enter a valid phone number !");
            return false;
        }
        else
            return true;
        }
        
        
        public boolean validpphone(){
        String pphonecount = "^[0-9]{10}$";
        
        Pattern patternpphone = Pattern.compile(pphonecount, Pattern.CASE_INSENSITIVE);
        
        Matcher regeMatcherpphone = patternpphone.matcher(txt_parent_phone.getText());
        if(!regeMatcherpphone.matches()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Enter a valid phone number !");
            return false;
        }
        else
            return true;
        }
        
        
        
       
        
        

        

        
        

        public boolean isEmpty(){
            
        
        if(txt_stu_nic.getText().isEmpty())
            req1.setVisible(true);
        else
            req1.setVisible(false);
        if(txt_stu_fname.getText().isEmpty())
            req2.setVisible(true);
        else
            req2.setVisible(false);
        if(txt_stu_lname.getText().isEmpty())
            req3.setVisible(true);
        else
            req3.setVisible(false);
        if(txt_stu_email.getText().isEmpty())
            req4.setVisible(true);
        else
            req4.setVisible(false);
        if(txt_stu_email.getText().isEmpty())
            req5.setVisible(true);
        else
            req5.setVisible(false);
        if(txt_stu_phone.getText().isEmpty())
            req6.setVisible(true);
        else
            req6.setVisible(false);
        if(txt_stu_address.getText().isEmpty())
            req7.setVisible(true);
        else
            req7.setVisible(false);
        if(txt_parent_nic.getText().isEmpty())
            req8.setVisible(true);
        else
            req8.setVisible(false);
        if(txt_parent_phone.getText().isEmpty())
            req9.setVisible(true);
        else
            req9.setVisible(false);
        if(txt_stu_username.getText().isEmpty())
            req10.setVisible(true);
        else
            req10.setVisible(false);
        if(txt_stu_pw.getText().isEmpty())
            req11.setVisible(true);
        else
            req11.setVisible(false);
        
        if(!txt_stu_nic.getText().isEmpty()&&!txt_stu_fname.getText().isEmpty()&&!txt_stu_lname.getText().isEmpty()&&!txt_stu_email.getText().isEmpty()&&!txt_stu_email.getText().isEmpty()&&!txt_stu_phone.getText().isEmpty()&&!txt_stu_address.getText().isEmpty()&&!txt_parent_nic.getText().isEmpty()&&!txt_parent_phone.getText().isEmpty()&&!txt_stu_username.getText().isEmpty()&&!txt_stu_pw.getText().isEmpty())
            return true;
        else
        {
            JOptionPane.showMessageDialog(null, "Please Enter all the Values!");
            return false;
        }
       
        }
     
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_IUDSV_AdminTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_IUDSV_AdminTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_IUDSV_AdminTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_IUDSV_AdminTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_IUDSV_AdminTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_stu_attachphoto;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btn_view;
    private javax.swing.JComboBox<String> combo_sem;
    private javax.swing.JComboBox<String> comboprog;
    private javax.swing.JRadioButton female;
    private com.toedter.calendar.JDateChooser jDateChooser_dob;
    private com.toedter.calendar.JDateChooser jDateChooser_enrolldate;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lbl_gender;
    private javax.swing.JLabel lbl_photo;
    private javax.swing.JLabel lbl_prog;
    private javax.swing.JLabel lbl_pw;
    private javax.swing.JLabel lbl_uname;
    private javax.swing.JRadioButton male;
    private javax.swing.JMenu mnu_date;
    private javax.swing.JMenu mnu_time;
    private javax.swing.JRadioButton radioclear;
    private javax.swing.JLabel req;
    private javax.swing.JLabel req1;
    private javax.swing.JLabel req10;
    private javax.swing.JLabel req11;
    private javax.swing.JLabel req2;
    private javax.swing.JLabel req3;
    private javax.swing.JLabel req4;
    private javax.swing.JLabel req5;
    private javax.swing.JLabel req6;
    private javax.swing.JLabel req7;
    private javax.swing.JLabel req8;
    private javax.swing.JLabel req9;
    private javax.swing.JTextField stu_pathimg;
    private javax.swing.JTextField txt_parent_nic;
    private javax.swing.JTextField txt_parent_phone;
    private javax.swing.JTextField txt_sid;
    private javax.swing.JTextField txt_stu_address;
    private javax.swing.JTextField txt_stu_email;
    private javax.swing.JTextField txt_stu_fname;
    private javax.swing.JTextField txt_stu_lname;
    private javax.swing.JTextField txt_stu_nic;
    private javax.swing.JTextField txt_stu_phone;
    private javax.swing.JPasswordField txt_stu_pw;
    private javax.swing.JTextField txt_stu_username;
    // End of variables declaration//GEN-END:variables

    private ImageIcon format = null;
    String filename =null;
    int s = 0;
    byte[] profile_pic=null;
    private String gender;
   
}
