/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iuds;
//DISPLAY TO LOGGED IN ADMIN TO EDIT RECORDS
import com.sun.glass.events.KeyEvent;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import java.util.regex.MatchResult.*;
import java.util.regex.Matcher;









/**
 *
 * @author Himashi
 */

public class StudentRecords_SearchRecords_AdminTask extends javax.swing.JFrame {
    
    
    Connection conn =null;
    PreparedStatement pst = null;
    ResultSet rs=null;
    

    /**
     * Creates new form NewJFrame
     */
    public StudentRecords_SearchRecords_AdminTask() {
        
        initComponents();
        conn = dbConnect.connectToDb();
        //showTableData();
        groupButton();
        currentDate();
        //required( );
    }

    
    public void currentDate(){
        
        
        Thread clock = new Thread(){
            public void run(){
                for(;;){
                    Calendar cal = new GregorianCalendar();
                    int month = cal.get(Calendar.MONTH);
                    int year = cal.get(Calendar.YEAR);
                    int day = cal.get(Calendar.DAY_OF_MONTH);
                    mnu_date.setText("Date "+year+"/"+(month+1)+"/"+day);
        
        
                    int second = cal.get(Calendar.SECOND);
                    int mins = cal.get(Calendar.MINUTE);
                    int hrs = cal.get(Calendar.HOUR);
                    mnu_time.setText("Time "+hrs+":"+(mins)+":"+second);
                    
                    
                    try {
                        sleep(1000);
                    } 
                    catch (InterruptedException ex) {
                        Logger.getLogger(StudentRecords_SearchRecords_AdminTask.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
            }
            
            
            
        };
        clock.start();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_stu_fname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_stu_address = new javax.swing.JTextField();
        txt_stu_email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_sid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_stu_nic = new javax.swing.JTextField();
        txt_stu_phone = new javax.swing.JTextField();
        txt_parent_phone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_parent_nic = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_stu_lname = new javax.swing.JTextField();
        lbl_gender = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_stu_gender = new javax.swing.JTextField();
        txt_stu_dob = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lbl_prog = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_stu_prog = new javax.swing.JTextField();
        txt_stu_asem = new javax.swing.JTextField();
        txt_stu_edate = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lbl_photo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_stu_search = new javax.swing.JTextField();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnu_date = new javax.swing.JMenu();
        mnu_time = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Information System", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(204, 0, 204))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(204, 0, 204))); // NOI18N

        txt_stu_fname.setEditable(false);
        txt_stu_fname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_stu_fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_stu_fnameKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Parent NIC");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Email");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("First Name");

        txt_stu_address.setEditable(false);
        txt_stu_address.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_stu_address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_stu_addressKeyTyped(evt);
            }
        });

        txt_stu_email.setEditable(false);
        txt_stu_email.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Last Name");

        txt_sid.setEditable(false);
        txt_sid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_sid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_sidKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("NIC");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Student_ID");

        txt_stu_nic.setEditable(false);
        txt_stu_nic.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_stu_nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stu_nicActionPerformed(evt);
            }
        });
        txt_stu_nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_stu_nicKeyTyped(evt);
            }
        });

        txt_stu_phone.setEditable(false);
        txt_stu_phone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_stu_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_stu_phoneKeyTyped(evt);
            }
        });

        txt_parent_phone.setEditable(false);
        txt_parent_phone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_parent_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_parent_phoneKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Date of Birth");

        txt_parent_nic.setEditable(false);
        txt_parent_nic.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_parent_nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_parent_nicActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Phone Number");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Postal Address");

        txt_stu_lname.setEditable(false);
        txt_stu_lname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_stu_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stu_lnameActionPerformed(evt);
            }
        });
        txt_stu_lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_stu_lnameKeyTyped(evt);
            }
        });

        lbl_gender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_gender.setText("Gender");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Parent's Phone No");

        txt_stu_gender.setEditable(false);
        txt_stu_gender.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_stu_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stu_genderActionPerformed(evt);
            }
        });
        txt_stu_gender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_stu_genderKeyTyped(evt);
            }
        });

        txt_stu_dob.setEditable(false);
        txt_stu_dob.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_stu_dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stu_dobActionPerformed(evt);
            }
        });
        txt_stu_dob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_stu_dobKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_gender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_stu_lname)
                    .addComponent(txt_stu_email)
                    .addComponent(txt_stu_fname)
                    .addComponent(txt_stu_nic)
                    .addComponent(txt_sid)
                    .addComponent(txt_stu_phone)
                    .addComponent(txt_parent_nic)
                    .addComponent(txt_parent_phone)
                    .addComponent(txt_stu_address, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(txt_stu_gender)
                    .addComponent(txt_stu_dob))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_sid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_stu_nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_stu_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_stu_lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_gender)
                    .addComponent(txt_stu_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_stu_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_stu_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_stu_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txt_stu_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel10)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(txt_parent_nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_parent_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );

        jPanel3.setBackground(new java.awt.Color(102, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(204, 0, 204))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Current Semester");

        lbl_prog.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_prog.setText("Program");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Enroll Date");

        txt_stu_prog.setEditable(false);
        txt_stu_prog.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_stu_prog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stu_progActionPerformed(evt);
            }
        });
        txt_stu_prog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_stu_progKeyTyped(evt);
            }
        });

        txt_stu_asem.setEditable(false);
        txt_stu_asem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_stu_asem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stu_asemActionPerformed(evt);
            }
        });
        txt_stu_asem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_stu_asemKeyTyped(evt);
            }
        });

        txt_stu_edate.setEditable(false);
        txt_stu_edate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_stu_edate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stu_edateActionPerformed(evt);
            }
        });
        txt_stu_edate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_stu_edateKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_prog, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_stu_prog, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(txt_stu_asem, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_stu_edate, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_prog)
                    .addComponent(txt_stu_prog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(5, 5, 5))
                    .addComponent(txt_stu_edate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel14))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_stu_asem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82))
        );

        jPanel4.setBackground(new java.awt.Color(102, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Profile Picture", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(204, 0, 204))); // NOI18N

        jDesktopPane1.setLayer(lbl_photo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_photo, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_photo, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addGap(70, 70, 70))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Type StudentID to search Student Record");

        txt_stu_search.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_stu_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_stu_searchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_stu_search, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_stu_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );

        jMenu3.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Home");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);
        jMenu3.add(jSeparator1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Close Window");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("About");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("About this System");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar2.add(jMenu4);

        mnu_date.setText("Date");
        jMenuBar2.add(mnu_date);

        mnu_time.setText("Time");
        jMenuBar2.add(mnu_time);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_stu_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stu_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stu_lnameActionPerformed

    private void txt_stu_nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stu_nicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stu_nicActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
            
        System.exit(0);


    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

           dispose();
           new Home().setVisible(true);


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed

        dispose();

    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void txt_stu_phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_stu_phoneKeyTyped
        
        
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
            
        }     
        
        
        
        
        
    }//GEN-LAST:event_txt_stu_phoneKeyTyped

    private void txt_parent_phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_parent_phoneKeyTyped
       
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
            
        }    
        
        
        
    }//GEN-LAST:event_txt_parent_phoneKeyTyped

    private void txt_sidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sidKeyTyped

        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
            
        }    


    }//GEN-LAST:event_txt_sidKeyTyped

    private void txt_stu_addressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_stu_addressKeyTyped

        

    }//GEN-LAST:event_txt_stu_addressKeyTyped

    private void txt_stu_nicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_stu_nicKeyTyped

        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(Character.isAlphabetic(c))||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
            
        }    

    }//GEN-LAST:event_txt_stu_nicKeyTyped

    private void txt_stu_fnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_stu_fnameKeyTyped

        char c = evt.getKeyChar();
        if(!((Character.isAlphabetic(c))||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
            
        }    

    }//GEN-LAST:event_txt_stu_fnameKeyTyped

    private void txt_stu_lnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_stu_lnameKeyTyped

        char c = evt.getKeyChar();
        if(!((Character.isAlphabetic(c))||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
            
        }    

    }//GEN-LAST:event_txt_stu_lnameKeyTyped

    private void txt_stu_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stu_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stu_genderActionPerformed

    private void txt_stu_genderKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_stu_genderKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stu_genderKeyTyped

    private void txt_stu_dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stu_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stu_dobActionPerformed

    private void txt_stu_dobKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_stu_dobKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stu_dobKeyTyped

    private void txt_stu_progActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stu_progActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stu_progActionPerformed

    private void txt_stu_progKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_stu_progKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stu_progKeyTyped

    private void txt_stu_asemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stu_asemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stu_asemActionPerformed

    private void txt_stu_asemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_stu_asemKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stu_asemKeyTyped

    private void txt_parent_nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_parent_nicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_parent_nicActionPerformed

    private void txt_stu_edateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stu_edateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stu_edateActionPerformed

    private void txt_stu_edateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_stu_edateKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stu_edateKeyTyped

    private void txt_stu_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_stu_searchKeyReleased

        

        try{
            String sql="SELECT * FROM student WHERE sid=?";

            pst=conn.prepareStatement(sql);
            pst.setString(1,txt_stu_search.getText());
            rs=pst.executeQuery();
            
            if(rs.next()){
                String a1 = rs.getString("sid");
                txt_sid.setText(a1);
                String a2 = rs.getString("nic");
                txt_stu_nic.setText(a2);
                String a3 = rs.getString("stu_fname");
                txt_stu_fname.setText(a3);
                String a4 = rs.getString("stu_lname");
                txt_stu_lname.setText(a4);
                String a5 = rs.getString("gender");
                txt_stu_gender.setText(a5);
                String a6 = rs.getString("dob");
                txt_stu_dob.setText(a6);
                String a7 = rs.getString("stu_email");
                txt_stu_email.setText(a7);
                String a8 = rs.getString("stu_phone");
                txt_stu_phone.setText(a8);
                String a9 = rs.getString("stu_address");
                txt_stu_address.setText(a9);
                String a10 = rs.getString("parent_nic");
                txt_parent_nic.setText(a10);
                String a11 = rs.getString("parent_contact_no");
                txt_parent_phone.setText(a11);
                String a12 = rs.getString("program");
                txt_stu_prog.setText(a12);
                String a13 = rs.getString("enroll_date");
                txt_stu_edate.setText(a13);
                String a14 = rs.getString("cur_sem");
                txt_stu_asem.setText(a14);
                
                
                
            byte[]imagedata=rs.getBytes("profile_pic");
            format = new ImageIcon(new ImageIcon(imagedata).getImage().getScaledInstance(lbl_photo.getWidth(), lbl_photo.getHeight(), Image.SCALE_DEFAULT));
            lbl_photo.setIcon(format);
                
                
            }
            

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }

    }//GEN-LAST:event_txt_stu_searchKeyReleased

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       
        new ABOUT().setVisible(true); 
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /*
     public void showTableData(){
         try{
            //conn = DriverManager.getConnection("jdbc:mysql://localhost/iuds","root","");
            
            String sql = "SELECT * FROM iudstbl";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            
            jTable_stu.setModel(DbUtils.resultSetToTableModel(rs));
         }
         catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);

         }
            
        }
    */
    
    
     private void groupButton( ) {

     }
     
      public boolean validnic(){
        
        String nic = "^[0-9]{9}V$";
        
        Pattern patternnic = Pattern.compile(nic,Pattern.CASE_INSENSITIVE);
        
        Matcher regeMatchernic = patternnic.matcher(txt_stu_nic.getText());
        if(!regeMatchernic.matches()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Enter a valid NIC !");
            return false;
        }
        else 
            return true;
      }
        
      public boolean validpnic(){
        String pnic = "^[0-9]{9}V$";
        
        Pattern patternpnic = Pattern.compile(pnic,Pattern.CASE_INSENSITIVE);
        
        Matcher regeMatcherpnic = patternpnic.matcher(txt_parent_nic.getText());
        if(!regeMatcherpnic.matches()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Enter a valid NIC !");
            return false;
        }
        else
            return true;
      }
            
        
        public boolean validemail(){
        //String emailPattern = "^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,3}$";
        
        String emailPattern = "^[A-Z0-9]+@[A-Z0-9]+\\.[A-Z]{2,3}$";
        
        Pattern patternemail = Pattern.compile(emailPattern, Pattern.CASE_INSENSITIVE);
        
        Matcher regeMatcheremail = patternemail.matcher(txt_stu_email.getText());
        if(!regeMatcheremail.matches()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Enter a valid email address !");
            return false;
        }
        else
            return true;
        }
        
        public boolean validphone(){
        String phonecount = "^[0-9]{10}$";
        
        Pattern patternphone = Pattern.compile(phonecount, Pattern.CASE_INSENSITIVE);
        
        Matcher regeMatcherphone = patternphone.matcher(txt_stu_phone.getText());
        if(!regeMatcherphone.matches()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Enter a valid phone number !");
            return false;
        }
        else
            return true;
        }
        
        
        public boolean validpphone(){
        String pphonecount = "^[0-9]{10}$";
        
        Pattern patternpphone = Pattern.compile(pphonecount, Pattern.CASE_INSENSITIVE);
        
        Matcher regeMatcherpphone = patternpphone.matcher(txt_parent_phone.getText());
        if(!regeMatcherpphone.matches()){
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Enter a valid phone number !");
            return false;
        }
        else
            return true;
        }
        
        
        
       
        
        

        

        
        

        
     
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRecords_SearchRecords_AdminTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRecords_SearchRecords_AdminTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRecords_SearchRecords_AdminTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRecords_SearchRecords_AdminTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRecords_SearchRecords_AdminTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lbl_gender;
    private javax.swing.JLabel lbl_photo;
    private javax.swing.JLabel lbl_prog;
    private javax.swing.JMenu mnu_date;
    private javax.swing.JMenu mnu_time;
    private javax.swing.JTextField txt_parent_nic;
    private javax.swing.JTextField txt_parent_phone;
    private javax.swing.JTextField txt_sid;
    private javax.swing.JTextField txt_stu_address;
    private javax.swing.JTextField txt_stu_asem;
    private javax.swing.JTextField txt_stu_dob;
    private javax.swing.JTextField txt_stu_edate;
    private javax.swing.JTextField txt_stu_email;
    private javax.swing.JTextField txt_stu_fname;
    private javax.swing.JTextField txt_stu_gender;
    private javax.swing.JTextField txt_stu_lname;
    private javax.swing.JTextField txt_stu_nic;
    private javax.swing.JTextField txt_stu_phone;
    private javax.swing.JTextField txt_stu_prog;
    private javax.swing.JTextField txt_stu_search;
    // End of variables declaration//GEN-END:variables

    private ImageIcon format = null;
    String filename =null;
    int s = 0;
    byte[] profile_pic=null;
    private String gender;
   
}
