 const LOAN_STATUS=1;
const FINE_STATUS=1;
const INITIAL_AMAOUNT_STATUS=0;
const LOAN_AMOUNT=500;
const FINE_AMOUNT=600;
const INITIAL_AMOUNT=1000;

module.exports = {
    LOAN_STATUS,
    FINE_STATUS,
    INITIAL_AMAOUNT_STATUS,
    LOAN_AMOUNT,
    FINE_AMOUNT,
    INITIAL_AMOUNT
}
