/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CMS;
import DBConnection.DBConnect;
import SPMS.dbConnection;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.sql.Connection;
import java.sql.DriverManager;
/**
 *
 * @author user
 */
public class CMS_foodItems extends javax.swing.JInternalFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
//    public String driver = "com.microsoft.jdbc.SQLServerDriver";
//    public String url = "jdbcsqlserver://localhost::24809:databaseName=smsDB";
//    public String user = "adminK";
//    public String pw = "admink";
    /**
     * Creates new form foodItems
     */
    public CMS_foodItems() throws ClassNotFoundException, SQLException {
        initComponents();
        
//        Class.forName(driver);
//        conn=DriverManager.getConnection(url, user, pw);
        

        conn = DBConnect.connect();
         //Connect to DB
        
        //Load table
        tableload();
    }
    
    public void tableload() throws ClassNotFoundException{
        try {
//            Class.forName(driver);
//            conn=DriverManager.getConnection(url, user, pw);
            
            String sql = "SELECT itemId,itemName,catName,itemPrice,itemQuantity FROM cms_item ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            jTable_Item.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (SQLException e) {
            
        }
    }
    
    //Clear rows
    public void refresh()
    {
         iIDbox.setText("");
         inameBox.setText("");
         canameBox.setText("");
         ipriceBox.setText("");
         iquantityBox.setText("");
    }      
         

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelItem = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        iIDbox = new javax.swing.JTextField();
        inameBox = new javax.swing.JTextField();
        canameBox = new javax.swing.JTextField();
        ipriceBox = new javax.swing.JTextField();
        iquantityBox = new javax.swing.JTextField();
        FIinsert_btn_ = new javax.swing.JButton();
        FIupdate_btn_ = new javax.swing.JButton();
        FIdelete_btn_ = new javax.swing.JButton();
        FIsearch_btn_ = new javax.swing.JButton();
        FDview_btn_ = new javax.swing.JButton();
        FIrefresh_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Item = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(1256, 800));
        setMinimumSize(new java.awt.Dimension(1256, 800));
        setPreferredSize(new java.awt.Dimension(1256, 800));

        jPanelItem.setBackground(new java.awt.Color(153, 153, 255));
        jPanelItem.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Food Items", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 26), new java.awt.Color(153, 0, 153))); // NOI18N
        jPanelItem.setMaximumSize(new java.awt.Dimension(1256, 800));
        jPanelItem.setMinimumSize(new java.awt.Dimension(1256, 800));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Food Item Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 22), new java.awt.Color(51, 0, 153))); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(470, 420));
        jPanel2.setMinimumSize(new java.awt.Dimension(470, 420));
        jPanel2.setPreferredSize(new java.awt.Dimension(470, 420));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Item ID");
        jLabel1.setMaximumSize(new java.awt.Dimension(115, 19));
        jLabel1.setMinimumSize(new java.awt.Dimension(115, 19));
        jLabel1.setPreferredSize(new java.awt.Dimension(115, 19));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Item Name");
        jLabel2.setMaximumSize(new java.awt.Dimension(115, 19));
        jLabel2.setMinimumSize(new java.awt.Dimension(115, 19));
        jLabel2.setPreferredSize(new java.awt.Dimension(115, 19));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Category Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("Item Price");
        jLabel4.setMaximumSize(new java.awt.Dimension(115, 19));
        jLabel4.setMinimumSize(new java.awt.Dimension(115, 19));
        jLabel4.setPreferredSize(new java.awt.Dimension(115, 19));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Item Quantity");
        jLabel5.setMaximumSize(new java.awt.Dimension(115, 19));
        jLabel5.setMinimumSize(new java.awt.Dimension(115, 19));
        jLabel5.setPreferredSize(new java.awt.Dimension(115, 19));

        iIDbox.setMaximumSize(new java.awt.Dimension(6, 20));
        iIDbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iIDboxActionPerformed(evt);
            }
        });

        inameBox.setMaximumSize(new java.awt.Dimension(6, 20));

        canameBox.setMaximumSize(new java.awt.Dimension(6, 20));

        ipriceBox.setMaximumSize(new java.awt.Dimension(6, 20));
        ipriceBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipriceBoxActionPerformed(evt);
            }
        });
        ipriceBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ipriceBoxKeyTyped(evt);
            }
        });

        iquantityBox.setMaximumSize(new java.awt.Dimension(6, 20));
        iquantityBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                iquantityBoxKeyTyped(evt);
            }
        });

        FIinsert_btn_.setBackground(new java.awt.Color(0, 0, 102));
        FIinsert_btn_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FIinsert_btn_.setForeground(new java.awt.Color(255, 255, 255));
        FIinsert_btn_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_CMS/insert.png"))); // NOI18N
        FIinsert_btn_.setText("INSERT");
        FIinsert_btn_.setMaximumSize(new java.awt.Dimension(127, 40));
        FIinsert_btn_.setMinimumSize(new java.awt.Dimension(127, 40));
        FIinsert_btn_.setPreferredSize(new java.awt.Dimension(127, 40));
        FIinsert_btn_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIinsert_btn_ActionPerformed(evt);
            }
        });

        FIupdate_btn_.setBackground(new java.awt.Color(0, 0, 102));
        FIupdate_btn_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FIupdate_btn_.setForeground(new java.awt.Color(255, 255, 255));
        FIupdate_btn_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_CMS/update.png"))); // NOI18N
        FIupdate_btn_.setText("UPDATE");
        FIupdate_btn_.setMaximumSize(new java.awt.Dimension(127, 40));
        FIupdate_btn_.setMinimumSize(new java.awt.Dimension(127, 40));
        FIupdate_btn_.setPreferredSize(new java.awt.Dimension(127, 40));
        FIupdate_btn_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIupdate_btn_ActionPerformed(evt);
            }
        });

        FIdelete_btn_.setBackground(new java.awt.Color(0, 0, 102));
        FIdelete_btn_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FIdelete_btn_.setForeground(new java.awt.Color(255, 255, 255));
        FIdelete_btn_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_CMS/delete.png"))); // NOI18N
        FIdelete_btn_.setText("DELETE");
        FIdelete_btn_.setMaximumSize(new java.awt.Dimension(127, 40));
        FIdelete_btn_.setMinimumSize(new java.awt.Dimension(127, 40));
        FIdelete_btn_.setPreferredSize(new java.awt.Dimension(127, 40));
        FIdelete_btn_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIdelete_btn_ActionPerformed(evt);
            }
        });

        FIsearch_btn_.setBackground(new java.awt.Color(0, 0, 102));
        FIsearch_btn_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FIsearch_btn_.setForeground(new java.awt.Color(255, 255, 255));
        FIsearch_btn_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_CMS/find.png"))); // NOI18N
        FIsearch_btn_.setText("SEARCH");
        FIsearch_btn_.setMaximumSize(new java.awt.Dimension(127, 40));
        FIsearch_btn_.setMinimumSize(new java.awt.Dimension(127, 40));
        FIsearch_btn_.setPreferredSize(new java.awt.Dimension(127, 40));
        FIsearch_btn_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIsearch_btn_ActionPerformed(evt);
            }
        });

        FDview_btn_.setBackground(new java.awt.Color(0, 0, 102));
        FDview_btn_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FDview_btn_.setForeground(new java.awt.Color(255, 255, 255));
        FDview_btn_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_CMS/viewall.png"))); // NOI18N
        FDview_btn_.setText("VIEW");
        FDview_btn_.setMaximumSize(new java.awt.Dimension(127, 40));
        FDview_btn_.setMinimumSize(new java.awt.Dimension(127, 40));
        FDview_btn_.setPreferredSize(new java.awt.Dimension(127, 40));
        FDview_btn_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FDview_btn_ActionPerformed(evt);
            }
        });

        FIrefresh_btn.setBackground(new java.awt.Color(0, 0, 102));
        FIrefresh_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FIrefresh_btn.setForeground(new java.awt.Color(255, 255, 255));
        FIrefresh_btn.setText("Refresh");
        FIrefresh_btn.setMaximumSize(new java.awt.Dimension(127, 40));
        FIrefresh_btn.setMinimumSize(new java.awt.Dimension(127, 40));
        FIrefresh_btn.setPreferredSize(new java.awt.Dimension(127, 40));
        FIrefresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIrefresh_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ipriceBox, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(iquantityBox, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iIDbox, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(canameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FIinsert_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FIdelete_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FDview_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FIsearch_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FIupdate_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FIrefresh_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iIDbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(canameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ipriceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iquantityBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FIinsert_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FIupdate_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FIdelete_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FIsearch_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FDview_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FIrefresh_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setPreferredSize(new java.awt.Dimension(512, 474));

        jTable_Item.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ItemID", "Item Name", "Category Name", "Item Price", "Item Quantity"
            }
        ));
        jTable_Item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_ItemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Item);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout jPanelItemLayout = new javax.swing.GroupLayout(jPanelItem);
        jPanelItem.setLayout(jPanelItemLayout);
        jPanelItemLayout.setHorizontalGroup(
            jPanelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanelItemLayout.setVerticalGroup(
            jPanelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItemLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanelItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 332, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ipriceBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipriceBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipriceBoxActionPerformed

    private void iIDboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iIDboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iIDboxActionPerformed

    private void FIdelete_btn_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIdelete_btn_ActionPerformed

        
        int confirmdelete = JOptionPane.showConfirmDialog(null, "Do you really want to delete this record ?","Delete",JOptionPane.YES_NO_OPTION);
        if(confirmdelete==0){
        try{
//            Class.forName(driver);
//            conn=DriverManager.getConnection(url, user, pw);
               String sql = "DELETE FROM cms_item WHERE itemId =?";
             
               pst = conn.prepareStatement(sql);
               
               pst.setString(1,iIDbox.getText());
               
               pst.executeUpdate();
               
               //Load table
                tableload();
               
               JOptionPane.showMessageDialog(null, "Record Deleted Successfully !");
 
        }
        catch(SQLException | HeadlessException ex){
                JOptionPane.showMessageDialog(null, ex);
        }   catch (ClassNotFoundException ex) {
                Logger.getLogger(CMS_foodItems.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_FIdelete_btn_ActionPerformed

    private void FIsearch_btn_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIsearch_btn_ActionPerformed
 
        try {
            jPanelItem.removeAll();
            CMS_searchItem si = new CMS_searchItem();
            jPanelItem.add(si).setVisible(true);
            
            CMS_searchItem searchrecords =new CMS_searchItem();
            searchrecords.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CMS_foodItems.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CMS_foodItems.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_FIsearch_btn_ActionPerformed

    private void FDview_btn_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FDview_btn_ActionPerformed
       
        try {
            jPanelItem.removeAll();
            CMS_viewItems vi = new CMS_viewItems();
            jPanelItem.add(vi).setVisible(true);
            
            
            CMS_viewItems viewall = new CMS_viewItems();
            viewall.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CMS_foodItems.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CMS_foodItems.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_FDview_btn_ActionPerformed

    private void FIinsert_btn_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIinsert_btn_ActionPerformed

       
        String ItemID = iIDbox.getText();
        String ItemName = inameBox.getText();
        String CategoryName = canameBox.getText();
        String ItemPrice = ipriceBox.getText();
        String Quantity  = iquantityBox.getText();
        
        
         //check null fields
        if(ItemID.isEmpty() || ItemName.isEmpty() || CategoryName.isEmpty() || ItemPrice.isEmpty() || Quantity.isEmpty()){
            
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Complete all the input fields!!");
        }
        else{
            String pattern = iIDbox.getText().trim();
            iIDbox.setText(pattern);
            
            if ((!pattern.isEmpty()) && (!pattern.matches("[0-9][0-9][0-9][0-9]")))
                    {   
                        getToolkit().beep();
                        JOptionPane.showMessageDialog(null, "Invalid Input. Enter only 4 digits for ITEM ID!!");
                        iIDbox.setText("");
                    }
            else
                
        
        try
        {
//            Class.forName(driver);
//            conn=DriverManager.getConnection(url, user, pw);
            int confirminsert = JOptionPane.showConfirmDialog(null,"Do you really want to insert this record?","Insert",JOptionPane.YES_NO_OPTION);
            
            String sql = "INSERT INTO cms_item(itemId,itemName,catName,itemPrice,itemQuantity) VALUES ('"+ItemID+"','"+ItemName+"','"+CategoryName+"','"+ItemPrice+"','"+Quantity+"')";
        
            pst = conn.prepareStatement(sql);
            pst.execute();
            
             //Load table
            tableload();
            
            JOptionPane.showMessageDialog(null,"Record Inserted Successfully");
            
        }catch(SQLException e)
          {
            System.out.println("SQLException e");
          } catch (ClassNotFoundException ex) {
                Logger.getLogger(CMS_foodItems.class.getName()).log(Level.SEVERE, null, ex);
            }
        }    
        
    }//GEN-LAST:event_FIinsert_btn_ActionPerformed

    private void FIupdate_btn_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIupdate_btn_ActionPerformed
        
            
            int confirmupdate = JOptionPane.showConfirmDialog(null, "Do you really want to update this record ?","Update",JOptionPane.YES_NO_OPTION);
            
            if(confirmupdate==0){
         
            try {
//                Class.forName(driver);
//            conn=DriverManager.getConnection(url, user, pw);
                 String sql ="UPDATE cms_item SET itemName=?,catName=?,itemPrice=?,itemQuantity=? WHERE itemId=?";
            
                 pst = conn.prepareStatement(sql);
            
                 pst.setString(5,iIDbox.getText());
                 pst.setString(1,inameBox.getText());
                 pst.setString(2,canameBox.getText());
                 pst.setString(3,ipriceBox.getText());
                 pst.setString(4,iquantityBox.getText());
            
                pst.executeUpdate();
                
                //Load table
                 tableload();
            
                 JOptionPane.showMessageDialog(null, "Record Updated Successfully !");
            
             } catch (SQLException | HeadlessException ex) {
                      JOptionPane.showMessageDialog(null, ex);
             }  catch (ClassNotFoundException ex) {
                    Logger.getLogger(CMS_foodItems.class.getName()).log(Level.SEVERE, null, ex);
                }
            
        }
    }//GEN-LAST:event_FIupdate_btn_ActionPerformed

    private void jTable_ItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_ItemMouseClicked
     
        int r = jTable_Item.getSelectedRow();
        
        String ItemID = jTable_Item.getValueAt(r, 0).toString();
        String ItemName = jTable_Item.getValueAt(r, 1).toString();
        String CategoryName = jTable_Item.getValueAt(r, 2).toString();
        String ItemPrice = jTable_Item.getValueAt(r, 3).toString();
        String Quantity = jTable_Item.getValueAt(r, 4).toString();
        
        iIDbox.setText(ItemID);
        inameBox.setText(ItemName);
        canameBox.setText(CategoryName);
        ipriceBox.setText(ItemPrice);
        iquantityBox.setText(Quantity);
        
        
        
    }//GEN-LAST:event_jTable_ItemMouseClicked

    private void ipriceBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ipriceBoxKeyTyped
  
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)|| (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Enter NUMERIC values!!");
        
        }
    }//GEN-LAST:event_ipriceBoxKeyTyped

    private void iquantityBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iquantityBoxKeyTyped
     
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)|| (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Enter NUMERIC values!!");
        
        }
        
    }//GEN-LAST:event_iquantityBoxKeyTyped

    private void FIrefresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIrefresh_btnActionPerformed
      
        //Clear rows
        refresh();
    }//GEN-LAST:event_FIrefresh_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FDview_btn_;
    private javax.swing.JButton FIdelete_btn_;
    private javax.swing.JButton FIinsert_btn_;
    private javax.swing.JButton FIrefresh_btn;
    private javax.swing.JButton FIsearch_btn_;
    private javax.swing.JButton FIupdate_btn_;
    private javax.swing.JTextField canameBox;
    private javax.swing.JTextField iIDbox;
    private javax.swing.JTextField inameBox;
    private javax.swing.JTextField ipriceBox;
    private javax.swing.JTextField iquantityBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelItem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Item;
    // End of variables declaration//GEN-END:variables
}
