/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CMS;
import DBConnection.DBConnect;
import SPMS.dbConnection;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author user
 */
public class CMS_searchCategory extends javax.swing.JInternalFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
//    public String driver = "com.microsoft.jdbc.SQLServerDriver";
//    public String url = "jdbcsqlserver://localhost::24809:databaseName=smsDB";
//    public String user = "adminK";
//    public String pw = "admink";
    /**
     * Creates new form searchCategory
     */
    public CMS_searchCategory() throws ClassNotFoundException, SQLException {
        initComponents();
        
//        Class.forName(driver);
//conn=DriverManager.getConnection(url, user, pw);        

         conn = DBConnect.connect();
        //viewcms_category();
              viewStudentTable();

        //currentDateAndTime();
    }
    
    
     public void viewStudentTable(){
        
        try{
            
        String sql1 = "SELECT * FROM cms_category";
        pst = conn.prepareStatement(sql1);
        rs = pst.executeQuery();
        jTable_searchCategory.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        
        catch(Exception e ){
            
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    public void viewcms_category() throws ClassNotFoundException{
        
        try{
//            Class.forName(driver);
//            conn=DriverManager.getConnection(url, user, pw);
        String sql = "SELECT * FROM cms_category";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery(sql);
        jTable_searchCategory.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        catch(SQLException e ){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
   /*public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_category_searchkeyReleased = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_searchCategory = new javax.swing.JTable();
        SFC_btn_ = new javax.swing.JButton();
        jButtonSFC = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1256, 800));
        setMinimumSize(new java.awt.Dimension(1256, 800));
        setPreferredSize(new java.awt.Dimension(1256, 800));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1240, 448));
        jPanel1.setMinimumSize(new java.awt.Dimension(1240, 448));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Food Category Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20), new java.awt.Color(153, 0, 153))); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(1020, 415));
        jPanel2.setMinimumSize(new java.awt.Dimension(1020, 415));
        jPanel2.setPreferredSize(new java.awt.Dimension(1020, 415));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Type the category name to search the food category details");

        txt_category_searchkeyReleased.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_category_searchkeyReleasedActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setMaximumSize(new java.awt.Dimension(850, 310));
        jPanel3.setMinimumSize(new java.awt.Dimension(850, 310));
        jPanel3.setPreferredSize(new java.awt.Dimension(850, 310));

        jTable_searchCategory.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable_searchCategory.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable_searchCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jTable_searchCategory.setColumnSelectionAllowed(true);
        jTable_searchCategory.setMaximumSize(new java.awt.Dimension(375, 160));
        jTable_searchCategory.setMinimumSize(new java.awt.Dimension(375, 160));
        jTable_searchCategory.setPreferredSize(new java.awt.Dimension(375, 160));
        jScrollPane1.setViewportView(jTable_searchCategory);
        jTable_searchCategory.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 846, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(35, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(144, Short.MAX_VALUE)))
        );

        SFC_btn_.setBackground(new java.awt.Color(0, 51, 102));
        SFC_btn_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SFC_btn_.setForeground(new java.awt.Color(255, 255, 255));
        SFC_btn_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_CMS/backTo.png"))); // NOI18N
        SFC_btn_.setText("BACK");
        SFC_btn_.setMaximumSize(new java.awt.Dimension(110, 40));
        SFC_btn_.setMinimumSize(new java.awt.Dimension(110, 40));
        SFC_btn_.setPreferredSize(new java.awt.Dimension(110, 40));
        SFC_btn_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SFC_btn_ActionPerformed(evt);
            }
        });

        jButtonSFC.setBackground(new java.awt.Color(0, 0, 102));
        jButtonSFC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSFC.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSFC.setText("Search");
        jButtonSFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSFCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)
                        .addComponent(txt_category_searchkeyReleased, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSFC, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 19, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(SFC_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(SFC_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_category_searchkeyReleased)
                        .addComponent(jButtonSFC))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 220, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_category_searchkeyReleasedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_category_searchkeyReleasedActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel table =(DefaultTableModel)jTable_searchCategory.getModel();
        String search=txt_category_searchkeyReleased.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(table);
        jTable_searchCategory.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
        
        
        try{
//            Class.forName(driver);
//            conn=DriverManager.getConnection(url, user, pw);
            String sql="SELECT * FROM cms_category WHERE catName=?";
            
            pst=conn.prepareStatement(sql);
            pst.setString(1,txt_category_searchkeyReleased.getText());
            rs=pst.executeQuery();
            
            
            
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CMS_foodCategory().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(CMS_searchCategory.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(CMS_searchCategory.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

    }//GEN-LAST:event_txt_category_searchkeyReleasedActionPerformed

    private void SFC_btn_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SFC_btn_ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_SFC_btn_ActionPerformed

    private void jButtonSFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSFCActionPerformed
        // TODO add your handling code here:
        
            String catname = txt_category_searchkeyReleased.getText();
            
            String sql = "SELECT * FROM cms_category WHERE catName LIKE '%"+catname+"%'";
            try {
//                Class.forName(driver);
//            conn=DriverManager.getConnection(url, user, pw);
                    pst=conn.prepareStatement(sql);
                    rs=pst.executeQuery();
                    
                    jTable_searchCategory.setModel(DbUtils.resultSetToTableModel(rs));
                    
        } catch (SQLException e) {
        }
        
        
    }//GEN-LAST:event_jButtonSFCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SFC_btn_;
    private javax.swing.JButton jButtonSFC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_searchCategory;
    private javax.swing.JTextField txt_category_searchkeyReleased;
    // End of variables declaration//GEN-END:variables
}
