/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CMS;
import DBConnection.DBConnect;
import SPMS.dbConnection;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import static java.time.zone.ZoneRulesProvider.refresh;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.DriverManager;
import SPMS.dbConnection;
import SPMS_IREPORTS.IREPORT_PARAMETERIZED;
import java.util.HashMap;
 
/**
 *
 * @author user
 */
public class CMS_foodCategory extends javax.swing.JInternalFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
//    public String driver = "com.microsoft.jdbc.SQLServerDriver";
//    public String url = "jdbcsqlserver://localhost::24809:databaseName=smsDB";
//    public String user = "adminK";
//    public String pw = "admink";
    
  
    
    /**
     * Creates new form foodCategory
     */
    
    /*
    public class SIMS_LoginScreen extends javax.swing.JFrame{
        
    Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
    
    public String driver = "com.microsoft.jdbc.SQLServerDriver";
    public String url = "jdbcsqlserver://localhost::24809:databaseName=smsDB";
    public String user = "adminK";
    public String pw = "adminK";
    
    }
    
    */
    
    /*
    public SIMS_LoginScreen throws ClassNotFoundException,SQLException{
        initComponents();
    
        Class.forName(driver);
        conn=DriverManger.getConnection(url,user,pw);
    }
    */
    
    
    
    public CMS_foodCategory() throws ClassNotFoundException, SQLException {
        initComponents();
        
        
        conn = DBConnect.connect();
        
//        Class.forName(driver);
//        conn=DriverManager.getConnection(url, user, pw);
        
        //Connect to DB
        
        //Load table
        tableload();
        
        
    }
    
    public void tableload() throws ClassNotFoundException{
        try {
//            Class.forName(driver);
//            conn=DriverManager.getConnection(url, user, pw);
            String sql = "SELECT catId,catName,itemName FROM cms_category";
        
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            jTable_Category.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (SQLException e) {
        }
    }
    
    //Clear rows
    public void refresh()
    {
         cidBox.setText("");
         cnameBox.setText("");
         inameBox.setText("");
         
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCategory = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cidBox = new javax.swing.JTextField();
        cnameBox = new javax.swing.JTextField();
        inameBox = new javax.swing.JTextField();
        FCinsert_btn_ = new javax.swing.JButton();
        FDupdate_btn_ = new javax.swing.JButton();
        FCdelete_btn_ = new javax.swing.JButton();
        FCsearch_btn_ = new javax.swing.JButton();
        FCview_btn_ = new javax.swing.JButton();
        FCrefresh_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Category = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        IREPORT_catNameToItemName_BTN = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));
        setBorder(null);
        setForeground(new java.awt.Color(153, 153, 255));
        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(6, 20));
        setMinimumSize(new java.awt.Dimension(1256, 800));
        setPreferredSize(new java.awt.Dimension(1256, 800));
        getContentPane().setLayout(null);

        jPanelCategory.setBackground(new java.awt.Color(153, 153, 255));
        jPanelCategory.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Food Category", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 26), new java.awt.Color(153, 0, 153))); // NOI18N
        jPanelCategory.setMaximumSize(new java.awt.Dimension(1256, 800));
        jPanelCategory.setMinimumSize(new java.awt.Dimension(1256, 800));
        jPanelCategory.setPreferredSize(new java.awt.Dimension(1256, 800));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Food Category Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20), new java.awt.Color(51, 0, 153))); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(470, 420));
        jPanel2.setMinimumSize(new java.awt.Dimension(470, 420));
        jPanel2.setPreferredSize(new java.awt.Dimension(470, 420));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Category ID");
        jLabel1.setMaximumSize(new java.awt.Dimension(115, 19));
        jLabel1.setMinimumSize(new java.awt.Dimension(115, 19));
        jLabel1.setPreferredSize(new java.awt.Dimension(115, 19));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Category Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Item Name");
        jLabel3.setMaximumSize(new java.awt.Dimension(115, 19));
        jLabel3.setMinimumSize(new java.awt.Dimension(115, 19));
        jLabel3.setPreferredSize(new java.awt.Dimension(115, 19));

        cidBox.setMaximumSize(new java.awt.Dimension(200, 20));
        cidBox.setMinimumSize(new java.awt.Dimension(200, 20));
        cidBox.setPreferredSize(new java.awt.Dimension(200, 20));
        cidBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidBoxActionPerformed(evt);
            }
        });

        cnameBox.setMaximumSize(new java.awt.Dimension(200, 20));
        cnameBox.setMinimumSize(new java.awt.Dimension(200, 20));
        cnameBox.setPreferredSize(new java.awt.Dimension(200, 20));

        inameBox.setMaximumSize(new java.awt.Dimension(200, 20));
        inameBox.setMinimumSize(new java.awt.Dimension(200, 20));
        inameBox.setPreferredSize(new java.awt.Dimension(200, 20));

        FCinsert_btn_.setBackground(new java.awt.Color(0, 0, 102));
        FCinsert_btn_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FCinsert_btn_.setForeground(new java.awt.Color(255, 255, 255));
        FCinsert_btn_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_CMS/insert.png"))); // NOI18N
        FCinsert_btn_.setText("INSERT");
        FCinsert_btn_.setMaximumSize(new java.awt.Dimension(127, 40));
        FCinsert_btn_.setMinimumSize(new java.awt.Dimension(127, 40));
        FCinsert_btn_.setPreferredSize(new java.awt.Dimension(127, 40));
        FCinsert_btn_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FCinsert_btn_ActionPerformed(evt);
            }
        });

        FDupdate_btn_.setBackground(new java.awt.Color(0, 0, 102));
        FDupdate_btn_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FDupdate_btn_.setForeground(new java.awt.Color(255, 255, 255));
        FDupdate_btn_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_CMS/update.png"))); // NOI18N
        FDupdate_btn_.setText("UPDATE");
        FDupdate_btn_.setMaximumSize(new java.awt.Dimension(127, 40));
        FDupdate_btn_.setMinimumSize(new java.awt.Dimension(127, 40));
        FDupdate_btn_.setPreferredSize(new java.awt.Dimension(127, 40));
        FDupdate_btn_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FDupdate_btn_ActionPerformed(evt);
            }
        });

        FCdelete_btn_.setBackground(new java.awt.Color(0, 0, 102));
        FCdelete_btn_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FCdelete_btn_.setForeground(new java.awt.Color(255, 255, 255));
        FCdelete_btn_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_CMS/delete.png"))); // NOI18N
        FCdelete_btn_.setText("DELETE");
        FCdelete_btn_.setMaximumSize(new java.awt.Dimension(127, 40));
        FCdelete_btn_.setMinimumSize(new java.awt.Dimension(127, 40));
        FCdelete_btn_.setPreferredSize(new java.awt.Dimension(127, 40));
        FCdelete_btn_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FCdelete_btn_ActionPerformed(evt);
            }
        });

        FCsearch_btn_.setBackground(new java.awt.Color(0, 0, 102));
        FCsearch_btn_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FCsearch_btn_.setForeground(new java.awt.Color(255, 255, 255));
        FCsearch_btn_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_CMS/find.png"))); // NOI18N
        FCsearch_btn_.setText("SEARCH");
        FCsearch_btn_.setMaximumSize(new java.awt.Dimension(127, 40));
        FCsearch_btn_.setMinimumSize(new java.awt.Dimension(127, 40));
        FCsearch_btn_.setPreferredSize(new java.awt.Dimension(127, 40));
        FCsearch_btn_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FCsearch_btn_ActionPerformed(evt);
            }
        });

        FCview_btn_.setBackground(new java.awt.Color(0, 0, 102));
        FCview_btn_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FCview_btn_.setForeground(new java.awt.Color(255, 255, 255));
        FCview_btn_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_CMS/viewall.png"))); // NOI18N
        FCview_btn_.setText("VIEW");
        FCview_btn_.setMaximumSize(new java.awt.Dimension(127, 40));
        FCview_btn_.setMinimumSize(new java.awt.Dimension(127, 40));
        FCview_btn_.setPreferredSize(new java.awt.Dimension(127, 40));
        FCview_btn_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FCview_btn_ActionPerformed(evt);
            }
        });

        FCrefresh_btn.setBackground(new java.awt.Color(0, 0, 102));
        FCrefresh_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FCrefresh_btn.setForeground(new java.awt.Color(255, 255, 255));
        FCrefresh_btn.setText("Refresh");
        FCrefresh_btn.setMaximumSize(new java.awt.Dimension(127, 40));
        FCrefresh_btn.setMinimumSize(new java.awt.Dimension(127, 40));
        FCrefresh_btn.setPreferredSize(new java.awt.Dimension(127, 40));
        FCrefresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FCrefresh_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cnameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cidBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(FCdelete_btn_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FCinsert_btn_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(FCview_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FCsearch_btn_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FDupdate_btn_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FCrefresh_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidBox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FCinsert_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FDupdate_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FCdelete_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FCsearch_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FCview_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FCrefresh_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setPreferredSize(new java.awt.Dimension(512, 474));

        jTable_Category.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jTable_Category.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_CategoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Category);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        IREPORT_catNameToItemName_BTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        IREPORT_catNameToItemName_BTN.setForeground(new java.awt.Color(0, 0, 153));
        IREPORT_catNameToItemName_BTN.setText("Category Deatails");
        IREPORT_catNameToItemName_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IREPORT_catNameToItemName_BTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCategoryLayout = new javax.swing.GroupLayout(jPanelCategory);
        jPanelCategory.setLayout(jPanelCategoryLayout);
        jPanelCategoryLayout.setHorizontalGroup(
            jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategoryLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCategoryLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCategoryLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(IREPORT_catNameToItemName_BTN)))
                .addContainerGap(285, Short.MAX_VALUE))
        );
        jPanelCategoryLayout.setVerticalGroup(
            jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCategoryLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCategoryLayout.createSequentialGroup()
                        .addGroup(jPanelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IREPORT_catNameToItemName_BTN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 332, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelCategory);
        jPanelCategory.setBounds(0, 0, 1256, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cidBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidBoxActionPerformed

    private void FCdelete_btn_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FCdelete_btn_ActionPerformed
        // TODO add your handling code here:
        
        int confirmdelete = JOptionPane.showConfirmDialog(null, "Do you really want to delete this record ?","Delete",JOptionPane.YES_NO_OPTION);
        
        if(confirmdelete==0){
        
        try{
//            Class.forName(driver);
//            conn=DriverManager.getConnection(url, user, pw);
           String sql = "DELETE FROM cms_category WHERE catId=?"; 
        
           pst = conn.prepareStatement(sql);
        
           pst.setString(1,cidBox.getText());
        
           pst.executeUpdate();
           
           //Load table
             tableload();
             
               JOptionPane.showMessageDialog(null, "Record Deleted Successfully !");
        }
        
        catch(HeadlessException | SQLException ex){
            
            JOptionPane.showMessageDialog(null, ex);
        
        }   catch (ClassNotFoundException ex) {
                Logger.getLogger(CMS_foodCategory.class.getName()).log(Level.SEVERE, null, ex);
            }
      } 
    }//GEN-LAST:event_FCdelete_btn_ActionPerformed

    private void FCsearch_btn_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FCsearch_btn_ActionPerformed
        try {
            //
            jPanelCategory.removeAll();
            CMS_searchCategory sc = new CMS_searchCategory();
            jPanelCategory.add(sc).setVisible(true);
            
            CMS_searchCategory searchrecords =new CMS_searchCategory();
            searchrecords.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CMS_foodCategory.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CMS_foodCategory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_FCsearch_btn_ActionPerformed

    private void FCview_btn_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FCview_btn_ActionPerformed
        try {
            //
            jPanelCategory.removeAll();
            CMS_viewCategory vc = new CMS_viewCategory();
            jPanelCategory.add(vc).setVisible(true);
            
            
            CMS_viewCategory viewall = new CMS_viewCategory();
            viewall.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CMS_foodCategory.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CMS_foodCategory.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_FCview_btn_ActionPerformed

    private void FCinsert_btn_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FCinsert_btn_ActionPerformed

        String catId = cidBox.getText();
        String catName = cnameBox.getText();
        String itemName = inameBox.getText();
        
        //check null fields
        if(catName.isEmpty() || catId.isEmpty() || itemName.isEmpty()) {
                 
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, "Complete all the input fields!!");
        }
        else{
            String pattern = cidBox.getText().trim();
            cidBox.setText(pattern);
            
            if ((!pattern.isEmpty()) && (!pattern.matches("[0-9][0-9][0-9][0-9][0-9]")))
                    {
                        getToolkit().beep();
                        JOptionPane.showMessageDialog(null, "Invalid Input. Enter only 5 digits for CATEGORY ID!!");
                        cidBox.setText("");
                    }
            else
          
            try {
//                Class.forName(driver);
//            conn=DriverManager.getConnection(url, user, pw);
                    int confirminsert = JOptionPane.showConfirmDialog(null,"Do you really want to insert this record?","Insert",JOptionPane.YES_NO_OPTION);
                    
                    String sql = "INSERT INTO cms_category(catId, catName, itemName) VALUES ('"+catId+"','"+catName+"','"+itemName+"')";
                    
                    pst = conn.prepareStatement(sql);
                    pst.executeUpdate();
            
                    //Load table
                    tableload();
            
            JOptionPane.showMessageDialog(null,"Record Inserted Successfully");
            
            } catch (HeadlessException | SQLException e) {
                
                System.out.println("SQLException e");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CMS_foodCategory.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
    }//GEN-LAST:event_FCinsert_btn_ActionPerformed

    private void FDupdate_btn_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FDupdate_btn_ActionPerformed
        
            int confirmupdate = JOptionPane.showConfirmDialog(null, "Do you really want to update this record ?","Update",JOptionPane.YES_NO_OPTION);
            
            if(confirmupdate==0){ //Correct code
            
             try{
//                 Class.forName(driver);
//            conn=DriverManager.getConnection(url, user, pw);
            String sql = "UPDATE cms_category SET catName=?,itemName=? WHERE catId=?";
            
            pst = conn.prepareStatement(sql);
            pst.setString(3, cidBox.getText());
            pst.setString(1,cnameBox.getText());
            pst.setString(2,inameBox.getText());
            
            pst.executeUpdate();
            
            //Load table
              tableload();
            
            
            JOptionPane.showMessageDialog(null, "Record Updated Successfully !");
            
            }
            catch(SQLException | HeadlessException ex){
                    JOptionPane.showMessageDialog(null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(CMS_foodCategory.class.getName()).log(Level.SEVERE, null, ex);
                } 
          
            }
        
    }//GEN-LAST:event_FDupdate_btn_ActionPerformed

    private void jTable_CategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_CategoryMouseClicked
       
        int r = jTable_Category.getSelectedRow();
        
        String catId = jTable_Category.getValueAt(r, 0).toString();
        String catName = jTable_Category.getValueAt(r, 1).toString();
        String itemName  = jTable_Category.getValueAt(r, 2).toString(); 
        
        cidBox.setText(catId);
        cnameBox.setText(catName);
        inameBox.setText(itemName);
    }//GEN-LAST:event_jTable_CategoryMouseClicked

    private void FCrefresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FCrefresh_btnActionPerformed
       
        //Clear rows
        refresh();
    }//GEN-LAST:event_FCrefresh_btnActionPerformed

    private void IREPORT_catNameToItemName_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IREPORT_catNameToItemName_BTNActionPerformed
        
        // SELECT * FROM cms_category WHERE catname = pcatname;
        //select the item names accourding to categoey name 
  
//        
//        HashMap fp_p1 = new HashMap();
//        fp_p1.put("pcatname", txtfineReport.getText());
//
//        IREPORT_PARAMETERIZED showReport_fp = new IREPORT_PARAMETERIZED("C:\\Users\\Hashini\\Desktop\\3.jasper", fp_p1);
//        showReport_fp.setVisible(true);
        
        HashMap fp_p1 = new HashMap();
        fp_p1.put("pcatname", jTextField1.getText());
        
        IREPORT_PARAMETERIZED showReport_fp = new IREPORT_PARAMETERIZED("C:\\xampp\\htdocs\\ITP\\Project\\VIVA\\IREPORTS\\CMS_CategoryP.jasper", fp_p1);
        showReport_fp.setVisible(true);
        
    }//GEN-LAST:event_IREPORT_catNameToItemName_BTNActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
        
     
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FCdelete_btn_;
    private javax.swing.JButton FCinsert_btn_;
    private javax.swing.JButton FCrefresh_btn;
    private javax.swing.JButton FCsearch_btn_;
    private javax.swing.JButton FCview_btn_;
    private javax.swing.JButton FDupdate_btn_;
    private javax.swing.JButton IREPORT_catNameToItemName_BTN;
    private javax.swing.JTextField cidBox;
    private javax.swing.JTextField cnameBox;
    private javax.swing.JTextField inameBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCategory;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Category;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    
      
    }

