/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CMS;
import DBConnection.DBConnect;
import SPMS.dbConnection;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author user
 */
public class CMS_searchOrder extends javax.swing.JInternalFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
//    public String driver = "com.microsoft.jdbc.SQLServerDriver";
//    public String url = "jdbcsqlserver://localhost::24809:databaseName=smsDB";
//    public String user = "adminK";
//    public String pw = "admink";
    
    
    /**
     * Creates new form searchOrder
     */
    public CMS_searchOrder() throws ClassNotFoundException, SQLException {
        initComponents();
        
//        Class.forName(driver);
//conn=DriverManager.getConnection(url, user, pw);        
        
        
         conn = DBConnect.connect();
        //currentDateAndTime();
        viewStudentTable();
        CMS_viewOrder();
    }
    
    public void viewStudentTable(){
        
        try{
            
        String sql1 = "SELECT * FROM cms_item";
        pst = conn.prepareStatement(sql1);
        rs = pst.executeQuery();
        jTable_searchOrder.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        
        catch(Exception e ){
            
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    public void CMS_viewOrder() throws ClassNotFoundException{
        
        try{
//            Class.forName(driver);
//            conn=DriverManager.getConnection(url, user, pw);
        String sql = "SELECT * FROM cms_order";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        jTable_searchOrder.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        catch(SQLException e ){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    /*public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_order_searchkeyReleased = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_searchOrder = new javax.swing.JTable();
        SFO_btn_ = new javax.swing.JButton();
        jButtonSFO = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1256, 800));
        setMinimumSize(new java.awt.Dimension(1256, 800));
        setPreferredSize(new java.awt.Dimension(1256, 800));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1240, 448));
        jPanel1.setMinimumSize(new java.awt.Dimension(1240, 448));
        jPanel1.setPreferredSize(new java.awt.Dimension(1240, 448));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Food Order Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20), new java.awt.Color(153, 0, 153))); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(1020, 415));
        jPanel2.setMinimumSize(new java.awt.Dimension(1020, 415));
        jPanel2.setPreferredSize(new java.awt.Dimension(1020, 415));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Type the order ID to search the food order details");

        txt_order_searchkeyReleased.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_order_searchkeyReleasedActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setMaximumSize(new java.awt.Dimension(850, 310));
        jPanel3.setMinimumSize(new java.awt.Dimension(850, 310));
        jPanel3.setPreferredSize(new java.awt.Dimension(850, 310));

        jTable_searchOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable_searchOrder.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable_searchOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTable_searchOrder.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable_searchOrder);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        SFO_btn_.setBackground(new java.awt.Color(0, 0, 102));
        SFO_btn_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SFO_btn_.setForeground(new java.awt.Color(255, 255, 255));
        SFO_btn_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_CMS/backTo.png"))); // NOI18N
        SFO_btn_.setActionCommand("BACK");
        SFO_btn_.setLabel("BACK");
        SFO_btn_.setMaximumSize(new java.awt.Dimension(110, 40));
        SFO_btn_.setMinimumSize(new java.awt.Dimension(110, 40));
        SFO_btn_.setPreferredSize(new java.awt.Dimension(110, 40));
        SFO_btn_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SFO_btn_ActionPerformed(evt);
            }
        });

        jButtonSFO.setBackground(new java.awt.Color(0, 0, 102));
        jButtonSFO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSFO.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSFO.setText("Search");
        jButtonSFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSFOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_order_searchkeyReleased, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonSFO, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SFO_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SFO_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_order_searchkeyReleased, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSFO))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 288, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_order_searchkeyReleasedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_order_searchkeyReleasedActionPerformed
        // TODO add your handling code here:
        DefaultTableModel table =(DefaultTableModel)jTable_searchOrder.getModel();
        String search=txt_order_searchkeyReleased.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(table);
        jTable_searchOrder.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
        
        
        try{
//            Class.forName(driver);
//            conn=DriverManager.getConnection(url, user, pw);
            String sql="SELECT * FROM cms_order WHERE orderId=?";
            
            pst=conn.prepareStatement(sql);
           // pst.setString(1,((JTextField)oDateChooseBox.getDateEditor().getUiComponent()).getText());
            pst.setString(1,txt_order_searchkeyReleased.getText());
            rs=pst.executeQuery();
            
            
            
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CMS_foodCategory().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(CMS_searchOrder.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(CMS_searchOrder.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        
    }//GEN-LAST:event_txt_order_searchkeyReleasedActionPerformed

    private void SFO_btn_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SFO_btn_ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_SFO_btn_ActionPerformed

    private void jButtonSFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSFOActionPerformed
        // TODO add your handling code here:

        String oid = txt_order_searchkeyReleased.getText();

        String sql = "SELECT * FROM cms_order WHERE orderId LIKE '%"+oid+"%'";
        try {
//            Class.forName(driver);
//            conn=DriverManager.getConnection(url, user, pw);
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();

            jTable_searchOrder.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
        }

    }//GEN-LAST:event_jButtonSFOActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SFO_btn_;
    private javax.swing.JButton jButtonSFO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_searchOrder;
    private javax.swing.JTextField txt_order_searchkeyReleased;
    // End of variables declaration//GEN-END:variables
}
