/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CMS;
import DBConnection.DBConnect;
import SPMS.dbConnection;
import SPMS_IREPORTS.IREPORT_PARAMETERIZED;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author user
 */
public class CMS_foodPayments extends javax.swing.JInternalFrame {

    /**
     * Creates new form foodPayments
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
//    public String driver = "com.microsoft.jdbc.SQLServerDriver";
//    public String url = "jdbcsqlserver://localhost::24809:databaseName=smsDB";
//    public String user = "adminK";
//    public String pw = "admink";
    
    public CMS_foodPayments() throws SQLException, ClassNotFoundException {
        initComponents();
        
//        Class.forName(driver);
//conn=DriverManager.getConnection(url, user, pw);        
        //Connect to DB
        
         conn = DBConnect.connect();
        
        //Load table
        tableload();
    }
    
    public void tableload() throws ClassNotFoundException{
            try {
//                Class.forName(driver);
//            conn=DriverManager.getConnection(url, user, pw);
                    String sql = "SELECT billno, orderId, date, totalPrice FROM cms_payment";
                    
                    pst = conn.prepareStatement(sql);
                    rs = pst.executeQuery();
            
                    jTable_Payment.setModel(DbUtils.resultSetToTableModel(rs));
                    
        } catch (SQLException e) {
        }
            
    }
    
    //Clear rows
    public void refresh()
    {
        PreceiptBox.setText("");
        oidComboBox2.setSelectedItem("Select Order ID");
        fpDateChooseBox.setDate(null);
        priceBox.setText("");
    }     
         

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPayments = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PreceiptBox = new javax.swing.JTextField();
        priceBox = new javax.swing.JTextField();
        fpDateChooseBox = new com.toedter.calendar.JDateChooser();
        oidComboBox2 = new javax.swing.JComboBox<>();
        FPinsert_btn_ = new javax.swing.JButton();
        FPupdate_btn_ = new javax.swing.JButton();
        FDdelete_btn_ = new javax.swing.JButton();
        FPsearch_btn_ = new javax.swing.JButton();
        FPview_btn_ = new javax.swing.JButton();
        IREPORTbill_BTN_np = new javax.swing.JButton();
        FPrefresh_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Payment = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        IREPORT_billNoTototalPrice_BTN = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1266, 594));
        setPreferredSize(new java.awt.Dimension(1266, 594));

        jPanelPayments.setBackground(new java.awt.Color(153, 153, 255));
        jPanelPayments.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Food Payments", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 26), new java.awt.Color(153, 0, 153))); // NOI18N
        jPanelPayments.setMaximumSize(new java.awt.Dimension(470, 420));
        jPanelPayments.setMinimumSize(new java.awt.Dimension(470, 420));
        jPanelPayments.setPreferredSize(new java.awt.Dimension(470, 420));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Food Payment Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20), new java.awt.Color(51, 0, 153))); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(470, 420));
        jPanel2.setMinimumSize(new java.awt.Dimension(470, 420));
        jPanel2.setPreferredSize(new java.awt.Dimension(470, 420));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Receipt Number");
        jLabel1.setMaximumSize(new java.awt.Dimension(127, 19));
        jLabel1.setMinimumSize(new java.awt.Dimension(127, 19));
        jLabel1.setPreferredSize(new java.awt.Dimension(127, 19));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Order ID");
        jLabel2.setMaximumSize(new java.awt.Dimension(127, 19));
        jLabel2.setMinimumSize(new java.awt.Dimension(127, 19));
        jLabel2.setPreferredSize(new java.awt.Dimension(127, 19));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setText("Order Date");
        jLabel7.setMaximumSize(new java.awt.Dimension(127, 19));
        jLabel7.setMinimumSize(new java.awt.Dimension(127, 19));
        jLabel7.setPreferredSize(new java.awt.Dimension(127, 19));

        jLabel8.setBackground(new java.awt.Color(153, 153, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 102));
        jLabel8.setText("Total Price");
        jLabel8.setMaximumSize(new java.awt.Dimension(127, 19));
        jLabel8.setMinimumSize(new java.awt.Dimension(127, 19));
        jLabel8.setOpaque(true);
        jLabel8.setPreferredSize(new java.awt.Dimension(127, 19));

        PreceiptBox.setMaximumSize(new java.awt.Dimension(200, 20));
        PreceiptBox.setMinimumSize(new java.awt.Dimension(200, 20));
        PreceiptBox.setPreferredSize(new java.awt.Dimension(200, 20));

        priceBox.setMaximumSize(new java.awt.Dimension(200, 20));
        priceBox.setMinimumSize(new java.awt.Dimension(200, 20));
        priceBox.setPreferredSize(new java.awt.Dimension(200, 20));
        priceBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                priceBoxKeyTyped(evt);
            }
        });

        oidComboBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        oidComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Order ID", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        FPinsert_btn_.setBackground(new java.awt.Color(0, 0, 102));
        FPinsert_btn_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FPinsert_btn_.setForeground(new java.awt.Color(255, 255, 255));
        FPinsert_btn_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_CMS/insert.png"))); // NOI18N
        FPinsert_btn_.setText("INSERT");
        FPinsert_btn_.setMaximumSize(new java.awt.Dimension(127, 40));
        FPinsert_btn_.setMinimumSize(new java.awt.Dimension(127, 40));
        FPinsert_btn_.setPreferredSize(new java.awt.Dimension(127, 40));
        FPinsert_btn_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FPinsert_btn_ActionPerformed(evt);
            }
        });

        FPupdate_btn_.setBackground(new java.awt.Color(0, 0, 102));
        FPupdate_btn_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FPupdate_btn_.setForeground(new java.awt.Color(255, 255, 255));
        FPupdate_btn_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_CMS/update.png"))); // NOI18N
        FPupdate_btn_.setText("UPDATE");
        FPupdate_btn_.setMaximumSize(new java.awt.Dimension(127, 40));
        FPupdate_btn_.setMinimumSize(new java.awt.Dimension(127, 40));
        FPupdate_btn_.setPreferredSize(new java.awt.Dimension(127, 40));
        FPupdate_btn_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FPupdate_btn_ActionPerformed(evt);
            }
        });

        FDdelete_btn_.setBackground(new java.awt.Color(0, 0, 102));
        FDdelete_btn_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FDdelete_btn_.setForeground(new java.awt.Color(255, 255, 255));
        FDdelete_btn_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_CMS/delete.png"))); // NOI18N
        FDdelete_btn_.setText("DELETE");
        FDdelete_btn_.setMaximumSize(new java.awt.Dimension(127, 40));
        FDdelete_btn_.setMinimumSize(new java.awt.Dimension(127, 40));
        FDdelete_btn_.setPreferredSize(new java.awt.Dimension(127, 40));
        FDdelete_btn_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FDdelete_btn_ActionPerformed(evt);
            }
        });

        FPsearch_btn_.setBackground(new java.awt.Color(0, 0, 102));
        FPsearch_btn_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FPsearch_btn_.setForeground(new java.awt.Color(255, 255, 255));
        FPsearch_btn_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_CMS/find.png"))); // NOI18N
        FPsearch_btn_.setText("SEARCH");
        FPsearch_btn_.setMaximumSize(new java.awt.Dimension(127, 40));
        FPsearch_btn_.setMinimumSize(new java.awt.Dimension(127, 40));
        FPsearch_btn_.setPreferredSize(new java.awt.Dimension(127, 40));
        FPsearch_btn_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FPsearch_btn_ActionPerformed(evt);
            }
        });

        FPview_btn_.setBackground(new java.awt.Color(0, 0, 102));
        FPview_btn_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FPview_btn_.setForeground(new java.awt.Color(255, 255, 255));
        FPview_btn_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_CMS/viewall.png"))); // NOI18N
        FPview_btn_.setText("VIEW");
        FPview_btn_.setMaximumSize(new java.awt.Dimension(127, 40));
        FPview_btn_.setMinimumSize(new java.awt.Dimension(127, 40));
        FPview_btn_.setPreferredSize(new java.awt.Dimension(127, 40));
        FPview_btn_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FPview_btn_ActionPerformed(evt);
            }
        });

        IREPORTbill_BTN_np.setBackground(new java.awt.Color(0, 0, 102));
        IREPORTbill_BTN_np.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IREPORTbill_BTN_np.setForeground(new java.awt.Color(255, 255, 255));
        IREPORTbill_BTN_np.setText("Generate Total Bill");
        IREPORTbill_BTN_np.setMaximumSize(new java.awt.Dimension(127, 40));
        IREPORTbill_BTN_np.setMinimumSize(new java.awt.Dimension(127, 40));
        IREPORTbill_BTN_np.setPreferredSize(new java.awt.Dimension(127, 40));
        IREPORTbill_BTN_np.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IREPORTbill_BTN_npActionPerformed(evt);
            }
        });

        FPrefresh_btn.setBackground(new java.awt.Color(0, 0, 102));
        FPrefresh_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FPrefresh_btn.setForeground(new java.awt.Color(255, 255, 255));
        FPrefresh_btn.setText("Refresh");
        FPrefresh_btn.setMaximumSize(new java.awt.Dimension(127, 40));
        FPrefresh_btn.setMinimumSize(new java.awt.Dimension(127, 40));
        FPrefresh_btn.setPreferredSize(new java.awt.Dimension(127, 40));
        FPrefresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FPrefresh_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PreceiptBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(oidComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fpDateChooseBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(priceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FPinsert_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FDdelete_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FPsearch_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FPupdate_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FPrefresh_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(FPview_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(IREPORTbill_BTN_np, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PreceiptBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(oidComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fpDateChooseBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(priceBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FPinsert_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FPupdate_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FPsearch_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FDdelete_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FPview_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FPrefresh_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IREPORTbill_BTN_np, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setPreferredSize(new java.awt.Dimension(512, 474));

        jTable_Payment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_Payment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_PaymentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Payment);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        IREPORT_billNoTototalPrice_BTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        IREPORT_billNoTototalPrice_BTN.setForeground(new java.awt.Color(0, 0, 153));
        IREPORT_billNoTototalPrice_BTN.setText("Payment Deatails");
        IREPORT_billNoTototalPrice_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IREPORT_billNoTototalPrice_BTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPaymentsLayout = new javax.swing.GroupLayout(jPanelPayments);
        jPanelPayments.setLayout(jPanelPaymentsLayout);
        jPanelPaymentsLayout.setHorizontalGroup(
            jPanelPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaymentsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPaymentsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPaymentsLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(IREPORT_billNoTototalPrice_BTN)))
                .addContainerGap(311, Short.MAX_VALUE))
        );
        jPanelPaymentsLayout.setVerticalGroup(
            jPanelPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaymentsLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelPaymentsLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanelPaymentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IREPORT_billNoTototalPrice_BTN))
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPayments, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1250, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPayments, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FDdelete_btn_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FDdelete_btn_ActionPerformed

        int confirmdelete = JOptionPane.showConfirmDialog(null, "Do you really want to delete this record ?","Delete",JOptionPane.YES_NO_OPTION);
        
        if(confirmdelete==0){
        
        try{
//            Class.forName(driver);
//            conn=DriverManager.getConnection(url, user, pw);
            String sql = "DELETE FROM cms_payment WHERE billno=?";
        
            pst = conn.prepareStatement(sql);
            pst.setString(1,PreceiptBox.getText());
            pst.executeUpdate();
            
            //Load table
              tableload();
        
            JOptionPane.showMessageDialog(null, "Record Deleted Successfully !");
        }
        
        catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }   catch (ClassNotFoundException ex) {
                Logger.getLogger(CMS_foodPayments.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_FDdelete_btn_ActionPerformed

    private void FPsearch_btn_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FPsearch_btn_ActionPerformed
        try {
            //
            jPanelPayments.removeAll();
            CMS_searchPayment sp = new CMS_searchPayment();
            jPanelPayments.add(sp).setVisible(true);
            
            CMS_searchPayment searchrecords =new CMS_searchPayment();
            searchrecords.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CMS_foodPayments.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CMS_foodPayments.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_FPsearch_btn_ActionPerformed

    private void FPview_btn_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FPview_btn_ActionPerformed
        try {
            //
            jPanelPayments.removeAll();
            CMS_viewPayment vp = new CMS_viewPayment();
            jPanelPayments.add(vp).setVisible(true);
            
            CMS_viewPayment viewall = new CMS_viewPayment();
            viewall.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(CMS_foodPayments.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CMS_foodPayments.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_FPview_btn_ActionPerformed

    private void FPinsert_btn_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FPinsert_btn_ActionPerformed
        
        String ReceiptNo = PreceiptBox.getText();
        String OrderID = oidComboBox2.getSelectedItem().toString();
        String OrderDate =  ((JTextField)fpDateChooseBox.getDateEditor().getUiComponent()).getText();
        String TotalPrice = priceBox.getText();
        
         //check null fields
        if (ReceiptNo.isEmpty() || OrderID.isEmpty() || OrderDate.isEmpty() || TotalPrice.isEmpty() ){
                    
                JOptionPane.showMessageDialog(null, "Complete all the input fields!!");
             }
        else 
         try {
//             Class.forName(driver);
//            conn=DriverManager.getConnection(url, user, pw);
                int confirminsert = JOptionPane.showConfirmDialog(null,"Do you really want to insert this record?","Insert",JOptionPane.YES_NO_OPTION);

                String sql = "INSERT INTO cms_payment"
                         +"(orderId, date, totalPrice)" 
                         +" VALUES (?,?,?)";

                pst = conn.prepareStatement(sql);

                String value1 = oidComboBox2.getSelectedItem().toString();
                pst.setString(1, value1);
                pst.setString(2,((JTextField)fpDateChooseBox.getDateEditor().getUiComponent()).getText());
                pst.setString(3,priceBox.getText());

                pst.executeUpdate();

                 //Load table
                 tableload();

                   JOptionPane.showMessageDialog(null,"Record Inserted Successfully");
                
        } catch (HeadlessException | SQLException ex) {
                   JOptionPane.showMessageDialog(null,ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CMS_foodPayments.class.getName()).log(Level.SEVERE, null, ex);
        }
       // }
    }//GEN-LAST:event_FPinsert_btn_ActionPerformed

    private void FPupdate_btn_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FPupdate_btn_ActionPerformed
   
         int confirmupdate = JOptionPane.showConfirmDialog(null, "Do you really want to update this record ?","Update",JOptionPane.YES_NO_OPTION);
        
        if(confirmupdate==0){
            
        try {
//            Class.forName(driver);
//            conn=DriverManager.getConnection(url, user, pw);
            String sql = "UPDATE cms_payment SET orderId=?,date=?,totalPrice=? WHERE billno=?";
         //UPDATE `cms_payment` SET `billno`=[value-1],`orderId`=[value-2],`date`=[value-3],`totalPrice`=[value-4] WHERE 1
            pst = conn.prepareStatement(sql);
            
            pst.setString(4,PreceiptBox.getText());
            String value1 = oidComboBox2.getSelectedItem().toString();
            pst.setString(1, value1);
            pst.setString(2,((JTextField)fpDateChooseBox.getDateEditor().getUiComponent()).getText());
            pst.setString(3,priceBox.getText());
             
            pst.executeUpdate();
             
            //Load table
            tableload();
               
                JOptionPane.showMessageDialog(null,"Record Updated Successfully");
                
            } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
          }  catch (ClassNotFoundException ex) {
                 Logger.getLogger(CMS_foodPayments.class.getName()).log(Level.SEVERE, null, ex);
             }
        }        
              
    }//GEN-LAST:event_FPupdate_btn_ActionPerformed

    private void jTable_PaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_PaymentMouseClicked
      
        int r = jTable_Payment.getSelectedRow();
        
        String ReceiptNo = jTable_Payment.getValueAt(r, 0).toString();
        String OrderID = jTable_Payment.getValueAt(r, 1).toString();
        String OrderDate = jTable_Payment.getValueAt(r, 2).toString();
        String TotalPrice = jTable_Payment.getValueAt(r, 3).toString(); 

        try{ 
            java.util.Date date = new SimpleDateFormat("MMM d,yyyy").parse(OrderDate);
            PreceiptBox.setText(ReceiptNo);
            oidComboBox2.setSelectedItem(OrderID);
            fpDateChooseBox.setDate(date);
            priceBox.setText(TotalPrice);
        }
        catch(ParseException e){
        JOptionPane.showMessageDialog(null, e);
        
    }
        
        
    }//GEN-LAST:event_jTable_PaymentMouseClicked

    private void priceBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceBoxKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)|| (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Enter NUMERIC values!!");
        
        }
    }//GEN-LAST:event_priceBoxKeyTyped

    private void FPrefresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FPrefresh_btnActionPerformed
        
        //Clear rows
        refresh();
    }//GEN-LAST:event_FPrefresh_btnActionPerformed

    private void IREPORT_billNoTototalPrice_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IREPORT_billNoTototalPrice_BTNActionPerformed
       
        //SELECT * FROM cms_payment WHERE totalPrice > $P(ptotalPrice);
         
        
//        HashMap fp_p1 = new HashMap();
//        fp_p1.put("ptotalPrice", txtfineReport.getText());
//
//        IREPORT_PARAMETERIZED showReport_fp = new IREPORT_PARAMETERIZED("C:\\Users\\Hashini\\Desktop\\3.jasper", fp_p1);
//        showReport_fp.setVisible(true);

HashMap fp_p1 = new HashMap();
        fp_p1.put("ptotal", jTextField1.getText());
        
        IREPORT_PARAMETERIZED showReport_fp = new IREPORT_PARAMETERIZED("C:\\xampp\\htdocs\\ITP\\Project\\VIVA\\IREPORTS\\CMS_PyamentP.jasper", fp_p1);
        showReport_fp.setVisible(true);
        
        
        
    }//GEN-LAST:event_IREPORT_billNoTototalPrice_BTNActionPerformed

    private void IREPORTbill_BTN_npActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IREPORTbill_BTN_npActionPerformed
     
        
         
        /*
	//Quary
        SELECT * FROM cms_payment;
          
          try {
            String feedback_report = "G:\\2nd Year Sem 2\\ITP\\IREPORTS\\HMS_feedback_report.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(feedback_report);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
            JasperViewer.viewReport(jp, false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        */
        
        try {
            String studentList = "C:\\xampp\\htdocs\\ITP\\Project\\VIVA\\IREPORTS\\CMS_AllPaymentsN.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(studentList);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
            JasperViewer.viewReport(jp, false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_IREPORTbill_BTN_npActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FDdelete_btn_;
    private javax.swing.JButton FPinsert_btn_;
    private javax.swing.JButton FPrefresh_btn;
    private javax.swing.JButton FPsearch_btn_;
    private javax.swing.JButton FPupdate_btn_;
    private javax.swing.JButton FPview_btn_;
    private javax.swing.JButton IREPORT_billNoTototalPrice_BTN;
    private javax.swing.JButton IREPORTbill_BTN_np;
    private javax.swing.JTextField PreceiptBox;
    private com.toedter.calendar.JDateChooser fpDateChooseBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelPayments;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Payment;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> oidComboBox2;
    private javax.swing.JTextField priceBox;
    // End of variables declaration//GEN-END:variables
}
