/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CMS;
import DBConnection.DBConnect;
import SPMS.dbConnection;
import SPMS_IREPORTS.IREPORT_PARAMETERIZED;

import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.String;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.Date;
import static java.sql.JDBCType.DATE;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import static java.sql.Types.DATE;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import static java.util.Calendar.DATE;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author user
 */
public final class CMS_foodOrder extends javax.swing.JInternalFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
//    public String driver = "com.microsoft.jdbc.SQLServerDriver";
//    public String url = "jdbcsqlserver://localhost::24809:databaseName=smsDB";
//    public String user = "adminK";
//    public String pw = "admink";
    
    
    /**
     * Creates new form foodOrder
     */
    public CMS_foodOrder() throws SQLException, ClassNotFoundException {
        initComponents();
        
//        Class.forName(driver);
//conn=DriverManager.getConnection(url, user, pw);        
        //Connect to DB
        
        conn = DBConnect.connect();
       
        //Load table
        tableload();
    }
    
    
    public void tableload() throws ClassNotFoundException{
            try {
//                Class.forName(driver);
//            conn=DriverManager.getConnection(url, user, pw);
                    String sql = "SELECT orderQty, orderId, itemId, date, orderPrice FROM cms_order";
                    
                    pst = conn.prepareStatement(sql);
                    rs = pst.executeQuery();
            
                    jTable_Order.setModel(DbUtils.resultSetToTableModel(rs));
                    
        } catch (SQLException e) {
        }
            
    }
    
    //Clear rows
    public void refresh()
    {
        oqComboBox.setSelectedItem("Select a quantity");
        oidComboBox.setSelectedItem("Select Order ID");
        iIDbox.setText("");
        oDateChooseBox.setDate(null);
        oPriceBox.setText("");
    }     

    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelOrder = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        oPriceBox = new javax.swing.JTextField();
        oqComboBox = new javax.swing.JComboBox<>();
        iIDbox = new javax.swing.JTextField();
        oidComboBox = new javax.swing.JComboBox<>();
        oDateChooseBox = new com.toedter.calendar.JDateChooser();
        FOinsert_btn_ = new javax.swing.JButton();
        FOupdate_btn_ = new javax.swing.JButton();
        FOdelete_btn_ = new javax.swing.JButton();
        FOsearch_btn_ = new javax.swing.JButton();
        FOview_btn_ = new javax.swing.JButton();
        FOvrefresh_btn = new javax.swing.JButton();
        IREPORTorder_BTN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Order = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        IREPORT_orderIDorderDate_BTN = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1256, 800));
        setMinimumSize(new java.awt.Dimension(1256, 800));
        setPreferredSize(new java.awt.Dimension(1256, 800));

        jPanelOrder.setBackground(new java.awt.Color(153, 153, 255));
        jPanelOrder.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Food Orders", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 26), new java.awt.Color(153, 0, 153))); // NOI18N
        jPanelOrder.setMaximumSize(new java.awt.Dimension(1256, 800));
        jPanelOrder.setMinimumSize(new java.awt.Dimension(1256, 800));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Food Order Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20), new java.awt.Color(51, 0, 153))); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(470, 420));
        jPanel2.setMinimumSize(new java.awt.Dimension(470, 420));
        jPanel2.setPreferredSize(new java.awt.Dimension(470, 420));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Order ID");
        jLabel1.setMaximumSize(new java.awt.Dimension(115, 19));
        jLabel1.setMinimumSize(new java.awt.Dimension(115, 19));
        jLabel1.setPreferredSize(new java.awt.Dimension(115, 19));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Item ID");
        jLabel2.setMaximumSize(new java.awt.Dimension(115, 19));
        jLabel2.setMinimumSize(new java.awt.Dimension(115, 19));
        jLabel2.setPreferredSize(new java.awt.Dimension(115, 19));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Order Quantity");
        jLabel3.setMaximumSize(new java.awt.Dimension(115, 19));
        jLabel3.setMinimumSize(new java.awt.Dimension(115, 19));
        jLabel3.setPreferredSize(new java.awt.Dimension(115, 19));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("Date");
        jLabel4.setMaximumSize(new java.awt.Dimension(115, 19));
        jLabel4.setMinimumSize(new java.awt.Dimension(115, 19));
        jLabel4.setPreferredSize(new java.awt.Dimension(115, 19));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Price");
        jLabel5.setMaximumSize(new java.awt.Dimension(115, 19));
        jLabel5.setMinimumSize(new java.awt.Dimension(115, 19));
        jLabel5.setPreferredSize(new java.awt.Dimension(115, 19));

        oPriceBox.setMaximumSize(new java.awt.Dimension(200, 20));
        oPriceBox.setMinimumSize(new java.awt.Dimension(200, 20));
        oPriceBox.setPreferredSize(new java.awt.Dimension(200, 20));
        oPriceBox.setRequestFocusEnabled(false);
        oPriceBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                oPriceBoxKeyTyped(evt);
            }
        });

        oqComboBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        oqComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a quantity", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40" }));
        oqComboBox.setLightWeightPopupEnabled(false);
        oqComboBox.setMaximumSize(new java.awt.Dimension(200, 20));
        oqComboBox.setMinimumSize(new java.awt.Dimension(200, 20));
        oqComboBox.setPreferredSize(new java.awt.Dimension(200, 20));
        oqComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oqComboBoxActionPerformed(evt);
            }
        });

        iIDbox.setMaximumSize(new java.awt.Dimension(200, 20));
        iIDbox.setMinimumSize(new java.awt.Dimension(200, 20));
        iIDbox.setPreferredSize(new java.awt.Dimension(200, 20));

        oidComboBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        oidComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Order ID", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" }));

        FOinsert_btn_.setBackground(new java.awt.Color(0, 0, 102));
        FOinsert_btn_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FOinsert_btn_.setForeground(new java.awt.Color(255, 255, 255));
        FOinsert_btn_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_CMS/insert.png"))); // NOI18N
        FOinsert_btn_.setText("INSERT");
        FOinsert_btn_.setMaximumSize(new java.awt.Dimension(127, 40));
        FOinsert_btn_.setMinimumSize(new java.awt.Dimension(127, 40));
        FOinsert_btn_.setPreferredSize(new java.awt.Dimension(127, 40));
        FOinsert_btn_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FOinsert_btn_ActionPerformed(evt);
            }
        });

        FOupdate_btn_.setBackground(new java.awt.Color(0, 0, 102));
        FOupdate_btn_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FOupdate_btn_.setForeground(new java.awt.Color(255, 255, 255));
        FOupdate_btn_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_CMS/update.png"))); // NOI18N
        FOupdate_btn_.setText("UPDATE");
        FOupdate_btn_.setMaximumSize(new java.awt.Dimension(127, 40));
        FOupdate_btn_.setMinimumSize(new java.awt.Dimension(127, 40));
        FOupdate_btn_.setPreferredSize(new java.awt.Dimension(127, 40));
        FOupdate_btn_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FOupdate_btn_ActionPerformed(evt);
            }
        });

        FOdelete_btn_.setBackground(new java.awt.Color(0, 0, 102));
        FOdelete_btn_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FOdelete_btn_.setForeground(new java.awt.Color(255, 255, 255));
        FOdelete_btn_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_CMS/delete.png"))); // NOI18N
        FOdelete_btn_.setText("DELETE");
        FOdelete_btn_.setMaximumSize(new java.awt.Dimension(127, 40));
        FOdelete_btn_.setMinimumSize(new java.awt.Dimension(127, 40));
        FOdelete_btn_.setPreferredSize(new java.awt.Dimension(127, 40));
        FOdelete_btn_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FOdelete_btn_ActionPerformed(evt);
            }
        });

        FOsearch_btn_.setBackground(new java.awt.Color(0, 0, 102));
        FOsearch_btn_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FOsearch_btn_.setForeground(new java.awt.Color(255, 255, 255));
        FOsearch_btn_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_CMS/find.png"))); // NOI18N
        FOsearch_btn_.setText("SEARCH");
        FOsearch_btn_.setMaximumSize(new java.awt.Dimension(127, 40));
        FOsearch_btn_.setMinimumSize(new java.awt.Dimension(127, 40));
        FOsearch_btn_.setPreferredSize(new java.awt.Dimension(127, 40));
        FOsearch_btn_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FOsearch_btn_ActionPerformed(evt);
            }
        });

        FOview_btn_.setBackground(new java.awt.Color(0, 0, 102));
        FOview_btn_.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FOview_btn_.setForeground(new java.awt.Color(255, 255, 255));
        FOview_btn_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG_CMS/viewall.png"))); // NOI18N
        FOview_btn_.setText("VIEW");
        FOview_btn_.setMaximumSize(new java.awt.Dimension(127, 40));
        FOview_btn_.setMinimumSize(new java.awt.Dimension(127, 40));
        FOview_btn_.setPreferredSize(new java.awt.Dimension(127, 40));
        FOview_btn_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FOview_btn_ActionPerformed(evt);
            }
        });

        FOvrefresh_btn.setBackground(new java.awt.Color(0, 0, 102));
        FOvrefresh_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FOvrefresh_btn.setForeground(new java.awt.Color(255, 255, 255));
        FOvrefresh_btn.setText("Refresh");
        FOvrefresh_btn.setMaximumSize(new java.awt.Dimension(127, 40));
        FOvrefresh_btn.setMinimumSize(new java.awt.Dimension(127, 40));
        FOvrefresh_btn.setPreferredSize(new java.awt.Dimension(127, 40));
        FOvrefresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FOvrefresh_btnActionPerformed(evt);
            }
        });

        IREPORTorder_BTN.setBackground(new java.awt.Color(0, 0, 102));
        IREPORTorder_BTN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IREPORTorder_BTN.setForeground(new java.awt.Color(255, 255, 255));
        IREPORTorder_BTN.setText("Generate Order Details");
        IREPORTorder_BTN.setMaximumSize(new java.awt.Dimension(127, 40));
        IREPORTorder_BTN.setMinimumSize(new java.awt.Dimension(127, 40));
        IREPORTorder_BTN.setPreferredSize(new java.awt.Dimension(127, 40));
        IREPORTorder_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IREPORTorder_BTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(oqComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(220, 220, 220))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(oidComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(oDateChooseBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(iIDbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(oPriceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(FOinsert_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FOdelete_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FOview_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(FOsearch_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FOupdate_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FOvrefresh_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(IREPORTorder_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oqComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oidComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iIDbox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oDateChooseBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oPriceBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FOinsert_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FOupdate_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FOdelete_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FOsearch_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FOview_btn_, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FOvrefresh_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IREPORTorder_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setPreferredSize(new java.awt.Dimension(512, 474));

        jTable_Order.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTable_Order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_OrderMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Order);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        IREPORT_orderIDorderDate_BTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        IREPORT_orderIDorderDate_BTN.setForeground(new java.awt.Color(0, 0, 153));
        IREPORT_orderIDorderDate_BTN.setText("Order Report");
        IREPORT_orderIDorderDate_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IREPORT_orderIDorderDate_BTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOrderLayout = new javax.swing.GroupLayout(jPanelOrder);
        jPanelOrder.setLayout(jPanelOrderLayout);
        jPanelOrderLayout.setHorizontalGroup(
            jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrderLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOrderLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelOrderLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(IREPORT_orderIDorderDate_BTN)))
                .addGap(0, 296, Short.MAX_VALUE))
        );
        jPanelOrderLayout.setVerticalGroup(
            jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrderLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelOrderLayout.createSequentialGroup()
                        .addGroup(jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IREPORT_orderIDorderDate_BTN))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 325, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oqComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oqComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oqComboBoxActionPerformed

    private void FOdelete_btn_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FOdelete_btn_ActionPerformed
      
        
        int confirmdelete = JOptionPane.showConfirmDialog(null, "Do you really want to delete this record ?","Delete",JOptionPane.YES_NO_OPTION);
        
        if(confirmdelete==0){
        
        try{
//            Class.forName(driver);
//            conn=DriverManager.getConnection(url, user, pw);
            String sql = "DELETE FROM cms_order WHERE orderId=?";
        
            pst = conn.prepareStatement(sql);
            String value2 = oidComboBox.getSelectedItem().toString();
            pst.setString(1, value2);
       
            pst.executeUpdate();
        
            //Load table
            tableload();
              
            JOptionPane.showMessageDialog(null, "Record Deleted Successfully !");
        }
        
        catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }   catch (ClassNotFoundException ex) {
                Logger.getLogger(CMS_foodOrder.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_FOdelete_btn_ActionPerformed

    private void FOsearch_btn_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FOsearch_btn_ActionPerformed
       
        try {
            jPanelOrder.removeAll();
            CMS_searchOrder so = new CMS_searchOrder();
            jPanelOrder.add(so).setVisible(true);
            
            CMS_searchOrder searchrecords =new CMS_searchOrder();
            searchrecords.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CMS_foodOrder.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CMS_foodOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_FOsearch_btn_ActionPerformed

    private void FOview_btn_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FOview_btn_ActionPerformed
      
        try {
            jPanelOrder.removeAll();
            CMS_viewOrder vo = new CMS_viewOrder();
            jPanelOrder.add(vo).setVisible(true);
            
            CMS_viewOrder viewall = new CMS_viewOrder();
            viewall.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CMS_foodOrder.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CMS_foodOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_FOview_btn_ActionPerformed

    private void FOinsert_btn_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FOinsert_btn_ActionPerformed
       
             String OrderID = oidComboBox.getSelectedItem().toString();
             String OrderQuantity = oqComboBox.getSelectedItem().toString();
             String ItemID = iIDbox.getText();
             String Date = ((JTextField)oDateChooseBox.getDateEditor().getUiComponent()).getText();
             String Price = oPriceBox.getText();
             
             //check null fields
             
             if (OrderID.isEmpty() || OrderQuantity.isEmpty() || ItemID.isEmpty() || Date.isEmpty() || Price.isEmpty()){
                    
                 getToolkit().beep();
                 JOptionPane.showMessageDialog(null, "Complete all the input fields!!");
             }
             else{
            String pattern = iIDbox.getText().trim();
            iIDbox.setText(pattern);
            
            if ((!pattern.isEmpty()) && (!pattern.matches("[0-9][0-9][0-9][0-9]")))
                    {
                        getToolkit().beep();
                        JOptionPane.showMessageDialog(null, "Invalid Input. Enter only 4 digits for ITEM ID!!");
                        iIDbox.setText("");
                    }
            else
            
            try {
//                Class.forName(driver);
//            conn=DriverManager.getConnection(url, user, pw);
                    int confirminsert = JOptionPane.showConfirmDialog(null,"Do you really want to insert this record?","Insert",JOptionPane.YES_NO_OPTION);
                    String sql = "INSERT INTO cms_order"
                            +"(orderQty, orderId, itemId, date, orderPrice)"
                            +"VALUES (?,?,?,?,?)";

                    pst = conn.prepareStatement(sql);

                    String value1 = oqComboBox.getSelectedItem().toString();
                    pst.setString(1, value1);
                    String value2 = oidComboBox.getSelectedItem().toString();
                    pst.setString(2, value2);
                    pst.setString(3,iIDbox.getText());
                    pst.setString(4,((JTextField)oDateChooseBox.getDateEditor().getUiComponent()).getText());
                    pst.setString(5,oPriceBox.getText());

                    pst.executeUpdate();

                     //Load table
                     tableload();

                      JOptionPane.showMessageDialog(null,"Record Inserted Successfully");
              
                } catch (HeadlessException | SQLException ex) {
                    JOptionPane.showMessageDialog(null,ex);
                  } catch (ClassNotFoundException ex) {
                Logger.getLogger(CMS_foodOrder.class.getName()).log(Level.SEVERE, null, ex);
            } 
       
            }
    }//GEN-LAST:event_FOinsert_btn_ActionPerformed

    private void FOupdate_btn_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FOupdate_btn_ActionPerformed
        
        
        int confirmupdate = JOptionPane.showConfirmDialog(null, "Do you really want to update this record ?","Update",JOptionPane.YES_NO_OPTION);
        if(confirmupdate==0){
            
            try {
//                Class.forName(driver);
//            conn=DriverManager.getConnection(url, user, pw);
                String sql = "UPDATE cms_order SET orderId=?,itemId=?,date=?,orderPrice=? WHERE orderQty=?";
                //UPDATE `cms_order` SET `orderQty`=[value-1],`orderId`=[value-2],`itemId`=[value-3],`date`=[value-4],`orderPrice`=[value-5] WHERE 1
                pst = conn.prepareStatement(sql);
                
                String value1 = oqComboBox.getSelectedItem().toString();
                pst.setString(5, value1);
                String value2 = oidComboBox.getSelectedItem().toString();
                pst.setString(1, value2);
                pst.setString(2,iIDbox.getText());
                pst.setString(3,((JTextField)oDateChooseBox.getDateEditor().getUiComponent()).getText());
                pst.setString(4,oPriceBox.getText());
                
                pst.executeUpdate();
                
                //Load table
                  tableload();
                  
                JOptionPane.showMessageDialog(null,"Record Updated Successfully !");
                
            } catch (HeadlessException | SQLException ex) {
                JOptionPane.showMessageDialog(null,ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CMS_foodOrder.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
    }//GEN-LAST:event_FOupdate_btn_ActionPerformed

    private void jTable_OrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_OrderMouseClicked
     
        int r = jTable_Order.getSelectedRow();
        
        String OrderID = jTable_Order.getValueAt(r, 0).toString();
        String OrderQuantity = jTable_Order.getValueAt(r, 1).toString();        
        String ItemID = jTable_Order.getValueAt(r, 2).toString();
        String dateValue = jTable_Order.getValueAt(r, 3).toString(); 
        String Price = jTable_Order.getValueAt(r, 4).toString();    
      
    try{ 
        java.util.Date date = new SimpleDateFormat("MMM d,yyyy").parse(dateValue);
        oqComboBox.setSelectedItem(OrderID);
        oidComboBox.setSelectedItem(OrderQuantity);
        iIDbox.setText(ItemID);
        oDateChooseBox.setDate(date);
        oPriceBox.setText(Price);
    }
    catch(ParseException e){
        JOptionPane.showMessageDialog(null, e);
        
    }
       
    }//GEN-LAST:event_jTable_OrderMouseClicked

    private void oPriceBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oPriceBoxKeyTyped
      
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)|| (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Enter NUMERIC values!!");
        
        }
    }//GEN-LAST:event_oPriceBoxKeyTyped

    private void FOvrefresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FOvrefresh_btnActionPerformed
       //Clear rows
        refresh();
    }//GEN-LAST:event_FOvrefresh_btnActionPerformed

    private void IREPORT_orderIDorderDate_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IREPORT_orderIDorderDate_BTNActionPerformed
      
        
        //SELECT * FROM cms_order WHERE orderPrice > $P(porderPrice);
//        
//        HashMap fp_p1 = new HashMap();
//        fp_p1.put("porderPrice", txtfineReport.getText());
//
//        IREPORT_PARAMETERIZED showReport_fp = new IREPORT_PARAMETERIZED("C:\\Users\\Hashini\\Desktop\\3.jasper", fp_p1);
//        showReport_fp.setVisible(true);
//        
        HashMap fp_p1 = new HashMap();
        fp_p1.put("pprice", jTextField1.getText());
        
        IREPORT_PARAMETERIZED showReport_fp = new IREPORT_PARAMETERIZED("C:\\xampp\\htdocs\\ITP\\Project\\VIVA\\IREPORTS\\CMS_OrderP.jasper", fp_p1);
        showReport_fp.setVisible(true);
        
    }//GEN-LAST:event_IREPORT_orderIDorderDate_BTNActionPerformed

    private void IREPORTorder_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IREPORTorder_BTNActionPerformed
        // TODO add your handling code here:
        
////        
////	//Quary
////        SELECT * FROM cms_order
////          
////          try {
////            String feedback_report = "G:\\2nd Year Sem 2\\ITP\\IREPORTS\\HMS_feedback_report.jrxml";
////            JasperReport jr = JasperCompileManager.compileReport(feedback_report);
////            JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
////            JasperViewer.viewReport(jp, false);
////
////        } catch (Exception e) {
////            JOptionPane.showMessageDialog(null, e);
////        }
 try {
            String studentList = "C:\\xampp\\htdocs\\ITP\\Project\\VIVA\\IREPORTS\\CMS_AllOrdersN.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(studentList);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
            JasperViewer.viewReport(jp, false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
    }//GEN-LAST:event_IREPORTorder_BTNActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FOdelete_btn_;
    private javax.swing.JButton FOinsert_btn_;
    private javax.swing.JButton FOsearch_btn_;
    private javax.swing.JButton FOupdate_btn_;
    private javax.swing.JButton FOview_btn_;
    private javax.swing.JButton FOvrefresh_btn;
    private javax.swing.JButton IREPORT_orderIDorderDate_BTN;
    private javax.swing.JButton IREPORTorder_BTN;
    private javax.swing.JTextField iIDbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelOrder;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Order;
    private javax.swing.JTextField jTextField1;
    private com.toedter.calendar.JDateChooser oDateChooseBox;
    private javax.swing.JTextField oPriceBox;
    private javax.swing.JComboBox<String> oidComboBox;
    private javax.swing.JComboBox<String> oqComboBox;
    // End of variables declaration//GEN-END:variables

   

    
}
